### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rezha1902** [pupunzi/jquery.mb.YTPlayer#103]
Hai pupunzi, can you help me please.

I have the problem with jquery, the notice say Uncaught TypeError: undefined is not a function, 
i use jscript from your raw demo.

![uncaguht](https://cloud.githubusercontent.com/assets/11847250/7039014/cc78b2c8-dde4-11e4-8ae9-2fd20cedf3c8.JPG)

http://jsbin.com/kehukecasi/1/edit

**Comment by pupunzi** [comment]
This error is generally thrown if the jquery.mb.YTPlayer.js is not correctly included in the page...
