### ISSUE TITLE
Pause / Play Button Combine in one ?

### ISSUE THREAD

**Issue by Zofk** [pupunzi/jquery.mb.YTPlayer#109]
Hello, 
How can I combine these two buttons in one ?

<button onclick="$('#bgndVideo').playYTP()" >play</button>
<button onclick="$('#bgndVideo').pauseYTP()">pause</button>

In fact, I'd like the video stops  in the middle and then a pause/play button appears...
Any ideas ?

Many thanks ! 

Regards !

**Comment by pupunzi** [comment]
Hi,
If you are using the latest release:

*To create a toggle button for play/pause this is the function:*

        $.fn.playPauseYTP = function(YTP){
          if(YTP[0].state == 1) { //if the player is playing
            YTP.pauseYTP();
            this.html("play")
          } else {
            YTP.playYTP();
            this.html("pause")
          }
        }

And you can use it as follow:

        <button onclick="$(this).playPauseYTP($('#bgndVideo'))">
play/pause</button>


*To stop and show the button when the YTplayer reach a certain time:*

$('#bgndVideo').on("YTPTime", function (e) {
                var currentTime = e.time; //current player time in seconds

                if (currentTime  == 120){
                    $('#bgndVideo').pauseYTP();
                     $('#your button').show();
               }
})


Bye,
Matteo


P.S.:  If you like this plugin and you are satisfied by the support, *please
consider a donation
<https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=V6ZS8JPMZC446&amp;lc=GB&amp;item_name=mb%2eideas&amp;item_number=MBIDEAS&amp;currency_code=EUR&amp;bn=PP%2dDonationsBF%3abtn_donateCC_LG_global%2egif%3aNonHosted%22>*.
It's always appreciated and can guaranty the development.




2015-04-22 12:31 GMT+02:00 Zofk <notifications@github.com>:

> Hello,
> How can I combine these two buttons in one ?
>
> play
> pause
>
> In fact, I'd like the video stops in the middle and then a pause/play
> button appears...
> Any ideas ?
>
> Many thanks !
>
> Regards !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pupunzi/jquery.mb.YTPlayer/issues/109>.
>



-- 

*█*

*matteo bicocchi*
pupunzi.com
pupunzi.open-lab.com
art director
*open lab s.r.l.*
comunicazione

via venezia 18b 50121 firenze italia
telefono +39 055 5522779

open-lab.com
twproject.com

*█*

**Comment by Zofk** [comment]
Thanks you Matteo !

The first function (pause/play) button works very well. 

But I met difficult with the second step 
'*To stop and show the button when the YTplayer reach a certain time:*'

Do I have to put this function after the first one ?

I saw that I have to replace $('#your button').show();  by my button's name.

So if I understand, I have to put : 

  <button id="test" onclick="$(this).playPauseYTP($('#bgndVideo'))">play/pause</button> 
And replace  $('#test').show();

It doesn't work :( 

Regards,

**Comment by pupunzi** [comment]
If you have an URL where I can see your page I probably can help you.

**Comment by Zofk** [comment]
Can I send you the folder by email ?

**Comment by Zofk** [comment]
Date: Thu, 23 Apr 2015 01:09:30 -0700

**Comment by Zofk** [comment]
I don't have public url... But it doesn't matter, I will try to resolve this.
Many thanks for you response. 



THE JAVASCRIPT

 <script type="text/javascript"> 
$(document).ready(function () {

    $("#bgndVideo").mb_YTPlayer();
	

});

$.fn.playPauseYTP = function(YTP){
if(YTP[0].state == 1) { //if the player is playing
YTP.pauseYTP();
this.html("play")
} else {
YTP.playYTP();
this.html("pause")
}
}

$('#bgndVideo').on("YTPTime", function (e) {
var currentTime = e.time; //current player time in seconds

if (currentTime == 120){
$('#bgndVideo').pauseYTP();
$('#buttontest').show();
}
})

</script>

THE HTML

<section class="video-section">
  <div class="pattern-overlay">
  <div class="buttons-container">
<button id="buttontest" onclick="$(this).playPauseYTP($('#bgndVideo'))">play/pause</button>
  <a id="bgndVideo" data-property="{videoURL:'http://youtu.be/_sdGwpKusaw', containment:'.video-section', quality:'highres', autoPlay:true, loop:true, addRaster:false,  mute:true, opacity:1  }"></a>
    </div>
    
 </section>
