### ISSUE TITLE
Background video is replaced by black background when scrolling in Safari 5.1.7 (Windows)

### ISSUE THREAD

**Issue by SnakeME** [pupunzi/jquery.mb.YTPlayer#110]
Hi,

When we implement the video in the background and test via safari, we see a black area which overlays the video when we start scrolling down.

For example on your demo page (http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html), if we resize the window and make it very small, it starts to show a black background when we scroll down.

![screen1](https://cloud.githubusercontent.com/assets/1651752/7493110/398936c4-f3fe-11e4-8e70-8eb02c8cba76.jpg)
![screen2](https://cloud.githubusercontent.com/assets/1651752/7493111/399dbe46-f3fe-11e4-999e-2e2a4c651b24.jpg)
![screen3](https://cloud.githubusercontent.com/assets/1651752/7493112/39bbbb12-f3fe-11e4-9026-eca56f916f53.jpg)

This problem occurs in Safari 5.1.7 for Windows. All other browsers are working fine.

**Comment by pupunzi** [comment]
Hi,
Safari for windows has been dismissed from Apple 3 years ago... Actually the OSX version is 8.0.5.
Probably the behavior you are describing is due to the old rendering engine that Safari was using years ago, but I can't give you support on an old browser anymore supported.
Sorry,
Matteo
