### ISSUE TITLE
getDataFromFeed function broken, broken videoData returned from API

### ISSUE THREAD

**Issue by tnke** [pupunzi/jquery.mb.YTPlayer#111]
Hi, firstly thank you for the wonderful plugin.

Today I noticed all my "self contained" background videos were showing a YouTube error message as the preload thumbnail, same thing is happening in the custom demo: http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_as_player.html

Fixed it temporarily for myself by commenting out most of the getDataFromFeed function.

**Comment by pupunzi** [comment]
Hi,
Just two days ago Google has definitely removed the Youtube API v.2 used by this component to get  the data for the poster-frame and several other things. I'm working on that fix and hopefully it will available in the next days.
