### ISSUE TITLE
Content becomes invisible when scrolling in Safari 8.0.5 (OSX)

### ISSUE THREAD

**Issue by SnakeME** [pupunzi/jquery.mb.YTPlayer#112]
Hi,

Another problem we've discovered is that the content of our site becomes invisible when we scroll through the page in Safari 8.0.5 (OSX).

http://mediaworker.com/jobs

When we remove the video player the content remains fully visible.

We tried to discover what causes the problem but unfortunately didn't found a solution yet.

**Comment by pupunzi** [comment]
As I can see you are not including the "YTPlayer.css" file that should prevent that issue in Safari.
Try adding the CSS and let me know.

Bye,
Matteo

**Comment by SnakeME** [comment]
Hi,

We've included the css file but unfortunately the same issue still occurs. When the video is loading all of the content is visible, but as soon as the video starts playing some parts of the content disappear. As soon as we remove the video player the issue is solved.

**Comment by pupunzi** [comment]
Does this test page works for you?
http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_smuthScroll.html

I just tested it on a macbook pro retina and this works fine. If that works for you the issue could be a CSS conflict between the YTPlayer css and your site css. I notice that if you roll over the "got to top" arrow the content appears... I'm not able to figure out what is the problem... If you send me a static page I can make some test.

Bye,
M

**Comment by pupunzi** [comment]
Hunting for the cause of your issue I get the solution; For some mysterious reason Safari run on that flickering issue if you don't have a wrapper that include all the content of the page. If you wrap all the page content excluded the "header_container" inside a div it should work fine.

here is an example page using your code: http://pupunzi.open-lab.com/test/safari-test/index.html
and here a zip with the code: http://pupunzi.open-lab.com/test/safari-test.zip

Those two links will be alive for few days.

Bye,
Matteo

**Comment by SnakeME** [comment]
Thank you very much, this solved the issue.
One more thing I can add to the strange browser behaviour list ;)

Keep up the great work!
