### ISSUE TITLE
Youtube video showing devicesupport warning

### ISSUE THREAD

**Issue by manueltomasir** [pupunzi/jquery.mb.YTPlayer#113]
This is a new issue for me. I've been using this plugin for a while on this site.

Recently I noticed the devicesupport warning screen shows up prior to the video itself loading. Is there any way to get rid of this and just show the thumbnail/poster for the video instead as it was before?

Please let me know as soon as possible, this is very urgent.

Please email me directly at manuel@karo.com, if you need more details on my specific implementation. The code running the video is below...

`<header class="video-header" id="$URLSegment">
	<div class="row">
		<%-- Fallback Image --%>
		<div class="slide-img-bg" style="">
			<div class="player" style="display:block; margin: auto; background: rgba(0,0,0,0.5)" data-property="{
				videoURL:'http://youtu.be/$RowVideoId',
				containment:'self',
				ratio: '16/9',
				startAt:0,
				mute:true,
				autoPlay:true,
				loop:true,
				opacity:1,
				showControls: false,
		        showAnnotations: false,
		        showYTLogo: false,
		        stopMovieOnClick: false,
				realfullscreen:true}" >
				</div>
		</div>
		<span>$RowText</span>
	</div>
</header>`

**Comment by pupunzi** [comment]
Just two days ago Google has definitely removed the Youtube API v.2 used by this component to get  the data for the poster-frame and several other things. I'm working on that fix and hopefully it will available in the next days.
Are you using the Wordpress component or you implemented it on your site using the jQuery one?

**Comment by manueltomasir** [comment]
I'm using the Jquery version...

**Comment by menasbeshay** [comment]
I'm facing the same issue

**Comment by olziinaa** [comment]
Thanks for the amazing jQuery plugin. Tt improve my website and save my time. i have same issue. When will fix it?

**Comment by pupunzi** [comment]
Updating to the latest version will solve this issue.

**Comment by olziinaa** [comment]
Thanks for the your update.
