### ISSUE TITLE
Mute Function doesn't work anymore :(

### ISSUE THREAD

**Issue by leoz2007** [pupunzi/jquery.mb.YTPlayer#114]
Hello,
When I use toggleVolume like this
```
<button onclick="$(this).toggleVolume()">Mute/Unmute</button>
```

I have an issue on Chrome
```
Uncaught TypeError: Cannot read property 'isMuted' of undefinedjQuery.fn.toggleVolume @ jquery.mb.YTPlayer.js:1283onclick @ index3.html:80
```

So i Try with YTPToggleVolume
```
<button onclick="$(this).YTPToggleVolume()">Mute/Unmute</button>
```

But I also have an error
```
Uncaught TypeError: $(...).YTPToggleVolume is not a function
```

Anyone has an idea?
Thanks

**Comment by pupunzi** [comment]
Hi,
It can't work if you use $(this) as in that case you are referring to the button itself and not at the player...

It will work if you refer to the player itself:

$("#myPlayer").YTPlayer();

....

```
<button onclick="$("#myPlayer").toggleVolume()">Mute/Unmute</button>
```
Bye,
Matteo
