### ISSUE TITLE
Demo's not working on server

### ISSUE THREAD

**Issue by Ronnos** [pupunzi/jquery.mb.YTPlayer#115]
I started today with YTPlayer and see that this is a new version (since 3 days). 
The demo versions don't work. My browser gives me an error that the apikey.js isnt available (404).
I think this file isnt necessary.. but I can't debug it.

I don't know  what changes there have been made since last version...

**Comment by pupunzi** [comment]
Hi,
just remove the inclusion of the apikey.js from the header of the demo page.

Bye,
Matteo

**Comment by Ronnos** [comment]
Matteo,

Thx for your fast response, removing the apikey.js script doesnt solve my problem. Now there is no error displayed in webdeveloper tab. But there is also no video playing...

Bye, Ron

**Comment by Ronnos** [comment]
Matteo,

I fixed demo.html now... I coppied the script in the headtag from your live demo.html into mine. I saw there were couple major changes. After i used your script it was working again...

I will now try for the other demo's

**Comment by Ronnos** [comment]
Matteo,
I used the jquery.mb.YTPlayer.js version 2.8.5 (u use on your site), this solved all my problems. Im not sure what is causing the problem in 2.9.0 version...
Thx

**Comment by pupunzi** [comment]
I'll check what could be wrong with the 2.9.0 as it use to work on my tests.

Bye,
M

**Comment by Ronnos** [comment]
Thx, I searched it, but couldnt find.
Is there a possibility to Toggle Sound/Volume?

Bye

**Comment by pupunzi** [comment]
that issue has been solved in the 2.9.1 update.
