### ISSUE TITLE
Mute not working

### ISSUE THREAD

**Issue by jacomensink** [pupunzi/jquery.mb.YTPlayer#116]
The mute option is not working anymore, see demopage http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html for more information.

**Comment by pupunzi** [comment]
It is working fine for me...
from both the button on the top (external call) and from the control bar on the bottom.
What browser and what OS are you using?

**Comment by jots** [comment]
mute is not working for me either:
http://jsbin.com/wonegilupo/1/edit?html,output

chrome 42.0.2311.82 beta on linux.

**Comment by jacomensink** [comment]
I can toggle the mute button, but the initial mute option is not working here.

chrome 42.0.2311.135 m - windows 8 (64 bit)

**Comment by prafgon** [comment]
Same here!

**Comment by pupunzi** [comment]
here is a demo page with the video starting mute and with all the available controls managed from external buttons:
http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_ext_methods.html

This page is working fine for me...

**Comment by prafgon** [comment]
Hi there,

Thanks for a quick reply, I've just noticed that indeed the site you posted works fine. I downloaded the code, went through it but unfortunately I have everything just the same as there. I created a demo page for you to see the issue live:

http://veented.com/workshops/north/north2/?page_id=721

You can go through the source code to check it all out. The "Read More" button is supposed to scroll down and also MUTE the video (it's in the jquery.custom.js file).

**Comment by pupunzi** [comment]
@prafgon checking the YTPlayer inclusion on your page I just noticed that while the js file is updated to almost last version (now it is the 2.9.1 and I would suggest to get the latest Master from gitHub where some important fix have been done and not yet published); the CSS file you are including is 2 years old and that could be the cause of your issue.

So first update every part of the component to the latest version; I'm sure this will fix your issue.

Bye,
Matteo

**Comment by prafgon** [comment]
Hi Matteo,

This is legend, the css update actually fixed the problem! Never thought a stylesheet could be a problem for this kind of a problem! Thanks a lot sir, you are great and keep up the good work. :+1:


Regards,
FJ

**Comment by pupunzi** [comment]
@jots here is a jsBin with the working demo: http://output.jsbin.com/jolocipalo/edit?html,output
Just added the CSS file and removed the $('#bgndVideo').YTPMute() on the document ready because it would throw an error as the Youtube player has not been defined yet.

**Comment by jacomensink** [comment]
@pupunzi Thanks for the quick response. The problem is that `.mb_YTPBar.compact .simpleSlider` needs a width for mute to work.

**Comment by jots** [comment]
thank you @pupunzi !  looks like the missing css file was the culprit.
