### ISSUE TITLE
Multiple player autoplay in a same time.

### ISSUE THREAD

**Issue by leoz2007** [pupunzi/jquery.mb.YTPlayer#117]
Hello guys,

I don't understand why but autoplay:false doesn't work for me.
I have two players, one I want to autoplay and another I want to play when I click on a button.

```
<div id="P3" class="player" data-property="{videoURL:'4E8wL2ZUU3o',
containment:'#customElement', showControls:false, autoPlay:true, mute:false,
 startAt:0, opacity:1, addRaster:true, quality:'default'}">My video</div>

<div id="P4" class="player" data-property="{videoURL:'rLVvUNmc3HA',
containment:'#customElement2', showControls:false, autoplay:false, loop:false, mute:false,
 startAt:0, opacity:1, addRaster:true, quality:'default'}">My video</div>
```

Any tricks to stop autoplay on the second video?

Thanks for this plugins btw!

**Comment by pupunzi** [comment]
Options are case sensitive; for the "P4" player you write: autoplay:false while it should be **autoPlay:false**. Just set the correct case and it will work.

Bye,
Matteo

**Comment by leoz2007** [comment]
Hey Matteo,
Thanks for your answer but I still have a trouble.
When I user autoPlay:false instead of autoplay:false my video don't load.

Example: http://www.leamaleh.com/new2/index3.html

**Comment by pupunzi** [comment]
This issue has been fixed. You can download the master from here: https://github.com/pupunzi/jquery.mb.YTPlayer/archive/master.zip
