### ISSUE TITLE
"Access Denied" for localstorage in ALL IEs

### ISSUE THREAD

**Issue by ak545** [pupunzi/jquery.mb.YTPlayer#119]
Hi, Matteo!

About "Access Denied" for localstorage in ALL IEs.

If replace all localStorage to sessionStorage then this error is fix and all work in all browsers (and in all IEs also) corrected.

jQuery.mbStorage={
		set:function(a,b){
			b=JSON.stringify(b),
			    sessionStorage.setItem(a,b)
			    //localStorage.setItem(a,b)
		},
		get:function(a){
			return sessionStorage[a]?JSON.parse(sessionStorage[a]):null
			//return localStorage[a]?JSON.parse(localStorage[a]):null
		},
		remove:function(a){
			a?sessionStorage.removeItem(a):sessionStorage.clear()
			//a?localStorage.removeItem(a):localStorage.clear()
		}
	};

Best Regards,
Andrey Klimov.

P.S. Sorry for my bad English.

**Comment by pupunzi** [comment]
Hi Andrew,
Thank you for the hint; that could be a solution but I would like to preserve the stored data cross session so I'll refine the function in the way that only IE will use sessionStorage if localStorage is not available.

Bye,
Matteo

**Comment by ak545** [comment]
Hi, Matteo.
Yes, of course. It will be so better.
Bye,
Andrey.
