### ISSUE TITLE
Since update Not full screen anymore

### ISSUE THREAD

**Issue by FastWP** [pupunzi/jquery.mb.YTPlayer#120]
After the update for new Youtube Api the video seems not to be full screen anymore. Any new settings ? http://screencast.com/t/rLArRvEq - especially on lower resolutions
Best Regards.

**Comment by martindebrunne** [comment]
Hi,
I've not problem about this page http://wisten.demo.fastwp.net/?styleId=3. It seems to work...
When I tried with files demo from git repository, It works again.

I use google chrome on Ubuntu 14.04 LTS 42.0.2311.90 (64-bit)

Can I get more information ?

**Comment by pupunzi** [comment]
Hi,
You have the *optimizeDisplay* option set to *false* and that sets the
player to the 100% of the available width without optimizing the size to
cover the space with the video.

Just change that option to* true*.

Bye,
Matteo


P.S.:  If you like this plugin and you are satisfied by the support, *please
consider a donation
<https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=V6ZS8JPMZC446&lc=GB&item_name=mb%2eideas&item_number=MBIDEAS&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG_global%2egif%3aNonHosted>*.
It's always appreciated and can guaranty the development.


2015-05-27 16:20 GMT+02:00 martindebrunne <notifications@github.com>:

> Hi,
> I've not problem about this page http://wisten.demo.fastwp.net/?styleId=3.
> It seems to work...
> When I tried with files demo from git repository, It works again.
>
> I use google chrome on Ubuntu 14.04 LTS 42.0.2311.90 (64-bit)
>
> Can I get more information ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pupunzi/jquery.mb.YTPlayer/issues/120#issuecomment-105928832>
> .
>



-- 

*█*

*matteo bicocchi*
pupunzi.com
pupunzi.open-lab.com
art director
*open lab s.r.l.*
comunicazione

via venezia 18b 50121 firenze italia
telefono +39 055 5522779

open-lab.com
twproject.com

*█*

**Comment by FastWP** [comment]
Hi, works & donated. <br> Best Regards.

**Comment by pupunzi** [comment]
Hi,
Thank you for the donation,
really appreciated,

Best regards,
Matteo

2015-05-27 18:01 GMT+02:00 FastWP <notifications@github.com>:

> Hi, works & donated.
> Best Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pupunzi/jquery.mb.YTPlayer/issues/120#issuecomment-105976223>
> .
>



-- 

*█*

*matteo bicocchi*
pupunzi.com
pupunzi.open-lab.com
art director
*open lab s.r.l.*
comunicazione

via venezia 18b 50121 firenze italia
telefono +39 055 5522779

open-lab.com
twproject.com

*█*

**Comment by niek33** [comment]
I have the same problem here, even with the following settings. It did work before, so I guess it has something to do with the update. 

<section class="content-section video-section">
  <div class="pattern-overlay">
  <a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=XXXXX', optimizeDisplay:true, containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}">bg</a>
</div>
</section>

Thanks in advance!

**Comment by NazarkinRoman** [comment]
+1.. Same problem(for example - http://wphunters.com/axis/), optimizeDisplay is true by default. 
Google Chrome 43.0.2357.124, mac. On safari everything is okay.

Looking for a solution.. Thanks in advance too!

**Comment by niek33** [comment]
I solved this, had to update my jQuery to a newer version (2.1.1).

**Comment by NazarkinRoman** [comment]
Hmm.. How this can vary on jQuery version? But anyway, thanks for advice.. 
I have tested my demo site with jQuery 2.1.1 - result the same :(

**Comment by pupunzi** [comment]
@NazarkinRoman : Update the mb.YTPlayer to the latest version: http://pupunzi.open-lab.com/mb-jquery-components/jquery-mb-ytplayer/

Bye,
Matteo
