### ISSUE TITLE
Ajax Call - Reinitialize bg Player to pull new contents link information.

### ISSUE THREAD

**Issue by allisongrey** [pupunzi/jquery.mb.YTPlayer#121]
I am running a bgvideo that loads per page. It works fine for each page until I use Ajax to move from page to page. The Wrapper is created by the plugin in wordpress outside the ajax content area. I have tried putting:

  $(function(){
      $(".player").YTPlayer();
        });

.. inside for the initialize page function that is trigger when ajax loads the new content. Doing this for the other functions I am running works fine, but not for this one. Am I calling the wrong thing? 

This code is in the top of each page inside of the ajax-content wrap:

 <div id="bgndVideo" class="player" 
     data-property="{videoURL:'<?php echo $youtube_url; ?>',containment:'body',autoPlay:true, quality:'defailt', mute:false, showControls:false, realfullscreen:false, startAt:<?php echo $youtube_startoffset; ?>, opacity:1}">
</div> 

It refreshes fine from page to page but the .mbYTP_wrapper div that the plugin creates stays the same with the same link. It doesn't continue playing though it pauses on the load so its not even completely working outside of the ajax.

I also can't figure out how to recall the playerstate to update buttons etc if the video is playing or has stopped etc. This isn't a huge deal because I don't actually want the player to work outside the ajax, I want it to be destroyed and reinitialized with the new pages link / settings on every content pull.

Any help would be super appreciated!

**Comment by glinesbdev** [comment]
I had to wrap it around a

$(window).on('load', function() {
$('#player').YTPlayer();
});

Today when using this library. Hope it helps.

**Comment by allisongrey** [comment]
Hey that initializes it the first time, but I feel like I need to somehow call YTPPlayerDestroy(); or something and then reload with the rest of the functions that are reinitialized after the ajax call?

**Comment by glinesbdev** [comment]
You can do a success (or done) Ajax callback and throw the methods you need
to call in there. Here are the Ajax docs for jquery and in them you will
find these callback methods: http://api.jquery.com/jquery.ajax/
