### ISSUE TITLE
add YTPLoaded event

### ISSUE THREAD

**Issue by wijzijnwolf** [pupunzi/jquery.mb.YTPlayer#122]
Could you implement an onloaded event?
An event that triggers at the same time the loading div switches text from 'loading' to 'ready'

the YTPUnstarted & YTPBuffering events dont trigger until the video starts playing (either manually or autoplay)

**Comment by pupunzi** [comment]
Hi,
there's the "YTPReady" event that is triggered once the player is ready to play:

```javascript
var myPlayer = jQuery("#P1").YTPlayer();
myPlayer.on("YTPReady", function(){
                alert("ready")
            })
```

**Comment by wijzijnwolf** [comment]
Thank you, the YTPReady event was exactly what i needed. Keep up the good work!
