### ISSUE TITLE
Possible to play mp4s stored in s3 (or elsewhere) rather than Youtube?

### ISSUE THREAD

**Issue by hhitch** [pupunzi/jquery.mb.YTPlayer#123]
Hi there, I really like this player, I'm trying to implement it into an application, but it appears it only works with Youtube. Is that the case? I would really like to use it for our propietary videos that are not stored on Youtube.

Thanks in advance for your response!

Hugh

**Comment by pupunzi** [comment]
Hi,
Actually this component works only for videos hosted on Youtube. I'm working on the self hosted video player component but it is not available at the time.
Bye,
Matteo
