### ISSUE TITLE
Delay before the start

### ISSUE THREAD

**Issue by Le-future** [pupunzi/jquery.mb.YTPlayer#126]
Hi there,

Still in love with your plugin, I would like to know if there was a trick to apply a fadeOut to my loading screen exactly when the video is starting.

Actually, for the moment, the loading is fadeOut via the $(window).load(function() { but the video starts 4 or 5 seconds later.

Best regards

**Comment by pupunzi** [comment]
Hi,
The player has its own start event you can use to fade out the loader.
Here is an example of the use:

```javascript
var myPlayer = jQuery( "#bgndVideo" ).YTPlayer();
myPlayer.on("YTPStart", function(){
   //your code to fade out the loader goes here...
});
```
Hope this help,
Bye,
Matteo

**Comment by Le-future** [comment]
Thanks for your answer Matteo :smiley: 

I'll try that next week
