### ISSUE TITLE
Video only looping half way

### ISSUE THREAD

**Issue by iampstew** [pupunzi/jquery.mb.YTPlayer#127]
Tried adding the video ID of what am wanting to use for my background and it only seem's it plays half of the video, I tried several different video at different duration's and all have cut half the time and loop back to the beginning. 

<div id="videoBg" class="background-video">
<div id="bgndVideo" class="player" 
     	data-property="{videoURL:'http://youtu.be/uvSupdP3Ijw',containment:'#videoBg',autoPlay:true, mute:true, startAt:0, opacity:1, quality:'hd720'}">
	</div>
</div>

Also receiving error messages on my console.log 

![image](https://cloud.githubusercontent.com/assets/11520896/8334662/0417c866-1a91-11e5-98af-46c95f32dcf8.png)

**Comment by pupunzi** [comment]
You should provide an url where I can see the issue. From what you say it seams you've set the "stopAt" property but I can't help you without seeng what's going on.

Bye

**Comment by iampstew** [comment]
Sorry yeah, my bad cause its a client URL i don't have permissions to send it out externally :( but, we just modified the video added black screen to extend it during the loop, once it goes live il send the URL for future reference man, again apologies.

It is weird though, seem's like it just stops half way of the video and loops back :/
