### ISSUE TITLE
Very short video are not played to the end.

### ISSUE THREAD

**Issue by ikixxx** [pupunzi/jquery.mb.YTPlayer#129]
Using the `playlist` functionality of the plugin, if you use very short movies  `~10s`, they are not played all the way to the end. Checkout out this playlist for testing purposes.
```` javascript 
var playlist = [
                'https://www.youtube.com/watch?v=yWaelIrAv9A',
                'https://www.youtube.com/watch?v=zr9leP_Dcm8',
                'https://www.youtube.com/watch?v=ekwF2bnHf84',
                'https://www.youtube.com/watch?v=GAHATYO18uA',
]
````

**Comment by pupunzi** [comment]
Hi,
The player actually stops the video three seconds befor the end to prevent the display of the "play" button it use to show at the end of a video. In the truth this time can be shortened to 1 second (just made few test but it seams to work).

change line 1180
from:
```
if( YTPlayer.player.getPlayerState() == 3 ...
```
to:
```
if( YTPlayer.player.getPlayerState() == 1 ...
```

Bye,
Matteo

**Comment by ikixxx** [comment]
Will you change this code in master? If so, I will just wait for the update.

**Comment by pupunzi** [comment]
It will be available with the next major release.
