### ISSUE TITLE
Playlist callback `videoData` is null

### ISSUE THREAD

**Issue by ikixxx** [pupunzi/jquery.mb.YTPlayer#130]
First parameter of the callback is the `video` html element , but `videoData` property on the element is `null`.

**Comment by pupunzi** [comment]
The videoData object is available only if you set the Youtube API key (https://github.com/pupunzi/jquery.mb.YTPlayer/wiki#ytpdata-event) introduced with the v.3 of their API otherwise it will return null.

Bye,
Matteo

**Comment by ikixxx** [comment]
Thanks.
