### ISSUE TITLE
www-embed-player.js errors?

### ISSUE THREAD

**Issue by kprovance** [pupunzi/jquery.mb.YTPlayer#131]
I updated my outdated version of this script to the latest from this repo.  Now I'm seeing this output in the console log

www-embed-player.js:170 GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED

It happens about six different times with different chome-extension urls.

Any idea what this is about?

**Comment by Zackio** [comment]
Seeing the same thing

**Comment by bhamodi** [comment]
It appears to be an issue on Google's side. They check for the existence of the Chrome Cast extension and this causes the errors that we see in the console.
Refer to this Google issue: https://code.google.com/p/google-cast-sdk/issues/detail?id=309
