### ISSUE TITLE
CSS Class .fullscreen too general

### ISSUE THREAD

**Issue by thomasloeschnigg** [pupunzi/jquery.mb.YTPlayer#132]
Better to write .mbYTP_wrapper.fullscreen

**Comment by pupunzi** [comment]
The fullscreen class will be YTPFullscreen with the next release

**Comment by thomasloeschnigg** [comment]
Vielen Dank für Ihre E-Mail. Mein Büro ist vom 23.12.2015 bis 10.01.2016 geschlossen

In Notfällen erreichen Sie mich über die Notfall-SMS Funktion auf unserer Webseite unter: http://premium-webworks.com/notfall-sms.html

Info: diese E-Mail wird nicht weitergeleitet.

Mit freundlichen Grüßen
Thomas Löschnigg
