### ISSUE TITLE
Incorrect centering when set as element background

### ISSUE THREAD

**Issue by FastWP** [pupunzi/jquery.mb.YTPlayer#133]
I updated to latest version, but when script is set to display video as an element background is not centred anymore - screenshoot 

http://screencast.com/t/sW3paHwLd
http://screencast.com/t/2dxKwQfws3

Only thing changed was script version.

**Comment by pupunzi** [comment]
You should replace also the CSS file and verify if this issue is still there.

**Comment by FastWP** [comment]
With css seems fine, apart from not filling the entire width like previous setup - http://www.medico-pro.com/#c-Uberuns , or maybe i am missing something ?

**Comment by pupunzi** [comment]
The video you are pointing to is not covering the player frame even on the Youtube default player. 
You can try setting the ratio to "4/3" instead of the default "16/9":
```
{videoURL:'r1xohS2u69E', ...,ratio:'4/3'}
```

That will fit better the aspect ratio of the video.

Bye,
Matteo

**Comment by FastWP** [comment]
Got, it , thx.
