### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by zapiko** [pupunzi/jquery.mb.YTPlayer#134]
I can't use YTPlayer, I have this problem, help me please

YTPlayer.videoData = jQuery.mbStorage.get("YYTPlayer_data_" + YTPlayer.videoID);

<script src="/Scripts/jquery-2.1.4.js"></script>
<script src="/Scripts/jquery-migrate-1.2.1.min.js"></script>
<script src="/Scripts/jquery.mb.YTPlayer.js"></script>

**Comment by icalphil** [comment]
Hey Zapiko, Try the suggestion in the following http://support.pixelentity.com/threads/13737-Issue-with-Landing-Page-Video.
