### ISSUE TITLE
Background image does not scale to the video size

### ISSUE THREAD

**Issue by manojarora342** [pupunzi/jquery.mb.YTPlayer#136]
Hi,
I want to set a background image till the time video is getting loaded on my website. Now my question is that how can i set the background image on the placeholder of video so that it exactly matches the video dimensions on the screen. Currently there is abrupt change once the video is loaded and thumbnail is hidden which does not look good. Is there any way that youtube channel can provide the thumbnail image on the top of the video and the plugin can be customized to show that thumbnail as per the video dimension.

**Comment by fseminario** [comment]
having the same issue here 
![screen shot 2015-08-28 at 9 08 10 am](https://cloud.githubusercontent.com/assets/4037582/9551175/53372404-4d64-11e5-9c81-24eee960b755.png)

**Comment by cdesch** [comment]
+1 how to do this?

**Comment by pupunzi** [comment]
Hi,
You can do it via CSS setting the "background-size" property to "cover" or to "contain".
Bye,
Matteo
