### ISSUE TITLE
YTPlaylist not looping properly

### ISSUE THREAD

**Issue by gdnwebmedia** [pupunzi/jquery.mb.YTPlayer#139]
I'm trying to play the first video, (5 min youtube video) works great... the want to loop the second video (11 seconds youtube video) plays only once and then go back and loop the entire playlist instead of the second video only.

See the code I'm using below.

```
      var videos = [
			{
				videoURL:'xxxxxxxxxvideoIDxxxxxxxxxx',
				containment: "body",
				ratio: "auto", // "auto", "16/9", "4/3"
				startAt: 0,
				stopAt: 0,
				autoPlay: true,
				vol: 90, // 1 to 100
				addRaster: false,
				opacity: 1,
				quality: "default", //or "small", "medium", "large", "hd720", "hd1080", "highres"
				mute: false,
				loop: false,
				showControls: true,
				showAnnotations: false,
				showYTLogo: false,
				stopMovieOnBlur: false,
				realfullscreen: true,
				gaTrack: true,
				optimizeDisplay: true},
			{
				videoURL:'xxxxxxxxxvideoIDxxxxxxxxxx',
				containment: "body",
				ratio: "auto", // "auto", "16/9", "4/3"
				startAt: 0,
				stopAt: 0,
				autoPlay: true,
				vol: 100, // 1 to 100
				addRaster: false,
				opacity: 1,
				quality: "default", //or "small", "medium", "large", "hd720", "hd1080", "highres"
				mute: false,
				loop: true,
				showControls: true,
				showAnnotations: false,
				showYTLogo: false,
				stopMovieOnBlur: false,
				realfullscreen: true,
				gaTrack: true,
				optimizeDisplay: true
			}
		];

		jQuery("#bgndVideo").YTPlaylist(videos, false);
```

Thoughts?

**Comment by pupunzi** [comment]
That is probably a bug :-)
I'll check for the issue.
Bye

**Comment by gdnwebmedia** [comment]
Any updates on a solution? It would be greatly appreciated.
Thanks!

**Comment by RitvikM** [comment]
^ same here, been trying to figure out a solution, but no luck yet

**Comment by gdnwebmedia** [comment]
Thinking out loud.... Could this be fixed by adding a function to play once all the videos in an array and have an option play once or loop the last video?  

I can see the issues of adding a loop : true option to the array -- ex: if you add that to the second video, the third video will never be seeing... but If the loop_last_video: true might force the array to play everything once, then loop the last one. or loop from the beginning.

Another idea could be to leave it as is, and add a second var videos [] line with one video only, we'll add the loop to it. so when the page loads, will play all the videos once form array1 and then will loop video from array2. 

Hope this at the very least prompts ideas to find a solution. Thanks

**Comment by gdnwebmedia** [comment]
any luck?

**Comment by pupunzi** [comment]
With the next major update you'll be able to loop videos inside a playlist. You could specify how many time a specific video should loop setting a number for the "loop" property or "true" to loop forever.

**Comment by gdnwebmedia** [comment]
Thank you! Looking forward to it.
