### ISSUE TITLE
loop-problem

### ISSUE THREAD

**Issue by dennobaby** [pupunzi/jquery.mb.YTPlayer#141]
Hi,

i want to use this nice plugin for this:
at first video 1 is playing (autostart). After video1 has finished video2 should start and this video2 should loop.

I use this:

```
var videos = [
						{videoURL: "video1",  containment:'body', autoPlay:true, mute:false, startAt:0, opacity:1, loop:false, ratio:"4/3", addRaster:false},
						{videoURL: "video2",containment:'body', autoPlay:true, mute:false, startAt:0, opacity:1, loop:true, ratio:"4/3", addRaster:false},
						
					];
					
                    $( 'myvideo' ).YTPlaylist(videos, false);
```

But after video2 has ended, video 1 begins.

Is this a bug or my failure?

Thanks

**Comment by pupunzi** [comment]
With the last release this issue has been fixed
