### ISSUE TITLE
Cannot read property 'msie' of undefined (google chrome)   line 159

### ISSUE THREAD

**Issue by ThePhoenix007** [pupunzi/jquery.mb.YTPlayer#142]
Uncaught TypeError: Cannot read property 'msie' of undefined(anonymous function) @ jquery.mb.YTPlayer.src.js:159n.extend.each @ jquery.js:374n.fn.n.each @ jquery.js:139jQuery.mbYTPlayer.buildPlayer @ jquery.mb.YTPlayer.src.js:96(anonymous function) @ (index):60

**Comment by pupunzi** [comment]
You should not use jquery.mb.YTPlayer.src.js but the jquery.mb.YTPlayer.js or the jquery.mb.YTPlayer.min.js  in the "dist" folder that are compiled with all the needed dependencies.
