### ISSUE TITLE
When scrolling in chrome the page is jumpy

### ISSUE THREAD

**Issue by waynobweno** [pupunzi/jquery.mb.YTPlayer#143]
When scrolling in Chrome v45.x this script really seems to make my browser quite jumpy, almost to the point where it is near impossible to scroll. I have removed all of the other js and css files from the page and I am still getting the same issues. This does not seem to be an issue with FF and Chrome. Anyone else experience this issue?

**Comment by pupunzi** [comment]
It doesn't happen to me...
