### ISSUE TITLE
Push Youtube video to left/down on Tab on the website

### ISSUE THREAD

**Issue by shoosah** [pupunzi/jquery.mb.YTPlayer#144]
Try to click once on the website when the website load finished and from that point press Tab several times to reach the youtube video. The Youtube logo would be shown (even if the showYTLogo is false) and it will push the video to the left/down.

**Comment by pupunzi** [comment]
This is due to the default browser behavior that focus the anchors on tab press; the YouTube logo get the focus and move the screen to make it visible. As the YT logo is inside an IFRAME and it is cross site I'm not able to stop this behavior.
