### ISSUE TITLE
External methods not working?

### ISSUE THREAD

**Issue by sjrichards88** [pupunzi/jquery.mb.YTPlayer#148]
Hi,

None of the external methods seem to be working, for example when using YTPStop() the following error is displayed in the console: Uncaught TypeError: $(...).YTPStop is not a function

I checked the demo pages and it looks like the same error is occurring.

Thanks

**Comment by dompl** [comment]
I have the same issue here. Any ideas please?

**Comment by pupunzi** [comment]
Hi,
I need an URL of the page where this issue is happening. 
On the demo page (http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html) methods are working fine.

**Comment by dompl** [comment]
HI,

You're, right. it is working. But I think this should be changed in the documentation where it says $.fn.YTPToggleVolume(). This function does not work, whereas toggleVolume() ( from demo site ) does.

Thanks!

**Comment by pupunzi** [comment]
just fixed the YTPToggleVolume method. Now both toggleVolume and YTPToggleVolume works.
