### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by stephanedemotte** [pupunzi/jquery.mb.YTPlayer#149]
Hi,

Thanks for this great plugin,

Can we show the video more faster ?
We i use it, the video appear after 5/6 seconde, same thing in the demo.

With this plugin : http://rochestb.github.io/jQuery.YoutubeBackground/
The video appear after 1 seconde...

Is it possible ?

Thanks !

**Comment by pierreleroyduclos** [comment]
Hi, 
I have exactly the same problem. Did you find a solution stephane ? Thanks in advance for your reply.
Happy new year!
Pierre

**Comment by stephanedemotte** [comment]
nope i juste switch to http://rochestb.github.io/jQuery.YoutubeBackground/

;)

**Comment by pierreleroyduclos** [comment]
Ok, thank you very much for your quick reply, i appreciate. The plug-in is part of a premium wordpress theme that I bought (rhythm on Themeforest). When I asked the creator of the theme how to speed up the start of the video, he said he could do nothing and that he just used the plug in ... (meaning, good luck to you ...). I'll try to do it myself but I'm not a pro. Do you think it is achievable without much knowledge?

**Comment by pupunzi** [comment]
With the latest release the video takes half the time then before to start

**Comment by bertalanimre** [comment]
End of 2019, the video still loads very-very slowly. About 33% of a page load time is taken by the video. :(
