### ISSUE TITLE
Reinitializing the player after $.YTPPlayerDestroy()

### ISSUE THREAD

**Issue by paha77** [pupunzi/jquery.mb.YTPlayer#151]
Hi,

When I do a $.YTPPlayerDestroy() call to destroy the player and then want to start it again with $.mb_YTPlayer() the wrapper div is initialised but the video is not loaded, the elements are missing.

Is there a way to do destroy a player and then start it again?

Thank you!

**Comment by gazpachu** [comment]
Agree, I'm experiencing the same issue. @paha77 Were you able to fix it?

**Comment by paha77** [comment]
Not yet.  :(

**Comment by pupunzi** [comment]
Sorry but at the time if you destroy the player it can't be reinitialized without loading the page.
