### ISSUE TITLE
Mobile Shows ytp-upnext instead of Disappearing like Desktop Version

### ISSUE THREAD

**Issue by emburklow** [pupunzi/jquery.mb.YTPlayer#152]
The desktop version works perfectly. The video loads, plays, and then disappears with the background I added using css.

However, when I view it on mobile, instead of the background I want it to choose, it uses the ytp-upnext class style. I have tried to overwrite this using both css and jquery, but neither has worked. 

I don't know if it has to do with the video not playing automatically like it's desktop counterpart or not, but I would like for the background to be what I've chosen instead of youtube.

HTML:
&lt;div data-property="{videoURL:'kdYTYq52_R0',containment:'self', showControls:false, autoPlay:true, loop:false, vol:50, mute:true, startAt:10, stopAt:28, opacity:1, addRaster:false, quality:'hd1080'}" class="player"&gt;
&lt;div class="Play"&gt;&lt;/div&gt;
&lt;div class="dnn_layout pt-60 pb-60 home-video"&gt;
&lt;/div&gt;
&lt;/div&gt;

CSS:
.mbYTP_wrapper {  bottom:0!important;z-index: 1!important;  background-image: url(/Portals/0/Images/BGs/blk-bg-03.jpg) no-repeat center!important }

**Comment by pupunzi** [comment]
This plugin doen's work on mobile devices. You should provide a fallback solution.
Bye,
Matteo
