### ISSUE TITLE
Embedding this video is restricted by Youtube.

### ISSUE THREAD

**Issue by pedromsduarte** [pupunzi/jquery.mb.YTPlayer#153]
I'm having this issue when the website is in production server, locally all works fine.

Any help?

Thanks.

**Comment by citmusa** [comment]
Be shure you are using urls like ```https://www.youtube.com/watch?v=l_tHTmd5pgk``` instead of ```https://www.youtube.com/embed/l_tHTmd5pgk```

**Comment by pupunzi** [comment]
Check the permission you set on Youtube for that video. It should be embeddable.
