### ISSUE TITLE
YTPChangeMovie videos constantly buffer

### ISSUE THREAD

**Issue by allisongrey** [pupunzi/jquery.mb.YTPlayer#155]
I am trying to have a list of links (play buttons) change the video in one main global div using YTPChangeMovie. There are four total right now. It works and loads the new movie into the .player div but the videos stop and start constantly trying to buffer.

I have other videos on the page contained in their own elements that play fine without any buffering. 

It is definitely not an internet speed issue. Its also not the videos themselves, the same videos in other elements on the page play smooth with no buffering. 

Any ideas? 

I need a list of 4 play buttons to dynamically load a video in a larger div somewhere else on the page.

**Comment by pupunzi** [comment]
Hi,
Does this happens also with the /examples/demo_videoList.html you can find in the download package?

**Comment by allisongrey** [comment]
Hey thank you for the reply, it seems to be an issue with the video source files in safari + youtube, we're still not sure, but 99.9% sure its not the plugin! 

We are having issues with the videos not starting exactly at 0:00 but about 0:01 which cuts off some words at the start of the video - this is happening cross browser - and we have startAt:0 for all the players. When the videos load they play for a second before pausing (autoPlay is set to false). Is there a way to ensure videos start at right at true 0?

**Comment by pupunzi** [comment]
The component start at 1 even if you set 0 to prevent the display of the youtube loader. I suggest to add some black space at the beginning of your video.

**Comment by rahulsjain** [comment]
I also have the same issue and I tried YTPSeekTo(0), It is working only for the first time, when the video is looped it again cuts some secs and play
