### ISSUE TITLE
IE Issues

### ISSUE THREAD

**Issue by mjperales** [pupunzi/jquery.mb.YTPlayer#156]
Video will not play in IE or did I miss something? 
Test Link: http://tcuaot.wpengine.com/

**Comment by pupunzi** [comment]
Tested your site using windows 7 IE 11/10/9 and it works fine... Which OS are you testing with?

**Comment by mjperales** [comment]
You are absolutely right, it does work in IE. I apologize in advance for my laziness. I was using a remote desktop connection to test in IE.

**Comment by GlauberF** [comment]
how do I instead of showing only a background image when accessed via smartphone to a small slide (image sequence)
