### ISSUE TITLE
YTPStart is only triggered on autoplay

### ISSUE THREAD

**Issue by cdarken** [pupunzi/jquery.mb.YTPlayer#160]
Is there a reason for this decision?

**Comment by pupunzi** [comment]
There's the YTPPlay event that triggers when you play a video or the YTPReady that trigger once the video is ready to play. If the player is initialized with the autoplay set to false the YTPStart event is not triggered as the video is not starting playing and knowing if you play the video at its beginning is not so simple to retrieve. Just use the YTPReady if you need the corresponding of YTPStart.

**Comment by atif-kht** [comment]
I have initialized the player with autoplay set to false and now niether of YTPStart or YTPPlay is working when I play video the first time. But it does work the 2nd time when I play/pause video. Is there a work around for this?

`jQuery( ".flexslider .player" ).on("YTPPlay",function(e){
        console.log('Played');
        slider.flexslider("stop");
        canSlide = false;
    });`
