### ISSUE TITLE
Having onYouTubeIframeAPIReady function previously declared in site code 

### ISSUE THREAD

**Issue by sturple** [pupunzi/jquery.mb.YTPlayer#163]
HI @pupunzi 
Once you declare this callback function onYouTubeIframeAPIReady either your plugin will not work or the code you created will not work.
For example
/assets/js/script.js
```javascript
function onYouTubeIframeAPIReady() {
	youtube_hp = new YT.Player('youtube_hp', {
		height: '390',
		width: '640',
		videoId: 'BLecHLDtEwA',
		events: {
		  'onReady': function() {
			videoready = true;
			
		},
		  'onStateChange': function() {}
		}
	});
}
```

**Comment by pupunzi** [comment]
Hi,
Where did you find /assets/js/script.js?
I don't understand what you are referring to...
the onYouTubeIframeAPIReady() is called by the jquery.mb.YTPlayer.js file; if you overwrite that function the YTPlayer plugin is never initialized...

look at the source code line: 23
Bye,
Matteo

**Comment by sturple** [comment]
So the /assets/js/script.js is custom script for the website, which I am using the youtube api, however since you already created the onYouTubeIframeAPIReady callback function, it is impossible for me to create this function as well.

**Comment by pupunzi** [comment]
You can just attach the function to the YTAPIReady event truggered when Youtube calls onYouTubeIframeAPIReady...

```
$(document).on("YTAPIReady", function(){
    //... your function goes here
})
```

Bye,
Matteo

**Comment by sturple** [comment]
ah, yes i see that now, thanks for the help.
