### ISSUE TITLE
Update the wiki

### ISSUE THREAD

**Issue by Pageau4** [pupunzi/jquery.mb.YTPlayer#164]
Certain function names have changed but the wiki didn't update from this change.

For example, I found the function YTPUnmute() in the wiki, but the real name of the function in the file is unmuteYTP()

**Comment by pupunzi** [comment]
Hi,
no, the real function actually is :  jQuery.fn.YTPUnmute;
unmuteYTP() has been deprecated.

`	jQuery.fn.YTPUnmute = jQuery.mbYTPlayer.unmute;
`

Bye,
Matteo
