### ISSUE TITLE
Multiple bg videos

### ISSUE THREAD

**Issue by DmitryAuine** [pupunzi/jquery.mb.YTPlayer#166]
Hello! This is really cool player, and bg video works as expected. But i have a problem with multiple videos setted as bg.
The firs one is not resized after you resize the window. Sems like the event listers shared beetwen two elements and they works only on the last one 

For example
```
<style>
    div{
      height: 600px;
      width: 100%;
    }
  </style>
</head>
<body>
  <div data-property="{videoURL:'http://youtu.be/BsekcY04xvQ'}"></div>
  <div data-property="{videoURL:'http://youtu.be/BsekcY04xvQ'}"></div>
  
  <script>
    $(function(){
      $('div').YTPlayer();
    })
  </script>
</body>
```

**Comment by pupunzi** [comment]
Fixed with v. 2.1.14

**Comment by DmitryAuine** [comment]
Thx :)
