### ISSUE TITLE
YTPReady not firing on mobile devices

### ISSUE THREAD

**Issue by webmatrixxxl** [pupunzi/jquery.mb.YTPlayer#167]
Hello! Great plugin. 

On mobile device YTPReady event is not firing when video is ready. Left top corner constant Loading.

Tested on OS X El Capitan Chrome,  android 5.1, Safari iOS 9

This is my scenario:

```
<div class="player bgndVideo" data-property="{videoURL:'http://youtu.be/Gd9OhYroLN0',containment:'self',autoPlay:false, mute:false, startAt:0, opacity:1, showControls:false, showYTLogo: false, addRaster: false, loop: false}">
</div> 
```

**Comment by pupunzi** [comment]
Hi,
This plugin can't work on mobile devices:
https://github.com/pupunzi/jquery.mb.YTPlayer/wiki#important-notice

Bye,
Matteo

**Comment by webmatrixxxl** [comment]
Yea.. I know.. but I can use YTPGetPlayer() on mobile devices and listen for 'onStateChange' trough plugin... but YTPReady is not fired.

**Comment by 8cells** [comment]
Any workaround?

**Comment by webmatrixxxl** [comment]
Yes.. they are two ways:

1. Use native youtube iframe.

2. You can execute code in window.onYouTubeIframeAPIReady = function() {} while using jquery.mb.YTPlayer
