### ISSUE TITLE
getDuration

### ISSUE THREAD

**Issue by Bluxart** [pupunzi/jquery.mb.YTPlayer#169]
Hi, how can access to this property for know the duration of the video? Exist some events?

**Comment by Bluxart** [comment]
I resolved.

**Comment by ExAnimoSeneghe** [comment]
Is it possible to have the solution of the problem? Thank you!

**Comment by pupunzi** [comment]
Hi,
The YTPLayer expose several methods to retrieve information about the video.
You can consult the documentation here: https://github.com/pupunzi/jquery.mb.YTPlayer/wiki#external-methods

To get the actual video time and its duration:

``` javascript
myPlayer.YTPGetTime();
myPlayer.YTPGetTotalTime();
```
