### ISSUE TITLE
Not working when entire site is loading in HTTPS

### ISSUE THREAD

**Issue by pierrebalian** [pupunzi/jquery.mb.YTPlayer#170]
Hello, I recently configured our server to run all sites strictly in https, and when the site loads in ssl mode you plugin doesnt load the video background.

Any ideas on what I can do to get it working?

**Comment by pupunzi** [comment]
The plugin should work fine under SSL as it calls the Youtube API using HTTPS...
Which error are you getting from the console?

Bye,
Matteo

**Comment by pierrebalian** [comment]
Uncaught TypeError: Cannot read property '1' of null on line 93
That line shows:
movieURL = url.match(/[\\?&]v=([^&#]*)/)[1];

Site is hookerandcompany.com and video is on the home page.

Pierre

On Mon, Mar 14, 2016 at 9:46 AM, mb.jquery.components <
notifications@github.com> wrote:

> The plugin should work fine under SSL as it calls the Youtube API using
> HTTPS...
> Which error are you getting from the console?
>
> Bye,
> Matteo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pupunzi/jquery.mb.YTPlayer/issues/170#issuecomment-196344923>
> .
>



-- 


[image: Hooker & Company Advertising] <http://www.hookerandcompany.com/>
*Pierre Balian <pierre@hookerandcompany.com>*
Web Developer / Designer / SEO Specialist
[image: Twitter] <https://twitter.com/HOOKERandCO>[image: Facebook]
<https://www.facebook.com/hookerandcompany>[image: LinkedIn]
<http://www.linkedin.com/company/hooker-&-company-advertising>
hookerandcompany.com <http://www.hookerandcompany.com>
165 Western Ave N <http://goo.gl/maps/lSGf8> | Suite #12
<http://goo.gl/maps/lSGf8> | St. Paul, MN 55102 <http://goo.gl/maps/lSGf8>
|
tel (651) 659-9648 | fax (651) 659-9735 |
*Confidentiality Note: *This email may contain confidential and/or private
information. If you received this email in error please delete and notify
sender

**Comment by pierrebalian** [comment]
Nevermind, my version of your script was from 2014.  Once I updated it
everything is working as it should.

On Mon, Mar 14, 2016 at 12:12 PM, Pierre Balian <pierre@hookerandcompany.com
> wrote:

> Uncaught TypeError: Cannot read property '1' of null on line 93
> That line shows:
> movieURL = url.match(/[\\?&]v=([^&#]*)/)[1];
>
> Site is hookerandcompany.com and video is on the home page.
>
> Pierre
>
> On Mon, Mar 14, 2016 at 9:46 AM, mb.jquery.components <
> notifications@github.com> wrote:
>
>> The plugin should work fine under SSL as it calls the Youtube API using
>> HTTPS...
>> Which error are you getting from the console?
>>
>> Bye,
>> Matteo
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pupunzi/jquery.mb.YTPlayer/issues/170#issuecomment-196344923>
>> .
>>
>
>
>
> --
>
>
> [image: Hooker & Company Advertising] <http://www.hookerandcompany.com/>
> *Pierre Balian <pierre@hookerandcompany.com>*
> Web Developer / Designer / SEO Specialist
> [image: Twitter] <https://twitter.com/HOOKERandCO>[image: Facebook]
> <https://www.facebook.com/hookerandcompany>[image: LinkedIn]
> <http://www.linkedin.com/company/hooker-&-company-advertising>
> hookerandcompany.com <http://www.hookerandcompany.com>
> 165 Western Ave N <http://goo.gl/maps/lSGf8> | Suite #12
> <http://goo.gl/maps/lSGf8> | St. Paul, MN 55102 <http://goo.gl/maps/lSGf8>
> |
> tel (651) 659-9648 | fax (651) 659-9735 |
> *Confidentiality Note: *This email may contain confidential and/or
> private information. If you received this email in error please delete and
> notify sender
>



-- 


[image: Hooker & Company Advertising] <http://www.hookerandcompany.com/>
*Pierre Balian <pierre@hookerandcompany.com>*
Web Developer / Designer / SEO Specialist
[image: Twitter] <https://twitter.com/HOOKERandCO>[image: Facebook]
<https://www.facebook.com/hookerandcompany>[image: LinkedIn]
<http://www.linkedin.com/company/hooker-&-company-advertising>
hookerandcompany.com <http://www.hookerandcompany.com>
165 Western Ave N <http://goo.gl/maps/lSGf8> | Suite #12
<http://goo.gl/maps/lSGf8> | St. Paul, MN 55102 <http://goo.gl/maps/lSGf8>
|
tel (651) 659-9648 | fax (651) 659-9735 |
*Confidentiality Note: *This email may contain confidential and/or private
information. If you received this email in error please delete and notify
sender

**Comment by pupunzi** [comment]
;-)
