### ISSUE TITLE
YTAPIReady does not get called on mobile

### ISSUE THREAD

**Issue by sturple** [pupunzi/jquery.mb.YTPlayer#178]
Hi  @pupunzi

Thanks for the plugin, 
I have a few questions and a possible feature/bug fix:
On mobile it seems like the YTAPIReady does not get called.  I require this for another application.
 
* I believe that if your plugin detects it is mobile and can't play on mobile that it kills itself, and that it shows the basic iframe.
* I also believe that this **kills** the YTAPIReady trigger.
* I still require this event to be triggered and the google iframe script to be loaded because i need to use this onready to trigger another iframe api command not related to your plugin.

**Comment by sturple** [comment]
Hi @pupunzi just wondering if you plan to update you code to fix this issue.

Regards,
Shawn

**Comment by pupunzi** [comment]
With the 3.0.5 release the YTAPIReady is triggered also on mobile
