### ISSUE TITLE
Youtube video loop cuts out early

### ISSUE THREAD

**Issue by SpaceWarpStudio** [pupunzi/jquery.mb.YTPlayer#179]
Hey!

My video header seems to be cutting out a few seconds early, skipping my fade out. I'm using the Livemesh SiteOrigin Hero Header. I mentioned this to them and they suggested telling you, apparently they are invoking YTPlayer using this...

`$('.lsow-section-bg-youtube').mb_YTPlayer({
                        startAt: 0,
                        showYTLogo: false,
                        showControls: false,
                        autoPlay: true,
                        mute: true,
                        containment: 'self'});` 

As mentioned [here](https://wordpress.org/support/topic/youtube-video-cuts-out-at-1-minute).

The issue can be seen on my website [here](http://screenspacevr.com/)

And the original youtube video as it should be played [here](https://www.youtube.com/watch?v=MUHe-7PtiTI)

Many thanks!

**Comment by pupunzi** [comment]
Hi,
the YTPlayer stops 1 sec. before the real end of the video to prevent the display of the big red play button. The only solution for you is to add one sec. more of black at the end.
