### ISSUE TITLE
Can't install with bower on windows

### ISSUE THREAD

**Issue by romapad** [pupunzi/jquery.mb.YTPlayer#180]
Hi! Your repository contains /node_modules/ folder with a lot of subfolders with path length more than 255 symbols. So it is throwing error while installing trough bower on windows system: "unable to create file node_modules/grunt-contrib-cssmin/bla-bla-bla (filename is too long)

**Comment by pupunzi** [comment]
The bower.json exclude that folder...
I don't know why it is included in the install.

**Comment by romapad** [comment]
Here is the whole list of errors:

`bower ECMDERR       Failed to execute "git clone https://github.com/pupunzi/jquery.mb.YTPlayer.git -b 3.0.1 --progress . --depth 1", exit code of #128 Cloning into '.'... remote: Counting objects: 2263, done.  Resolving deltas: 100% (361/361), done. remote: Total 2263 (delta 361), reused 2233 (delta 352), pack-reused 0         Checking connectivity... done. Note: checking out 'abd3f70df3e557de57f7f3af22eaf5f973183d83'.  You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout.  If you want to create a new branch to retain commits you create, you may do so (now or later) by using -b with the checkout command again. Example:    git checkout -b <new-branch-name>  Checking out error: unable to create file node_modules/grunt-contrib-cssmin/node_modules/maxmin/node_modules/gzip-size/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_passthrough.js (Filename too long) error: unable to create file node_modules/grunt-contrib-cssmin/node_modules/maxmin/node_modules/gzip-size/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_transform.js (Filename too long) fatal: cannot create directory at 'node_modules/grunt-contrib-cssmin/node_modules/maxmin/node_modules/gzip-size/node_modules/concat-stream/node_modules/readable-stream/node_modules': Filename too long warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'

Additional error details:
Cloning into '.'...
remote: Counting objects: 2263, done.
remote: Compressing objects: 100% (1712/1712), done.
Receiving objects: 100% (2263/2263), 5.38 MiB | 585.00 KiB/s, done.
Resolving deltas: 100% (361/361), done.
remote: Total 2263 (delta 361), reused 2233 (delta 352), pack-reused 0
Checking connectivity... done.
Note: checking out 'abd3f70df3e557de57f7f3af22eaf5f973183d83'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

error: unable to create file node_modules/grunt-contrib-cssmin/node_modules/maxmin/node_modules/gzip-size/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_passthrough.js (Filename too long)
error: unable to create file node_modules/grunt-contrib-cssmin/node_modules/maxmin/node_modules/gzip-size/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_transform.js (Filename too long)
fatal: cannot create directory at 'node_modules/grunt-contrib-cssmin/node_modules/maxmin/node_modules/gzip-size/node_modules/concat-stream/node_modules/readable-stream/node_modules': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'`

Can't get why it's like that

**Comment by romapad** [comment]
Thanks! Now it's working
