### ISSUE TITLE
Force to wait until 100% buffer

### ISSUE THREAD

**Issue by Schnitzer** [pupunzi/jquery.mb.YTPlayer#181]
Hello Matteo,
thank you for the great component!

For low bandwidth clients there is allways a to small buffer on youtube. If you want to force wait until the video is complete loaded, how would you do that?
I thougt your YTPBuffering event is a good starting point but when it fires, it´s to late :)

kind regards
Danny

**Comment by pupunzi** [comment]
Hi Danny,

The Youtube API check itself the bandwidth and serve the video with the appropriate resolution based on that. 
The YTPBuffering event is fired each time the player start buffering the video, but you can't force the player to buffer all the video... and starting the video when it's totally loaded is not a good idea...

**Comment by Schnitzer** [comment]
Ok, thank you. I guess i get this behaviour if i set `quality: ‘default’` right?

**Comment by abhinavek** [comment]
how to disable aoutomatic buffer ??

**Comment by pupunzi** [comment]
@abhinavek What do you mean by disabling buffering? 
The player needs to buffer video, otherwise it can't work...
