### ISSUE TITLE
Restart the video from the begining

### ISSUE THREAD

**Issue by rossmc** [pupunzi/jquery.mb.YTPlayer#183]
Thanks so much for the plugin.

Is it possible to restart the video from the begining?  I have button and when it's clicked I would like it to start playing the video from the begining.

I've looked through the documentation and have played around with
`jQuery('#[playerID]').YTPPlay()`
`jQuery('#ytvideo-bg').YTPPlay('{startAt:0}');`

But this just plays the video from where it was stopped.  It does not play it from the begining

**Comment by pupunzi** [comment]
Hi,
you should use jQuery.fn.YTPSeekTo method instead:

`jQuery('#[playerID]').YTPSeekTo(0)`

That way the video goes to the beginning and if it was playing it will play otherwise it will stop at the beginning.
