### ISSUE TITLE
Fullscreen Help

### ISSUE THREAD

**Issue by dorelljames** [pupunzi/jquery.mb.YTPlayer#185]
Any ideas how can I achieve proper fullscreen on the site I'm creating? See below: http://kayu.dorelljames.com. 

The restaurant's slogan gets cut off on the right side. Wanted it really fullscreen and centered so the video doesn't get cut off. Tried different combinations and all sorts of options in the docs but it doesn't just get the job done, sadly enough. Or possibly I'm missing something here.

![screen shot 2016-06-08 at 10 07 50 pm](https://cloud.githubusercontent.com/assets/977413/15897087/976dc7bc-2dc5-11e6-8fa9-4c4e77229080.png)
[ taken from kayu.dorelljames.com ]

Here's the actual video on Youtube. https://youtu.be/XwWZI7SkSDY?t=21s. If you can see, the "Passionately Inspiring" is not cut off. See sample below:

![screen shot 2016-06-08 at 10 07 37 pm](https://cloud.githubusercontent.com/assets/977413/15897100/a6788a8a-2dc5-11e6-8054-04d51d911c53.png)
[ taken from youtube.com video as per above link ]

**Comment by pupunzi** [comment]
Hi,
The default behaviour is to adapt the video to fit the screen size the same way [the "cover" CSS properties does](http://www.w3schools.com/cssref/playit.asp?filename=playcss_background-size&preval=cover). That means the video gets the biggest screen size (width or height) and is centered on the screen cutting what exceeds the difference between the screen aspect-ratio and the video aspect-ratio. 

If you don't want this behaviour you can set the "optimizeDisplay" option to false; that makes the video always visible introducing black strip top/bottom or left/right.

Hope this helps,
Matteo

**Comment by tarson** [comment]
The thing about MB.YT Player is automatically scales the video to make sure it fits in the element. The best course of action is maybe playing with the video ratio.



Sent via the Samsung Galaxy Note5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by laravelcebu** [comment]
Thank you @pupunzi and @tarson :+1:

**Comment by dorelljames** [comment]
Thanks @pupunzi and @tarson :+1:
