### ISSUE TITLE
control bar not showing on background video

### ISSUE THREAD

**Issue by anxhelamustafa** [pupunzi/jquery.mb.YTPlayer#187]
Hello, in this website I am working with:
http://gardesana.it/index.php/storia
I have a problem with the controls. On full screen, the control bar are shown, but in background video, or in normal screen, I can not make them appear(except for the progress bar). I would like to know if there is any method to make the controls stick at the bottom of the element from the moment the video starts playing.
Thanks in advance

**Comment by pupunzi** [comment]
Hi,
Actually the YTPlayer.js is at version 3.0.3 while you are using version 2.6. 
Anyway that is not the real cause of your issue. I presume that the author of your Joomla theme (shaper_helix3) did change part of the javascript code to modify the behavior of the component and they intentionally removed the default control-bar. you should ask them for a solution.

Bye,
Matteo
