### ISSUE TITLE
How to make on/off mask?

### ISSUE THREAD

**Issue by xGoldenS** [pupunzi/jquery.mb.YTPlayer#190]
I use maskadd and maskremove but i cant get current mask for On again.(I use multi mask)
Please help me.

**Comment by pupunzi** [comment]
Hi, at the time you the YTPAddMask method what the path to the mask file. In the next release if no path to the mask is specified it will get the last mask applied.

Bye,
Matteo

**Comment by xGoldenS** [comment]
Good job man.

**Comment by pupunzi** [comment]
With the new 3.0.6 release you've a YTPToggleMask method for that.
