### ISSUE TITLE
loop false not working 

### ISSUE THREAD

**Issue by alessiovaralta** [pupunzi/jquery.mb.YTPlayer#193]
This is my code 

var videos = [
            {videoURL:"vnxOSVD7PVE",containment:'#video-expact-presentation',autoPlay:true, mute:false, startAt:0,opacity:1, loop:false, ratio:"4/3", addRaster:true},
      ];
      jQuery("#video-expact-presentation").YTPlaylist(videos, true);

but the video restart in an infinite loop

**Comment by pupunzi** [comment]
Hi,
If you use the YTPlaylist its behavior is to go to the next video once the playing one is ended and once the last video ended it goes to the first. If you have only one video it will loop.

If you want to play only one video you should not use the YTPlaylist method but the YTPlayer one:

```
var video = {videoURL:"vnxOSVD7PVE",containment:'#video-expact-presentation',autoPlay:true, mute:false, startAt:0,opacity:1, loop:false, ratio:"4/3", addRaster:true}

jQuery("#video-expact-presentation").YTPlayer(video);

```

Bye,
Matteo

P.S.: I'll add a boolean to control this behavior on the next release
