### ISSUE TITLE
Is there a way to choose a specific video to play among a list ?

### ISSUE THREAD

**Issue by Julie95** [pupunzi/jquery.mb.YTPlayer#200]
Is there a way to choose a specific video to play when we are using a list of video ? 

Thank you !

**Comment by pupunzi** [comment]
With the latest 3.0.8 release you have a new method jQuery.fn.YTPPlayIndex that accept the index of the video you want to play. [see the doc](https://github.com/pupunzi/jquery.mb.YTPlayer/wiki#external-methods)

**Comment by Julie95** [comment]
Great ! As soon as I am missing a feature, it's there ! 
Thank you so mush !
