### ISSUE TITLE
Function $.fn.YTPPlayIndex(idx) doesn't work on mobile

### ISSUE THREAD

**Issue by Julie95** [pupunzi/jquery.mb.YTPlayer#201]
Hi, 

I have been trying to use the function $.fn.YTPPlayIndex(idx) on a mobile (android), and it doesn't seem to have any effect. Is that an expected behavior ? 

Thank you !

**Comment by pupunzi** [comment]
It doesn't work on mobile devices due to the vendors media policy. Youtube videos on mobile devices can't be controlled via javascript and can't be started without a direct user's touch event. On most devices videos are played within the native player and not inside the browser.
