### ISSUE TITLE
How to reverse the Volume icon behavior just like youtube?

### ISSUE THREAD

**Issue by atif-kht** [pupunzi/jquery.mb.YTPlayer#202]
Hi currently when the volume is mute, icon shows speaker without cross on it but if there is volume then it shows speaker icon with cross on it.

I know why you have set it as such and does make sense that when they volume is open, then in order to mute it, it should be speaker with cross on it. But there is a requirement to this reverse behavior .i.e. when the volume is mute, it should show speaker with cross on it and when the volume is played, it should show speaker without cross.

I tried to drill down the code in order to see for .clases or id;s to reverse the styling but was not able to find it.

Can you please suggest how can I do this? Please do let me know if my question doesn't make sense.

Thanks.

**Comment by atif-kht** [comment]
@pupunzi Can you please look into it.

**Comment by pupunzi** [comment]
Hi,
the volume icon shows the state you can obtain by clicking on it. You can inverse them changing the map of the controls before you initialize the background video as follow:

```
jQuery.mbYTPlayer.controls.mute="A";
jQuery.mbYTPlayer.controls.unmute="M";

```

**Comment by atif-kht** [comment]
Thank you very much @pupunzi ! This really resolved my problem.
