### ISSUE TITLE
e[i].trim is not a function

### ISSUE THREAD

**Issue by ciprianimike** [pupunzi/jquery.mb.YTPlayer#204]
Video dosen't work, console shows this JS error:
jquery.mb.YTPlayer.min.js?ver=2.0.9:8 Uncaught TypeError: e[i].trim is not a function

You can check this live at: http://www.serafinoconsoli.com/

**Comment by pupunzi** [comment]
You're probably using some other javascript library on your site that is overwriting the default trim() function... 
Anyway I published a new Wordpress version 2.0.10 using another method to trim the string. Try updating to the new version and let me know.

**Comment by ciprianimike** [comment]
the actual error is now "Uncaught TypeError: e[i].replace is not a function" as you can see in at the same URL. The theme used is Salient Version: 7.0.7 i am trying to detect the conflict.
