### ISSUE TITLE
On Ipad video assigned to container (not background), not showing up

### ISSUE THREAD

**Issue by atif-kht** [pupunzi/jquery.mb.YTPlayer#205]
Hi @pupunzi !

Thanks for the help with my early problem few days back, but now I have one more issue. I know this player does not work on mobile but it should work on IPAD, right? I have tested it on android tablets and is working fine but the only issue is for IPAD + Safari. 

Also in your notice it is mentioned that if video is not assigned to background, it will fall back to youtube video or something?

Can it be possible to show the video no matter what, on mobiles as well, without player settings? May be fall back to youtube video player on mobiles only?

Do let me know if you need link to my site, I will email it to you as it is not public yet.

Thanks.

**Comment by midiser** [comment]
hi  @pupunzi! thanks a lot for your great work!

I have the same problem as above. the video asigned to a container is not showing up on mobile devices like IPAD.

any suggestions please?

**Comment by pupunzi** [comment]
This component doesn't work on mobile devices as the Youtube API is limited in functionalities and mobile vendors doesn't allow to play videos as it happens on desktop browsers.
