### ISSUE TITLE
Resuming video from last session

### ISSUE THREAD

**Issue by socheon** [pupunzi/jquery.mb.YTPlayer#207]
I have a long youtube video used as background on my home page. When a user temporarily navigate away from the home page and then return, I don't want the video to be restarted, rather resumed from the last session possibly in a cookie. Can this be done?

**Comment by pupunzi** [comment]
Hi,
With some coding you can have this behaviour using cookies (or local storage) and the player events to check if there's a cookie for that player and seek to that value on the event YTPSTART.
