### ISSUE TITLE
Heroku Issue

### ISSUE THREAD

**Issue by keithmacinnis** [pupunzi/jquery.mb.YTPlayer#209]
I'm having trouble getting the player to work on Heroku ... Any tips? 
https://keithmacinnis.herokuapp.com/

I get this error message in my web browsers:
Uncaught TypeError: t(...).scrollspy is not a function

**Comment by pupunzi** [comment]
Hi,
**scrollspy** is not part of the YTPlayer component. If that is firing an error it is probably blocking the player but that doesn't depend on my script.

You can try removing the scrollspy script (that is a Bootstrap plugin: http://www.w3schools.com/bootstrap/bootstrap_ref_js_scrollspy.asp) and check if the player works.

Bye,
Matteo

**Comment by keithmacinnis** [comment]
Hey thanks!

Took me bit to track down the error but it turned out that adding 
config.assets.debug = true to my production.rb file fixed the issue.

**Comment by pupunzi** [comment]
Great :-)
