### ISSUE TITLE
jquery error

### ISSUE THREAD

**Issue by korwin1983** [pupunzi/jquery.mb.YTPlayer#213]
Hi, i have this error:
jquery.mb.YTPlayer.src.js:175 Uncaught TypeError: Cannot read property 'msie' of undefined

thanks for solving problem.

**Comment by pupunzi** [comment]
You should not use the jquery.mb.YTPlayer.src.js file but the one in the "dist" folder. That one is for developing scope and doesn't contain all the needed scripts.

**Comment by korwin1983** [comment]
it works! 
thanks
