### ISSUE TITLE
Youtube logo appears for first few seconds

### ISSUE THREAD

**Issue by VinnyR** [pupunzi/jquery.mb.YTPlayer#214]
The youtube logo appears in the bottom right corner at the start of the video, and then disappears about 2-3 seconds later. This is despite the fact that I have set showYTLogo:false.

Problem occurs on both Firefox (49.0.2) and Chrome (53.0.2785.143 m) on Windows 7.

I have noticed that the problem only occurs from version 3.0.3 onwards. Therefore, I am sticking to version 3.0.2 for now. This issue does not occur in version 3.0.2 and below.

**Comment by pupunzi** [comment]
Hi,
I'm not able to reproduce your issue.
Can you check if that happens on this page http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_ext_methods.html ?

thanks,
Matteo

**Comment by VinnyR** [comment]
Hello,

Yes the issue does also occur on the page [](http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_ext_methods.html).

I have taken a video of the issue, you can view it here: [](https://drive.google.com/file/d/0B-CeZEcA4wIaaS1FTmZXSllFU1U/view)

I have noticed that the issue also occurs whenever the web browser becomes the inactive window. So if I make notepad the active window, and then I switch to chrome, the youtube logo will briefly show again. I have taken a video of this issue too, you can see it here: [](https://drive.google.com/open?id=0B-CeZEcA4wIaR0pPUG53TDF3bE0)

Please let me know if I can assist further.

Kind regards,

Vin

**Comment by bjorndomino** [comment]
Hi, I am also having this issue – was this ever addressed? I am using v3.0.10 and the YT logo appears in the bottom right corner when optimizeDisplay is set to false. Happens in Chrome and Firefox, OS X Yosemite.

Thank you!

**Comment by pupunzi** [comment]
Hi,
**The bottom right Youtube logo can't be removed with the API**. So if you set the **optimizeDisplay option to false** the player will show all all video as if it is in the default Youtube player except for the toolbar. The  bottom right logo is hidden only if you turn on the optimizeDisplay option as it is placed outside the viewable area.

I'm sorry but I can't prevent the display of the logo if the option is turned off.

All the best,
Matteo

**Comment by bjorndomino** [comment]
Great, thank you for clarifying.

Just a quick follow up question – is it then possible in some other way to display the video uncropped using the plugin? Basically just looking for the video to display in correct ratio uncropped but without the YT logo.

Thanks again, love this plugin and your support here means a lot!
Bjorn

**Comment by pupunzi** [comment]
Turning off the optimizeDisplay option let you display the video uncropped with the correct aspect ratio but that way also the lower part of the video where the Youtube logo appears is displayed. As I told you, the Youtube API doesn't have any method to hide their logo so the only way to hide it is to crop the lower part of the video.

**Comment by VinnyR** [comment]
I am now using the latest version (09-12-2016) with optimizeDisplay:true, and I don't see the youtube logo.

**Comment by bjorndomino** [comment]
@VinnyR that would be due to the cropping enabled with optimizeDisplay, according to pupunzi's latest comment above.

**Comment by VinnyR** [comment]
@bjorndomino Thanks, I didn't realise that when I first opened the issue. 

But the example I used to demonstrate the issue was on [this link](http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_ext_methods.html) where it looks like optimizeDisplay is already set to true.

It seems to me that the plugin at [http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_ext_methods.html](http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_ext_methods.html) has been updated since I opened the issue.

(see the videos I posted above)
