### ISSUE TITLE
Vídeo iframe optimal Height and Width

### ISSUE THREAD

**Issue by asier-laukoa** [pupunzi/jquery.mb.YTPlayer#216]
Hi,

is there a way to respect the video screening at fullscreen but not losing any video surface? The thing is that I have a video with text inside and some of this text is not showing because the dimmensions of the iframe.

Thanks!

**Comment by pupunzi** [comment]
Hi,
Disabling the "optimizeDisplay" option (set it to false) make the video always feet the screen. Of course there'll be empty areas on the top/bottom or left/right to fill the difference between the screen and the video aspect-ratio.

Bye,
Matteo

**Comment by asier-laukoa** [comment]
I will try.

Thanks a lot!
