### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by robertrhu** [pupunzi/jquery.mb.YTPlayer#218]
Getting this error in the console. Not getting the video loaded at all. Wondering if it is a Jquery version issue? Attached a screenshot of the console...

Thanks in advance!

![screen shot 2016-11-22 at 12 11 57 pm](https://cloud.githubusercontent.com/assets/11826368/20545794/4a5eb4f4-b0ce-11e6-8ec9-8bd77dce1026.png)

**Comment by pupunzi** [comment]
Do you have a public URL where I can see this behaviour?

**Comment by robertrhu** [comment]
I don't at this moment. I'm developing in my local environment. Any thoughts without seeing it live? I'm working on pushing it to a live domain. I'll keep you posted.

**Comment by robertrhu** [comment]
Here's a link to the website I'm working on. I'm using the YTPlayer in the very top section of the page. Thanks!

http://storyportal.robertrhu.net/

**Comment by pupunzi** [comment]
From what I can see you are using the wrong Youtube URL for the video.

you set: https://youtu.be/OIlh-rpFrZ0
should be: https://www.youtube.com/watch?v=OIlh-rpFrZ0

Let me know.
Bye,
Matteo

**Comment by robertrhu** [comment]
I've tried that. It clears the original error but creates new ones and the video still won't load.

**Comment by pupunzi** [comment]
From what I can see you have an error generated by the main.js file: 
Uncaught TypeError: Cannot set property 'onclick' of null
That could compromise the correct behavior of the mb.YTPlayer.

**Comment by PSzabo** [comment]
I have same problem in iOS devices or browser simulators. I cant figure out it. My grunt's project concats libraries from bower. Thats all. I don't changing anything in the library.

**Comment by pupunzi** [comment]
@PSzabo this plug-in doesn't work on devices due to restrictions applied on the use of the youtube javascript API by the mobile vendors. You can set a fallback image for them.

**Comment by kinsbrunner** [comment]
Hi @pupunzi , 
I believe that you have adjusted your script and that now allows reproducing videos on mobile devices.
Is my understanding correct?
Regards.
Alejandro.
