### ISSUE TITLE
No 'Access-Control-Allow-Origin for https://www.youtube.com/iframe_api

### ISSUE THREAD

**Issue by grekpg** [pupunzi/jquery.mb.YTPlayer#219]
i Have this error jquery.min.js:6 XMLHttpRequest cannot load https://www.youtube.com/iframe_api?v=3.0.10. No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by pupunzi** [comment]
Hi,
Do you have a public URL where I can check your issue?

**Comment by grekpg** [comment]
yes here is site https://rejsychorwacja.com

**Comment by pupunzi** [comment]
Hi,
First I suggest to download the latest release (3.0.10) and use the js file in the "dist" folder.
You've an error: Uncaught TypeError: Cannot read property 'pauseVideo' of undefined(…)
It seams you are calling the "pause" before the YTPlayer is initialized. 

Did you try including the script directly in the page?

**Comment by grekpg** [comment]
hm i dont have  Cannot read property 'pauseVideo' of undefined (in opera linux) 
But i change now jquery from  2.0.0 to 2.2.4 and error No 'Access-Control-Allow-Origin' header is present on the requested resource. was gone. So for now its ok. Thanks for you investigate. You have pause error ? in with browser ?

**Comment by pupunzi** [comment]
I've the Uncaught TypeError: Cannot read property 'pauseVideo' of undefined(…) In Chrome...
