### ISSUE TITLE
Enable Mobile Player?

### ISSUE THREAD

**Issue by nsystem1** [pupunzi/jquery.mb.YTPlayer#220]
I know it don't work on mobile devices, but please tell me how to remove the mobile blocking? I want the full code to fire on mobile device even those i know it wont work, i needed the full event for my project.

Thank you

**Comment by pupunzi** [comment]
Hi,
you can remove the mobile check at line 356 but I can't understand why you need that.
Anyway commenting from line 356 to 385 the mobile check is removed.

Bye,
Matteo
