### ISSUE TITLE
First 2-3 seconds cut off.

### ISSUE THREAD

**Issue by kdiz7** [pupunzi/jquery.mb.YTPlayer#221]
Hi,

My player cuts the first 2-3 seconds off the beginning of all my videos. Is there someway to fix this without adding blank space to each video as this is out of my control?

Many thanks,

**Comment by pupunzi** [comment]
The first 2 seconds of the video are lost because of the first check the plug-in need to do to set up the player correctly (one seconds is for the initial fade-in and one second is for the check). There's nothing you can do either then add some free space at the beginning.

All the best,
Matteo
