### ISSUE TITLE
is there an option to stop clicking over div element with video from stop/starting video?

### ISSUE THREAD

**Issue by arkid** [pupunzi/jquery.mb.YTPlayer#222]
I fear users may click the element (as it's very large on my page design) accidentally and not instantly realise why the video stopped.  Can I disable this?

**Comment by pupunzi** [comment]
Hi,
The toggle play is active only if the player is set as "player" using the "self" as containment (the video container correspond to the element that define the video properties.

you can find the event trigger **at line 235**:

```
				if( YTPlayer.isPlayer ) {
					overlay.on( "click", function() {
						$YTPlayer.YTPTogglePlay();
					} )
				}
```

At the time there's no option to manage it but you can comment those lines of code to prevent the behavior.

All the best,
Matteo

**Comment by arkid** [comment]
Thanks so much for this Matteo!
