### ISSUE TITLE
How can i restart player after Destroying player??

### ISSUE THREAD

**Issue by hasarang** [pupunzi/jquery.mb.YTPlayer#223]
I called external method "jQuery.fn.playerDestroy" to destroy player.
and then, how can i restart(re-init) the player?

below is the sample code

    var flag = true;
    $(document).on('click', '.btn-player', function(event) {
      event.preventDefault();

      if(flag === true) {
        // first time : ok, second times : not working
        $("#video").YTPlayer();
      } else {
        $("#video").playerDestroy();
      }
      flag = !flag;
    });

**Comment by pupunzi** [comment]
Hi,

there's a bug in the playerDestroy method. the YTPlayer.isReady state is not resetting while destroied. Replace it with:

```
		playerDestroy: function() {
			var YTPlayer = this.get( 0 );
			ytp.YTAPIReady = true;
			ytp.backgroundIsInited = false;
			YTPlayer.isInit = false;
			YTPlayer.videoID = null;
			YTPlayer.isReady = false;
			var playerBox = YTPlayer.wrapper;
			playerBox.remove();
			jQuery( "#controlBar_" + YTPlayer.id ).remove();
			clearInterval( YTPlayer.checkForStartAt );
			clearInterval( YTPlayer.getState );
			return this;
		},

```
This fix will be available on the next release.

**Comment by hasarang** [comment]
Hi

I really thank you for your fast reply and your kindness.
It works well. wow~~~~ !!!!

It took so long time to try to solve this problem.
thank you for your best plugin.

Regards
JB

2017-01-05 6:10 GMT+09:00 mb.jquery.components <notifications@github.com>:
