### ISSUE TITLE
changeMovie dynamically

### ISSUE THREAD

**Issue by smaouad** [pupunzi/jquery.mb.YTPlayer#226]
Hi pupunzi, 
Im trying to change the url dynamically using jquery without success.
When I click on an anchor, the default video is been loaded everytime.
Am I missing something ?
A helping handwould be very appreciated.
By the way, great plugin
there is my code 
````

#JS
$(document).ready(function () {

   var myPlayer = jQuery("#bgndVideo").YTPlayer();
    
    $(".category").on('click', function () {
        
        var id = $(this).attr('href');
        var data = $(id).attr('data-property')
        myPlayer.changeMovie(data);
    });
});

#HTML
<div id="wrapper" > 
<section id="container-1" data-property="{videoURL:'https://youtu.be/bPn5StfWUyQ',
      containment:'#wrapper', autoPlay:true, mute:false}">
</section>
<section id="container-2" data-property="{videoURL:'https://youtu.be/E5ln4uR4TwQ',
      containment:'#wrapper', autoPlay:true, mute:false}">
</section>
<section id="container-3"  data-property="{videoURL:'https://youtu.be/6KzJtBr6Yxg',
      containment:'#wrapper', autoPlay:true, mute:false}">
</section>
 
<a id="bgndVideo" data-property="{ videoURL:'https://youtu.be/bPn5StfWUyQ', containment:'#wrapper',autoPlay:true, mute:false}">video</a>
</div>
<ul>
  <li><a class="category" href="#container-1"> 1</a></li>
  <li><a class="category" href="#container-2"> 2</a></li>
  <li><a class="category" href="#container-3"> 3</a></li>
</ul>

    



```

**Comment by pupunzi** [comment]
Hi,
first you should use: `myPlayer.YTPChangeMovie(data)`, the method you are using is depracated and will be removed.

The YTPChangeMovie accept an object as parameter while you are passing a string. to solve this problem you should convert your string to an object as follow:

`
        var id = $(this).attr('href');
        var data = $(id).attr('data-property')
        data = eval( '(' + data + ')' )
        myPlayer.changeMovie(data);
`

That way it should work.

All the best,
Matteo

**Comment by smaouad** [comment]
Thanks works like a charm
