### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by TheSoulrester** [pupunzi/jquery.mb.YTPlayer#230]
Is it possibile to include an event?

An event for checking if a video is embeddable.
I have a script which extracts automatically die video id's out of an array but there are some videos which are not allowed to embedd them somewhere else...

I want to check if they aren't allowed to embedd, a function will be started to generate a new random id out of the array...

**Comment by pupunzi** [comment]
Hi,
The YTPlayer API can be initialized passing a callback function that fires if there's been an error:
`
jQuery("#[playerID]").YTPlayer({
     onError: function ($YTPlayer, err) {
               // your code here
    }
});
`
If the video can't be loaded this function will be fired and you can manage the behavior.

All the best,
Matteo
