### ISSUE TITLE
Quality setting not possible

### ISSUE THREAD

**Issue by rijosh** [pupunzi/jquery.mb.YTPlayer#232]
How to change defalut video quality

**Comment by pupunzi** [comment]
Hi,
there's a "quality" settings you can set that tells to the Youtube API which quality you would have:

`quality: "default", //or “small”, “medium”, “large”, “hd720”, “hd1080”, “highres”
`

Youtube anyway will set the quality based on the available bandwidth so even if you set hd1080, that quality will be available only if you have enough bandwidth.

All the best,
Matteo
