### ISSUE TITLE
Undefined image for the background of the container

### ISSUE THREAD

**Issue by 87elijah87** [pupunzi/jquery.mb.YTPlayer#233]
Hello.
Perhaps there is some error. (line 1567)
`background: "rgba(0,0,0,0.5) url(" + YTPlayer.opt.backgroundUrl + ") center center",`

Terms of occurrence:
containment != body
loop = false
autoplay = true

YTPlayer.opt.backgroundUrl = undefined.

I got the key to the API and use it.

**Comment by pupunzi** [comment]
Hi,
The backgroundUrl is used if the player is initialized as "self". Do you have an URL where I can see your issue?

**Comment by takisdoukas** [comment]
Hello,
I'm having the same issue as the OP.
Has the issue been solved?

Thanks

**Comment by pupunzi** [comment]
@takisdoukas :
Can you provide a public URL where the issue is happening?

That way I can check what is going wrong.

All the best,
Matteo

**Comment by takisdoukas** [comment]
Thanks for taking the time to look into this.

Here is a the URL.
http://rabel.dukedigitalmedia.com/aluminium-systems/rabel-65-slim-super-thermal-system

The video is set not to loop and on end, the poster frame does not load.

**Comment by pupunzi** [comment]
@takisdoukas 
I just published a new update (3.0.12) that should solve your issue.
Now it should not remove the background-image you set on the element.
Let me know.

**Comment by takisdoukas** [comment]
That works just fine, thank you!
