### ISSUE TITLE
YouTube googlevideo.com/videoplayback? canceled xhr

### ISSUE THREAD

**Issue by rossmc** [pupunzi/jquery.mb.YTPlayer#235]
We're using your plugin show a YT video as a background but have found that with the browser cache disabled or when a user first visits the page the video does not load correctly. On subsequent visits with the cache enabled it works, so it seems to have something to do with the browser cache.

This is the error we see in the browser's network panel:
<img width="1440" alt="screen shot 2017-02-11 at 15 22 52" src="https://cloud.githubusercontent.com/assets/2452991/22854936/28c9bd3a-f06f-11e6-901a-db0e2d47bdf9.png">

The full videoplayback url is: https://r6---sn-vov-8aje.googlevideo.com/videoplayback?itag=248&upn=ati3Ndct_to&expire=1486848105&dur=48.440&mime=video%2Fwebm&id=o-AAadFCZLEMtq8BpMPnURA9WPRkYaJsjB5oenWBv0ghLW&ms=au&mt=1486826485&mv=m&pl=18&source=youtube&mm=31&mn=sn-vov-8aje&ip=[i took out my ip address here]&gir=yes&clen=11908296&requiressl=yes&lmt=1464264652833029&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt6&initcwndbps=2261250&signature=4773CE851025FA815D8571479D7BD2223D92B6F6.86ADCEB29BF7450331E278721FC38AE95DDD6422&ipbits=0&alr=yes&keepalive=yes&ratebypass=yes&cpn=DJ7S1ehORsSWWz_q&c=WEB&cver=1.20170209&range=1328819-3289900&rn=5&rbuf=5905 

And the base.js file that is initiating it is: https://r6---sn-vov-8aje.googlevideo.com/videoplayback?itag=248&upn=ati3Ndct_to&expire=1486848105&dur=48.440&mime=video%2Fwebm&id=o-AAadFCZLEMtq8BpMPnURA9WPRkYaJsjB5oenWBv0ghLW&ms=au&mt=1486826485&mv=m&pl=18&source=youtube&mm=31&mn=sn-vov-8aje&ip=[i took out my ip address here]&gir=yes&clen=11908296&requiressl=yes&lmt=1464264652833029&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt6&initcwndbps=2261250&signature=4773CE851025FA815D8571479D7BD2223D92B6F6.86ADCEB29BF7450331E278721FC38AE95DDD6422&ipbits=0&alr=yes&keepalive=yes&ratebypass=yes&cpn=DJ7S1ehORsSWWz_q&c=WEB&cver=1.20170209&range=1328819-2141148&rn=7&rbuf=5905

There network errors disappears on subsequent visits with the cache enabled.

This is how we iniate the YT background video
```
            jQuery(function(){
                jQuery("#ytvideo-bg").YTPlayer();
            });

            jQuery('#ytvideo-bg').on("YTPReady",function(e){
                jQuery('#ytvideo-bg-wrapper .video-loader').fadeOut();
            });
```

And in our HTML
` <a id="ytvideo-bg" data-property="{videoURL:'https://youtu.be/xjJCMSSYCgQ',containment:'#ytvideo-bg-wrapper', autoPlay:true, mute:true, startAt:0, opacity:1, loop:true, showControls:false}" > </a>`

Any idea what could be causing this or how to fix it?

**Comment by pupunzi** [comment]
Hi,

The way you are initializing the video is correct.
Testing your video URL locally on a clean page works fine... 

Are you using other plug-ins that could interfere with the YTPlayer?
Do you have an URL where I can see your issue?

**Comment by rossmc** [comment]
Hi Pupunzi, yes here is the url:
http://fr.diet-expert.com/home-video

**Comment by pupunzi** [comment]
I'm not able to reproduce your issue on your page.
It's working fine for me.

On which browser you're having the issue?

**Comment by rossmc** [comment]
Chrome on MaxOSX with the cache disabled

**Comment by pupunzi** [comment]
Hi,
it happens to me too; but it is not directly related to the YTPlayer plug-in (it never happens to me in any installation). Probably there's some conflict with the other javascript you are loading on that page; but I'm not able to check which. 

I notice that you are including two times the jQuery framework:
- <script type="text/javascript" src="http://fr.diet-expert.com/js/mgt_developertoolbar/jquery-1.7.2.min.js"></script> 
- <script type="text/javascript" src="http://fr.diet-expert.com/skin/frontend/bootstrapped/default/js/jquery.js"></script>

And both are old version. You should include jQuery just once and possibly the latest release.

Let me know if you find the cause.
All the best,
Matteo

**Comment by rossmc** [comment]
ok thanks, will look into it more and let you know what I find.
