### ISSUE TITLE
Can I put 2 videos at the same time?

### ISSUE THREAD

**Issue by Franguestclain** [pupunzi/jquery.mb.YTPlayer#237]
I wanted to know how I could put two video background, but I do not mean the playlist, something like, the two videos in different sections and reproducing at the same time

**Comment by pupunzi** [comment]
Hi,
Of course you can... just add two video-placeholders specifying for each their containment element.

**For Ex:**

**javascript:**

```
var myPlayer;
$(function(){
   myPlayer = $(".ytplayer").YTPlayer();
});

```

**HTML**

```
<div id="video-1" class="ytplayer" data-property="{videoURL:'qvuILbcXlg8',containment:'#video-1', showControls:false, autoPlay:true, loop:true, mute:true, startAt:0, opacity:1, addRaster:true, quality:'default'}">My video</div> 

<div id="video-2" class="ytplayer" data-property="{videoURL:'qvuILbcXlg8',containment:'#video-2', showControls:false, autoPlay:true, loop:true, mute:true, startAt:0, opacity:1, addRaster:true, quality:'default'}">My video</div> 
```

For the start time of each element the sync is almost impossible due to the different buffer time.

**Comment by Franguestclain** [comment]
Hello! Thanks for answering me, sorry for not clarifying the question, but I also wanted the videos to be different. Greetings.

**Comment by pupunzi** [comment]
just set two different video ID...

**Comment by Franguestclain** [comment]
I did it, but it did not work, only a single video is shown :(

**Comment by Franguestclain** [comment]
Lol sorry, I already found my mistake. Thanks a lot man!
