### ISSUE TITLE
YTPEnd and YTPLoop not working?

### ISSUE THREAD

**Issue by pulketo** [pupunzi/jquery.mb.YTPlayer#238]
I'm not a programmer and perhaps i'm doing something wrong, but in your example:
demo_multiple_videos.html
YTPEnd and YTPLoop are never fired is that ok?
tested on Firefox for Linux 51.0.1 (64-bit)
and Chrome Version 54.0.2840.100 (64-bit)

**Comment by pupunzi** [comment]
Hi,
the YTPEnd event is fired correctly. If the video is looping then that event is fired only if you specified a number of loops at the end of last one.

The YTPLoop event doesn't exist at all :-)

All the best,
Matteo
