### ISSUE TITLE
Video not looping till the last second

### ISSUE THREAD

**Issue by AlexanderSk** [pupunzi/jquery.mb.YTPlayer#239]
Hello,

 i have set a video upload with the following code:
videoURL:'https://youtu.be/yzK4kvFRgmc',containment:'#intro',showControls:true,autoPlay:true, mute:true,startAt:0,opacity:1,optimizeDisplay:true,loop:true

The issue is that the video is 18 seconds long but the loop only goes until the 17th second and no the 18th.
I have set showControls to true in order to verify that and also tried to work around it with stoptAt:18 but with no success.

**Comment by pupunzi** [comment]
Hi,
That is the behavior of the player to prevent the display of the Youtube "play" button at the end of the video. it stops 1 second before the real end. If you need to loop at the exact end you have to add 1 or more seconds at the end of the video.

All the best,
Matteo

**Comment by borishere** [comment]
@pupunzi Any coding workaround without modifying the exact video?

**Comment by AlexanderSk** [comment]
If you have the latest version of the plugin i believe it is now fixed. It does play till the end...

**Comment by borishere** [comment]
@AlexanderSk Thanks, I will try the latest version.
