### ISSUE TITLE
Custom video control icons

### ISSUE THREAD

**Issue by iamDeJa** [pupunzi/jquery.mb.YTPlayer#241]
Greetings!
First of all thanks for the amazing player you have provided, second, I don't know if this is the right place for such a question/issue.

I was wondering if it was possible to use custom video control icons when the video is playing in background, instead of the standard 'p/P' and 'm/M'. When I tried to edit the code I simply broke everything :/
So my question is, would it be possible?
Thanks a lot and sorry if this is the wrong palce

**Comment by pupunzi** [comment]
Hi, this is the right place :-)

You've two possibilities:

1) disable the standard controls at the footer and create your own using [the API](https://github.com/pupunzi/jquery.mb.YTPlayer/wiki#external-methods)

2) The action icons are fonts, if you want to use an image instead on fonts you can overwrite the **jQuery.mbYTPlayer.controls object** before the initialization of the component specifying for each the HTML to insert:

```
		jQuery.mbYTPlayer.controls: {
			play: "<img src='[the/path/to/image]'/>",
			pause: "<img src='[the/path/to/image]'/>",,
			mute: "<img src='[the/path/to/image]'/>",,
			unmute: "<img src='[the/path/to/image]'/>",,
			onlyYT: "<img src='[the/path/to/image]'/>",,
			showSite: "<img src='[the/path/to/image]'/>",,
			ytLogo: "<img src='[the/path/to/image]'/>",
		}

```

Or you can create your own font, set the letters each command corresponds and change the **ytpregular** font reference in the **jquery.mb.ytplayer.min.css** file with your.

Hope this helps,
M

**Comment by iamDeJa** [comment]
Oh I see. I'll try this out. Thanks a lot!
