### ISSUE TITLE
startAt argument doesn't work

### ISSUE THREAD

**Issue by yyyyaaa** [pupunzi/jquery.mb.YTPlayer#243]
I am trying to integrate YTPlayer into my website as a background video. However, I want the video to start at 00:12 so I tried putting startAt:12 in both of the data-property and in the constructor of YTPlayer but none of them has worked for me.

The code I'm using for the website looks like this:

```
jQuery(document).ready(function () {
        jQuery('.Hero--video').YTPlayer({
            fitToBackground: true,
            startAt: 12,
            mute: true,
	    showYTLogo: false,
            autoPlay: false,
            <?php if (get_field('video')) { ?>
            videoId: '<?= get_field('video') ?>'
            <?php } else {
                echo "videoId: 'P7kCmkqYGho'";
            } ?>
        });
    });
```

Other arguments like mute: false or fitToBackground work when I try giving them different values.
The ID of my youtube video is: P7kCmkqYGho
My website for reference:
http://oshp.ml/intern/

The video is in the hero section.

**Comment by pupunzi** [comment]
Hi,
here is an example of your video starting at 12.
https://pupunzi.com/mb.components/mb.YTPlayer/demo/test.html

Anyway looking at your pages it doesn't seams you are using my video library...
the **fitToBackground** property does not exist.

All the best,
Matteo
