### ISSUE TITLE
Any docs how to setup a Fallback image for mobile devices? 

### ISSUE THREAD

**Issue by weilinzung** [pupunzi/jquery.mb.YTPlayer#244]
I just use a normal CSS way instead now, but I saw the plugin script has this option, but can'f find any example to set it up? how to call this data-property? thanks~

```
if( jQuery.browser.mobile && !YTPlayer.canPlayOnMobile ) {
if( YTPlayer.opt.mobileFallbackImage ) {
	wrapper.css( {
		backgroundImage: "url(" + YTPlayer.opt.mobileFallbackImage + ")",
		backgroundPosition: "center center",
		backgroundSize: "cover",
		backgroundRepeat: "no-repeat",
		opacity: 1
	} )
};
```

**Comment by pupunzi** [comment]
Hi,
it's not documented yet but yes, there's the **mobileFallbackImage** option that let you specify an absolute path to an image that would be used in case of video background on mobile.

You can either set that when you initialize the player or passing it as data-property:

1.  

`var myPlayer = jQuery("#bgndVideo").YTPlayer({mobileFallbackImage:'absolute/path/to/image'});`

2.

`    <div id="bgndVideo" class="player" data-property="{videoURL:'2yacT1XMjsg',containment:'body', showControls:true, autoPlay:true, loop:false, vol:50, mute:false, startAt:0,  stopAt:296, opacity:1, addRaster:true, quality:'large', optimizeDisplay:true, mobileFallbackImage:'absolute/path/to/image'}">My video</div>
`

**Comment by weilinzung** [comment]
very nice. thanks!!!! It works for me.

**Comment by jeffkee** [comment]
In my case, despite having the URL set for the mobileFallbackImage, the whole DIV just disappears. I have an <img> tag in there, as that is supposed to be the temporary background until the video loads (i'm using Layerslider, so loading the YTPlayer instance inside the Layerslider). 

For the time being, I ran a script to DISABLE the YT player from loading at all, now it just falls back to the <img> tag. 

You can see the demo at [http://www.davidweilhomes.com/](url)

`<div id="videoData" class="player ls-l" style="width: 1920px; height: 920px; top: 0; left: 0; background-color: #aaa;" data-property="{videoURL:'http://youtu.be/F-weSOIHxXU',containment:'#videoData',autoPlay:true, mute:true, startAt:0, opacity:1, quality: 'hd1080', gaTrack: false, showYTLogo: false, loop: true, mobileFallbackImage: 'http://davidweilhomes.com/pages/36/main.jpg?mod=1488934297' }"><img class="mob_thumbnail" class="ls-bg" src="http://davidweilhomes.com/pages/36/main.jpg?mod=1488934297"/></div>`
