### ISSUE TITLE
Video Quality Options

### ISSUE THREAD

**Issue by weilinzung** [pupunzi/jquery.mb.YTPlayer#245]
Hi,

Just want to ask confirmation about the quality option. 
1. Would it automatic detect the video quality with the script options? 
2. Are these options same as the Youtube? 
`small, medium, large, hd720, hd1080, highness <-Script Option`
`240P,    360P,   480P,  720P,   1080P,  1440P  <- Youtube Option`
http://i.imgur.com/AaLcMYe.png

3. If I set the video to `medium` quality, then the video itself doesn't have the `medium`,  what would be selected then? Back to default?

thanks!

**Comment by pupunzi** [comment]
Hi,
The video quality options are suggestions for the API. Is Youtube that choose the quality based on the bandwidth and the browser capability taking in consideration the suggestion you give.

Read more here: https://developers.google.com/youtube/iframe_api_reference#setPlaybackQuality
