### ISSUE TITLE
Missing option to set iv_load_policy

### ISSUE THREAD

**Issue by thdoan** [pupunzi/jquery.mb.YTPlayer#247]
I would like to set `iv_load_policy=3` to disable annotations, but there doesn't appear to be an equivalent option in YTPlayer.

You should support all of the available options as the native player:

https://developers.google.com/youtube/player_parameters

**Comment by pupunzi** [comment]
Hi,
the option exist, is the "showAnnotations" that by default is set to false.

All the best,
Matteo

**Comment by thdoan** [comment]
OK, thanks. Please update your wiki because this option is not listed there:

https://github.com/pupunzi/jquery.mb.YTPlayer/wiki
