### ISSUE TITLE
Video plays even after YTPStop();

### ISSUE THREAD

**Issue by Praneeth-Pike** [pupunzi/jquery.mb.YTPlayer#248]
Hi, I have an element contained video that plays as an overlay in a fixed div. When I close the fixed overlay div, I'm running a function that looks like this:
`$("#close-button").on('click', function(){
    $('#myPlayerContainer').YTPStop();
    $('#video-overlay').hide();
});`

After that the video stops for a moment and resumes playing after few seconds. Sometimes it happens when I go to another tab and revisit my page again. In both cases, after I have YTPStop()'ed the video, I don't see the video because my #videoContainer is hidden, I only hear the audio.

**Comment by pupunzi** [comment]
Do you have an URL where I can see this behavior?
