### ISSUE TITLE
Video does not start in safari

### ISSUE THREAD

**Issue by vladvi** [pupunzi/jquery.mb.YTPlayer#250]
Hi, the video in the safari browser does not start, what could be the problem? Site address http://alekseiptitsa.com/

**Comment by pupunzi** [comment]
Hi,
Just tested your site on Safari 10.1 (12603.1.30.0.34) and it's working fine.
What version of Safari and what version of OS are you testing with?

**Comment by vladvi** [comment]
Safari 8.0.8 (10600.8.9)
OS X Yosemite

**Comment by vladvi** [comment]
In version 10.1 (10603.1.30.0.34) does not work either 
OS X Yosemite version 10.10.5

**Comment by pupunzi** [comment]
I suppose the problem is the OSX version (Yosemite)
Just published a new release (3.0.15) that should fix the problem. 
Try downloading it (https://github.com/pupunzi/jquery.mb.YTPlayer/archive/3.0.15.zip) and let me know.

**Comment by vladvi** [comment]
1. macOS Sierra version 10.12.4
Safari version 10.1 (12603.1.30.0.34) 
It works, but when the page is reloaded, it does not start from the beginning, but from the moment the page is reloaded

2. OS X Yosemite version 10.10.5 
Safari 10.1 (10603.1.30.0.34) 
Runs and immediately stops, when you restart the video - it changes by frame

3. Opera version 43.0.2442.1165, Chrome 57.0.2987.133
It starts, but when the page is reloaded, the video does not start from the beginning

**Comment by pupunzi** [comment]
There's a new feature (remember_last_time) that define if the video should start from the last frame it was before the page was left. By default is set to true.

For Safari on Yosemite I can't test it here but should have the same behavior as it had before... I'll be able to test on Yosemite in the next future.

**Comment by vladvi** [comment]
Yes, really, thanks, did not know about the new function (remember_last_time). 
Tell me how to remove the pause when clicking on the video. http://pastenow.ru/8d54c3f280847bf8ccb52d0282065675
And when you double click the youtube window opens http://pastenow.ru/8d54c3f280847bf8ccb52d0282065675

**Comment by pupunzi** [comment]
on http://alekseiptitsa.com/ it doesn't happens for me and it should not happens as there's an overlay that prevent it.

**Comment by vladvi** [comment]
I have this happening in all browsers (safari, firefox, chrome, opera), try clearing the cache

**Comment by pupunzi** [comment]
Hi Vlad,
You set the display of the .YTPOverlay to "none" on your style.css removing the overlay and enabling that way the click event on the video. 
If you don't want the raster over the video just set the addRaster property to false but don't remove the YTPOverlay.

**Comment by vladvi** [comment]
Thank you for pointing out my mistake, corrected.
The problem remains in version safari 10.1 (10603.1.30.0.34) video does not start
OS X Yosemite version 10.10.5 . The rest is all super!

**Comment by pupunzi** [comment]
Tested on **OS X Mavericks** (version 10.9) with Safari 9.5 and on **OS X El Capitan** (version 10.11) with Safari 10.1  and it's working fine on both. Are you sure that on Yosemite it doesn't work?

**Comment by vladvi** [comment]
Yes sure, does not work in Yosemite.
For example, in this version of the plug-in, the video starts up in Yosemite: http://test.vladvi.com/libs/ytplayer/jquery.mb.YTPlayer.min.js

**Comment by pupunzi** [comment]
I've no way to test it on Yosemite but it sounds strange as it's working on the previous OS X Mavericks and on the next OS X El Capitan; there's a condition in the code that set an hack for Safari on OS previous then El Capitan (the same you had on the 2.6.0 you mentioned.

Can you try the 3.0.11 on Yosemite and tell me if that works?

**Comment by vladvi** [comment]
Tested, with version 3.0.11 also does not work in Yosemite.
Made a video https://www.youtube.com/watch?v=jRhB_M2cVvE&feature

**Comment by pupunzi** [comment]
Can you try the attached file and check if it works on Yosemite?
Thank you.

[jquery.mb.YTPlayer.js.zip](https://github.com/pupunzi/jquery.mb.YTPlayer/files/955888/jquery.mb.YTPlayer.js.zip)

**Comment by vladvi** [comment]
Yes, attached file it works for Yosemite!

I also tested previous versions, the last working one on Yosemite turned out to be this
https://github.com/pupunzi/jquery.mb.YTPlayer/releases/tag/3.0.0 Can it help you in optimizing your code. Thanks for the feedback!

**Comment by pupunzi** [comment]
Just published the 3.0.16 release that should work on Yosemite too.
Let me know.

**Comment by vladvi** [comment]
Yes, version 3.0.16 works fine on Yosemite! Thank you!
