### ISSUE TITLE
Safari 10.1 autoplay issue.

### ISSUE THREAD

**Issue by jalite1991** [pupunzi/jquery.mb.YTPlayer#251]
Hello, There seems to be a compatibility issues when running the YTPlayer in Safari Browser version 10.1 on Mac. This is a new release of safari so I think it might be a bug in the browser. I was wondering if you guys can confirm whether it is happening for you, and did you know of a work around.

**Comment by pupunzi** [comment]
Hi,
this issue should have been fixed with the latest 3.0.15 release...
What OS did you test with?

**Comment by jalite1991** [comment]
OS X Yosemite v10.10.5

**Comment by pupunzi** [comment]
I've no possibility to test it on Yosemite... can you try this and check if it works on Yosemite?
Thank you.

[jquery.mb.YTPlayer.js.zip](https://github.com/pupunzi/jquery.mb.YTPlayer/files/955888/jquery.mb.YTPlayer.js.zip)

**Comment by vladvi** [comment]
Try the new version of https://github.com/pupunzi/jquery.mb.YTPlayer/releases/tag/3.0.16 I had the same problem

**Comment by jalite1991** [comment]
Updating was perfect thanks. Turns out even though I had updated, I still had 3.0.14 in the cache instead of 3.0.15. Once I went through some extra steps to clear my cache, everything worked out.
