### ISSUE TITLE
Is it just me? Ver 3.0.15 and 3.0.16 dont work!

### ISSUE THREAD

**Issue by digitart** [pupunzi/jquery.mb.YTPlayer#253]
Even the online demos are broken, as in https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html
Actually ver 3.0.14 has problems with lists! You can not change mute status with control bar, among other things.
I've downloaded ver 3.0.10 and added by hand some  new features as YTPPlayIndex(), preserve mute status while playing lists and be able to set value for "abundance" to let me decide the size of the bleeding in optimizeDisplay

**Comment by pupunzi** [comment]
It's working fine for me tested on Chrome, Firefox, Opera, Safari on Mac El Captain and Sierra and on Chrome, Firefox, IE11 and Edge on Windows.
Can you be more specific on the issues you have with lists?

Thank you,
Matteo

**Comment by digitart** [comment]
This is the error I get in Chrome
Uncaught TypeError: Cannot read property '1' of null
    at getOS (jquery.mb.YTPlayer.js:2078)
    at jquery.mb.YTPlayer.js:2078

I'm in Ubuntu with Chrome Versión 58.0.3029.96 (64-bit)
It also happen with Opera and Firefox in my box. I've tryed your demo in a Windows box and worked perfectly, so I presume it has to do with the OS detection.

On the other hand, when I reproduce a list with v. 3.0.14 the player triggers YTPReady (and maybe all events at once) again and again reseting any change in volume or mute state so it's impossible to change the volume or mute or unmute the reproducion, wich is jagged because of the excesive activity of the script.
This all happen in my Ubuntu box, couldn't test it on windows.

Thank you for your great job and scripts! Hope this report helps.
AV

**Comment by pupunzi** [comment]
It helps :-)
I recently changed the OS detection method and probably I generate a bug detecting linux OS...
As soon as I'll fix the error I'll let you know.
thank you.

**Comment by pupunzi** [comment]
with the latest 3.0.17 the bug should be fixed.
Let me know.

**Comment by digitart** [comment]
It's working!! Thank you! 
Now 3.0.17 is working back in Linux! Your website demos still use 3.0.16 but I tested in http://codepen.io/digitart/pen/GmELaM and worked perfectly.
I'm about to test playing lists to see  if the YTPReady issue is now fixed as well. If I can reproduce the problem with v3.0.17 I'll post it as a new issue, to let you mark this one as fixed.
I take this opportunity to tank your efforts, support and great scripts, specially YTPlayer. I've been fan of your scripts by years!

**Comment by gormus** [comment]
I get errors with v3.0.17 too, on Windows 10 Home + Chrome 58.0.3029.96 (64-bit)

![capture](https://cloud.githubusercontent.com/assets/291025/25790776/537777d6-3370-11e7-9b05-03d4d1a07f2c.PNG)

**Comment by pupunzi** [comment]
@gormus : 
Do you have a public page where I can see the issue?
What is the error you are getting?

**Comment by gormus** [comment]
@pupunzi 

I don't have a copy of the error message anymore; but it was something like `name` not being available in the context. Also, my project is not publicly available yet, still on local development. So, I won't be able to provide more feedback ATM.

Though, after I downgraded it to v3.0.14, it worked without errors.

**Comment by dedman** [comment]
Hey @pupunzi, firstly thank you for your great libraries!

I just upgraded to v3.0.17 and I am seeing the same issue as @digitart reported (Cannot read property '1' of null). However I am seeing it in iOS Safari and chrome when pretending to be the iPhone. 

If you view http://codepen.io/digitart/pen/GmELaM on an iOS device with Safari it doesn't work. And if you view it in chrome, emulating an iPhone, you can see there is the "Uncaught TypeError: Cannot read property '1' of null" error again.
 
![screen shot 2017-05-09 at 11 52 16 am](https://cloud.githubusercontent.com/assets/11966/25860044/4e99ce82-34ae-11e7-8388-d6b673acbd85.png)
<img width="499" alt="screen shot 2017-05-09 at 11 52 26 am" src="https://cloud.githubusercontent.com/assets/11966/25860051/52f2c1c8-34ae-11e7-939f-3a1fae388c26.png">

**Comment by pupunzi** [comment]
@dedman :
The iOs bug has been fixed within the 3.0.18 release.
Anyway this plugin can't work on mobile devices; you can specify a fallback image via the "mobileFallbackImage" option that will be used on mobile devices.

**Comment by dedman** [comment]
Thanks for the quick turn around @pupunzi, yeah I'm not trying to make it work on mobile devices, its just that the error was causing other JS on the page not to execute.
