### ISSUE TITLE
Problem with YTPlaylist

### ISSUE THREAD

**Issue by digitart** [pupunzi/jquery.mb.YTPlayer#254]
Since 3.0.13 reproducing lists re-triggers over and over again all events, reseting mute and volume and making a frentic work that slows down the browser.
I cloned one of the demos in https://teatro.mx/av/list17.html using ver. 3.0.17 to let you see the problem, and you can check https://teatro.mx/av/list12.html as a reference with ver 3.0.12. I only added a few extra lines to show a mesage in console every time that YTPStart is triggered.
To see the problem in action open the console and wait to the second video to start and you'll see the messages regarding YTPStart repeat indefinitely. If you try to mute it will be resetted and even if you change focus to another window the video will keep playing. Audio is also affected by this re-triggering.
As a reference, you can try list12.html that correctly triggers only one YTPStart event on every video start.
I tested it in Linux and windows with Chrome and Firefox with same results.

**Comment by pupunzi** [comment]
@digitart : There was a bug. just published the 3.0.19 release fixing it. It should work fine now.
