### ISSUE TITLE
Need to modify to youtube-nocookie - how to do?

### ISSUE THREAD

**Issue by Garavani** [pupunzi/jquery.mb.YTPlayer#255]
Hello out there,

I noticed that my theme (WP) is using your awesome plugin to create video backgrounds.

I am desperately trying to modify it in a way that instead of the iframe embed src with ‘www.youtube.com/embed…’ it creates the src with ‘www.youtube-nocookie.com/embed…’ instead.
I am tearing my hair out, can’t get ahead with this. Someone out to help?

**Comment by pupunzi** [comment]
Hi,
The YTPlayer plug-in is using the Youtube API to embed the specified video so I think you have no possibility to use a different service to include it.

All the best,
Matteo

**Comment by Garavani** [comment]
Thanks for the answer!

Have a nice evening!

Stefan
—

Stefan Seifert  ·  stefanseifert.com <http://stefanseifert.com/>  ·  @stefanseifert33 <https://twitter.com/stefanseifert33>
