### ISSUE TITLE
Detect video ended

### ISSUE THREAD

**Issue by Softid30** [pupunzi/jquery.mb.YTPlayer#256]
Is there a way to detect when the video ended? I would like to show some text after the video played once and has done playing.

**Comment by pupunzi** [comment]
Hi, 
the plugin expose events for all its states. Read the doc: https://github.com/pupunzi/jquery.mb.YTPlayer/wiki#events

All the best,
Matteo

**Comment by Softid30** [comment]
I was on that page but it was late yesterday. I must have skipped that part somehow.
Thank you!
