### ISSUE TITLE
Background Video does not loop.

### ISSUE THREAD

**Issue by emilche** [pupunzi/jquery.mb.YTPlayer#258]
Hi. Great plugin! I have a problem though. I checked in that the video should loop but when the video reaches the end it goes back to a thumbnail and shows the YouTube play button. Please help me.

https://gyazo.com/e58e3f27848839d3f689498f14092436
https://gyazo.com/247d23723bfa06656d739e2a149b0f40
https://gyazo.com/89029df9b48ba485bc55ef69051ee2fa

**Comment by Critick-rbs** [comment]
I have the same problem. When I am ON my page - it's ok, but when I'm spending some few minutes on another browser pages and coming back - I see stopped video with non-active play button in the center of the screen. Using Firefox. ```

data-property = "{
		videoURL 		: 'https://youtu.be/A9abHX_NSK4',
		containment 	: '.main-screen',
		autoPlay 		: true,
		mute 			: true,
		startAt 		: 0,
		opacity 		: 1,
		quality 		: 'highres',
		loop 			: true,
		optimizeDisplay : true,
		showYTLogo 		: false,
		showControls 	: false,
		realfullscreen  : true,
		stopMovieOnBlur : false}"
```
My test page: http://test-1.rbsdev.pro/

**Comment by replicat0r** [comment]
you can get around this by playing your video in a playlist and have the loop set to true. It works for me. It no longers stops and have the play button on the background
