### ISSUE TITLE
Message on video end

### ISSUE THREAD

**Issue by cosmos74** [pupunzi/jquery.mb.YTPlayer#259]
When the video ends there is a message ENDED! How can it be not showing?
Thanks in advance.

**Comment by pupunzi** [comment]
@cosmos74 
Where are you getting the message? On the console or on the page?
Can you point me to a file where this happens?
I can't find any place in the code where the "ENDED!" message is displayed.

All the best,
Matteo

**Comment by cosmos74** [comment]
see the page : http://pbssacapital.com/demo/index-3.html
On firefox and Chrome the message appears. Please let video finished to see the popup message.
Thanks Matteo.

**Comment by pupunzi** [comment]
@cosmos74 
You are using a really old version of the plug-in (2.6.2) we are now at **3.0.19**.
I really suggest you to update to the latest version. Anyway there's any alert inside the YTPlayer code (even the 2.6.2) so it could have been added anywhere on your site javascript code probably on the YTPEnd event. Try searching YTPEnd on your project files and see if there's an alert("ENDED!").

All the best,
Matteo

**Comment by pupunzi** [comment]
@cosmos74 
The alert is on your "controls.js" file: http://pbssacapital.com/demo/assets/js/controls.js

       ```
     jQuery("#bgndVideo").on("YTPEnd", function(){
                alert("ENDED!");
                jQuery("#eventListener").html("YTPEnd");
                jQuery("#eventListener").append(" :: (state= "+ jQuery("#bgndVideo").getPlayer().getPlayerState()+")");
                console.debug("YTPEnd")
            });
```

**Comment by cosmos74** [comment]
Thank you for your quick reply on this issue. How it can be removed? Delete the specific function?
