### ISSUE TITLE
YTPlayer container removed entirely on mobile devices

### ISSUE THREAD

**Issue by 20bs** [pupunzi/jquery.mb.YTPlayer#260]
Hi,

It appears that when viewing on mobile devices the entire YTPlayer container is getting removed. I'm not sure this was the intended effect.

It looks like the code adds the background image if available, in the previous if statement: 

if( YTPlayer.opt.mobileFallbackImage ){}

then simply removes the entire container. Seems like the container should remain with the background image.

This issue is in jquery.mb.YTPlayer.src.js on line 353.

**Comment by pupunzi** [comment]
The YTPlayer object is not the element where the video is played either then if the player is initialized with the containment option set as "self" that means you are using the YTPlayer as player, the containment is the placeholder itself and it is not playing as background. 
If the player is set as above the "canPlayOnMobile" is set to true (the player should be rendered as the default Youtube player also on mobile devices) and the fallback image should not be set as it don't enter in the condition "jQuery.mbBrowser.mobile && !YTPlayer.canPlayOnMobile".

If the script enter into that condition it means the "wrapper" element that should have the background image is not the YTPayer object that is going to be removed.

**Comment by ilPas** [comment]
Same problem...how can i resolve it?Thanks!
