### ISSUE TITLE
video on safari don't autostart

### ISSUE THREAD

**Issue by rapope22** [pupunzi/jquery.mb.YTPlayer#261]
Recently updated my safari to Version 10.1 (12603.1.30.0.34), and I notice the jquery.mb.ytplayer no longer auto play.

**Comment by pupunzi** [comment]
What version of jquery.mb.ytplayer are you using?
do you have a link where I can see your issue?

**Comment by rapope22** [comment]
thank for replying,
I am using jquery.mb.YTPlayer.js  last modified: 24/10/16 22.30 
and the site is www.oneislandband.com <http://www.oneislandband.com/>

I am only experiencing this problem in safari

**Comment by pupunzi** [comment]
The latest version is 3.0.19 while yours is 3.0.12. This issue has been fixed on the last release.
Update the script to the last version to fix the problem.

All the best,
Matteo

**Comment by rapope22** [comment]
will do thank you!!On May 23, 2017, at 1:45 PM, mb.jquery.components <notifications@github.com> wrote:The latest version is 3.0.19 while yours is 3.0.12. This issue has been fixed on the last release.
Update the script to the last version to fix the problem.All the best,
Matteo—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pupunzi/jquery.mb.YTPlayer","title":"pupunzi/jquery.mb.YTPlayer","subtitle":"GitHub repository","main_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>","avatar_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>","action":{"name":"Open in GitHub","url":"<a href="<a href="https://github.com/pupunzi/jquery.mb.YTPlayer" class="">https://github.com/pupunzi/jquery.mb.YTPlayer</a>" class=""><a href="https://github.com/pupunzi/jquery.mb.YTPlayer" class="">https://github.com/pupunzi/jquery.mb.YTPlayer</a></a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pupunzi in #261: The latest version is 3.0.19 while yours is 3.0.12. This issue has been fixed on the last release.\r\nUpdate the script to the last version to fix the problem.\r\n\r\nAll the best,\r\nMatteo"}],"action":{"name":"View Issue","url":"<a href="<a href="https://github.com/pupunzi/jquery.mb.YTPlayer/issues/261#issuecomment-303478682" class="">https://github.com/pupunzi/jquery.mb.YTPlayer/issues/261#issuecomment-303478682</a>" class=""><a href="https://github.com/pupunzi/jquery.mb.YTPlayer/issues/261#issuecomment-303478682" class="">https://github.com/pupunzi/jquery.mb.YTPlayer/issues/261#issuecomment-303478682</a></a>"}}}
