### ISSUE TITLE
transfert my licence to another domaine?

### ISSUE THREAD

**Issue by xnvbp** [pupunzi/jquery.mb.YTPlayer#263]
hello :)

Thanks for your good worlpress plugin.
Is it possible to transfer my license to another domain?
Thank you for your reply. 
Sorry for my English.

**Comment by pupunzi** [comment]
@xnvbp 
Hi,
Of course it is possible. Just install the plug-in on the other domain and insert the key; the verification will return a message that says your license is not valid for that domain and with a link that points you to the procedure to change it. Clicking on the link you'll receive an email to the address you specify when you purchase the license; in the email there'll be a link to a page where you can specify the new domain.

Once you changed it revalidate the key.

Hope this helps you,

All the best,
Matteo

**Comment by xnvbp** [comment]
Beautiful, thank you very much :)
