### ISSUE TITLE
Play a list of videos in wordpress

### ISSUE THREAD

**Issue by xnvbp** [pupunzi/jquery.mb.YTPlayer#264]
Hello :)
I can not make a playsit with the wordpress plug in. Is it possible? Can you help me?

For exemple:
[mbYTPlayer url="https://www.youtube.com/watch?v=X-dMOvEOQiM" opacity="0" quality="default" ratio="auto" isinline="false" showcontrols="false" realfullscreen="true" printurl="true" autoplay="true" mute="true" loop="true" addraster="true" stopmovieonblur="true" gaTrack="false" ]

What should I write?

best regard

**Comment by pupunzi** [comment]
Hi,
The Wordpress plug-in has not implemented the playlist yet.
You can set a comma separated list of video URL that the player will play randomly each time the page is loaded.

The playlist feature will be available soon for the PLUS plug-in.

All the best,
Matteo

**Comment by xnvbp** [comment]
thank you for your reply matteo
