### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by gibbons1984** [pupunzi/jquery.mb.YTPlayer#265]
Hi, I am using the player through a template off Themeforest and the video works fine but i am getting infinite errors through the console. I've looked htough a lot of the closed issues to see if already been flagged but couldn't see it. These are the errors which I am getting:

Uncaught TypeError: Cannot read property 'prototype' of undefined
    at annotations_module.js:386
    at annotations_module.js:659
(anonymous) @ annotations_module.js:386
(anonymous) @ annotations_module.js:659
captions.js:84 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at captions.js:84
    at captions.js:174
(anonymous) @ captions.js:84
(anonymous) @ captions.js:174
annotations_module.js:386

**Comment by pupunzi** [comment]
Hi,
All the errors you are referring to are not generated by my scripts.
As you can see they come from the **annotations_module.js** and from the **captions.js** files that are not part of my component.

All the best,
Matteo

**Comment by gibbons1984** [comment]
Thanks for reply. I don't have any scripts by that name and it only happens when i load
jquery.mb.YTPlayer.js

It might be to do with the video I am loading. I will carry on looking. Cheers

**Comment by pupunzi** [comment]
Do you have an URL where I can see the issue?

**Comment by gibbons1984** [comment]
Hi, thanks for the reply. For some bizarre reason it seems to have fixed itself and is no longer doing it. Cheers and great plugin
