### ISSUE TITLE
Multiple background videos

### ISSUE THREAD

**Issue by JaXLad** [pupunzi/jquery.mb.YTPlayer#266]
Hello! Awesome plugin!

I am coming across a bit of a problem. I use the plugin for playing YouTube background videos on a few slides of a carousel so I am using the data-property tag with a YouTube video url on a div within each slide's html  As there are a few slides in the carousel, I have multiples instances with different videos on one page. 

My issue is that I want to play the video when a slide that has a background video set by your plugin but destroy it when I have moved away from it but equally re-create the video if I end up revisiting the same slide later. I have used the **YTPPlayerDestroy()** method to perform the removal and **YTPlayer()** method for creating it on the carousel's changed event listener but I keep getting a '_Uncaught TypeError: Cannot read property 'toString' of null_' error message to your plugin if I swipe in between two slides that have a background video set on consecutively to each other. Any ideas on how to make a simple function that can do what I trying to do?

https://jsfiddle.net/tb7y84zu/4/

```html
<div id="slide1" class="container" style="width: 100%; height: 50%">
   <div id="video1" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=iNJdPyoqt8U', containment:'#slide1', showControls:false, autoPlay:true, loop:true, mute:true, opacity:1, quality:'default'}"></div>
   <button onClick="$('div#video1').YTPPlayerDestroy();">Remove</button>
   <button onClick="$('div#video1').YTPlayer();">Add</button>
</div>
<div id="slide2" class="container" style="width: 100%; height: 50%">
   <div id="video2" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=mkggXE5e2yk', containment:'#slide2', showControls:false, autoPlay:true, loop:true, mute:true, opacity:1, quality:'default'}"></div>
   <button onClick="$('div#video2').YTPPlayerDestroy();">Remove</button>
   <button onClick="$('div#video2').YTPlayer();">Add</button>
</div>

**Comment by pupunzi** [comment]
Hi,
the code you have on the jsfiddle is working fine... it create and remove correctly the video...
I should see it in action on the carousel to see if I can help you...
