### ISSUE TITLE
Mobile Device Change Default YT Player Background to Custom One

### ISSUE THREAD

**Issue by pramodsandakelum** [pupunzi/jquery.mb.YTPlayer#268]
I need to change the default yt player background on mobile to a custom one can i do this

**Comment by pupunzi** [comment]
On mobile devices the background video doesn't work... you should set the mobileFallbackImage option on mobile devices.

**Comment by frafor1988** [comment]
Hi on latest versions of chrome mobile it is making a mess: 3.1.5 shows up the fallback image, then the standard yt player, then loading, then stops and fadeout. 3.1.11 stucks in blank screen.
