### ISSUE TITLE
Background Video Autoplay on iOS 10 or later

### ISSUE THREAD

**Issue by surjithctly** [pupunzi/jquery.mb.YTPlayer#269]
As per this Webkit Blog post, https://webkit.org/blog/6784/new-video-policies-for-ios/ Starting from iOS 10, Apple relaxed some video autoplay restrictions. 

Do, Do you have any plan to give options to make compatible with that? is there a workaround, we can use now?

~Surjith

**Comment by pupunzi** [comment]
I know that iOs 10 now could support the inline autoplay videos but that doesn't seems to be adopted by the Youtube API. I'm sure that in the next future it will be possible but not for now.

All the best,
Matteo
