### ISSUE TITLE
jQuery.normalizeCss is not a function

### ISSUE THREAD

**Issue by bipashant** [pupunzi/jquery.mb.YTPlayer#271]
Hi
I'm trying to integrate the player in my web application written in Rails, 
and I'm getting this error. 
I created an div element as in your documentation
` <div id="bgndVideo" class="player" data-property="{videoURL:'https://youtu.be/b9KnPR6Jxj4',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}">bg</div>`

and then 

```
    jQuery(function(){
        jQuery("#bgndVideo").YTPlayer();
    });
```

Is there anything I need to do in addition to this?
Thank you 

<img width="1392" alt="screen shot 2017-07-10 at 2 13 49 pm" src="https://user-images.githubusercontent.com/5179884/28009428-221b7588-657b-11e7-8fed-cecab705a4e7.png">

<img width="913" alt="screen shot 2017-07-10 at 2 16 24 pm" src="https://user-images.githubusercontent.com/5179884/28009402-14021c68-657b-11e7-9097-9d099c03f9e1.png">

**Comment by pupunzi** [comment]
Hi,
I presume you are integrating the jquery.mb.YTPlayer.src.js loacated in the "src" folder instead of the jquery.mb.YTPlayer.js or the jquery.mb.YTPlayer.min.js located in the "dist" folder.

**Comment by chekle** [comment]
I had this same error, for me it was due to the version of jquery I was loading, I had v1.11.1 and now I'm loading v1.12.4, everything is working well. I thought I'd mention this in case someone else has the same issue.

**Comment by arturmamedov** [comment]
I tried with jquery 3.4.1 and 3.5.1, doesn't work for me.
Alsoi can't find a function called normalizeCss anywhere

**Comment by pupunzi** [comment]
@arturmamedov 
I presume **you are integrating the jquery.mb.YTPlayer.src.js** loacated in the "src" folder instead of the **jquery.mb.YTPlayer.js** or the **jquery.mb.YTPlayer.min.js** located in the "dist" folder.
The plugin works with all the versions of jQuery.

**Comment by arturmamedov** [comment]
No I use one from dist, maybe is bacause I use jquery compiled with webpack

**Comment by pupunzi** [comment]
@arturmamedov What errors are you receiving in the console?

**Comment by arturmamedov** [comment]
@pupunzi Uncaught TypeError: jQuery.normalizeCss is not a function

**Comment by pupunzi** [comment]
the jQuery.normalizeCss is at line 2947 in the jquery.mb.CSSAnimate.min.js minified block

**Comment by arturmamedov** [comment]
Now i see only the console log `YTPlayerInit_abHc9taTsdk: 4ms – timer terminato`

**Comment by pupunzi** [comment]
This is not an error...

The player is working
You probably are trying to autoplay with the sound active...
Do you have an URL where I can see what is going on?

**Comment by arturmamedov** [comment]
@pupunzi thank u! 
https://www.campingadriatico.net/en/where

**Comment by arturmamedov** [comment]
I found now that is conflicting with a myne requireJS module ... maybe cause in this module i have another import of jQuery
