### ISSUE TITLE
mobileFallbackImage suggestion

### ISSUE THREAD

**Issue by tigerste** [pupunzi/jquery.mb.YTPlayer#272]
Thanks for the great plugin!

Currently a mobile fallback image will only be applied if the 'containment' attribute is set to 'body'.

I note that several people have raised issues about expected behaviour with containment set to 'self', i.e. that a background image is applied to the player container - currently the whole element is removed, which is problematic if the element in question contains content e.g. a series of paragraphs.

If you remove line 353 from your code ('$YTPlayer.remove();'), the element renders on mobile, with its children and the fallback image, and still works as before on 'body' - perfect!

Would you consider updating the plugin with this?

**Comment by pupunzi** [comment]
Hi,
the code should not remove the player if it is initialized as "self":

Line 353
```
    if( !YTPlayer.isPlayer )
            $YTPlayer.remove();
```
It removes it only if the target is different from the element that is initializing it.

Do you have a page where I can see what is the behavior you have?

**Comment by tigerste** [comment]
https://codepen.io/anon/pen/xrBwyp

Have tested on iPhone 6S (iOS10) with both Safari and Chrome browsers, no background image is rendered and the paragraphs are lost.

**Comment by pupunzi** [comment]
@tigerste 
I was sure it was working :-)

For the pause feature, the most uses this plugin as background of the entire page and in that case it's never out of view.

I'll think about introducing it in the case of background for dom element.

All the best,
Matteo

**Comment by tigerste** [comment]
Background video is very common now on a container element, and often combined with a parallax effect - I'll put in a pull request when I find some time!
