### ISSUE TITLE
Using Variables for Parameters

### ISSUE THREAD

**Issue by effectivemedia** [pupunzi/jquery.mb.YTPlayer#273]
Hi,
This plugin is amazing! 

2 quick questions 
- I have the YouTube ID attributed to a variable so the user can change it on the CMS. Is there a way to assign the variable to the videoURL (for example - videoURL:$YouTubeID didnt work)?
- How would I make sure the video always fills the entire containing element? I do not want the black bars at large screen sizes? Cropping/hiding the extra width is acceptable.

Thanks!

**Comment by effectivemedia** [comment]
Also, showYTLogo:false is not removing the logo on pause

http://absoluteearth.youreffectivemedia.com

Thanks

**Comment by effectivemedia** [comment]
Be advised that the YouTube logo is hidden by the stylistic element under the video on larger screen sizes.

The black bar seems to have disappeared somehow, though I suspect it's hidden by the elements under the video.

Thank you

**Comment by effectivemedia** [comment]
Got it - videoURL:'http://youtu.be/<?php echo $YTID; ?>' (yes - I'm using PHP).

So that's 2 seemingly down (Although I don't trust that the black bar was really taken care of).

I just need the YouTube Logo gone. (I saw it using Chrome dev tools with screen width set to 1400px).

Thanks

**Comment by effectivemedia** [comment]
Hmm.. didnt add the php last comment.

`videoURL:'http://youtu.be/<?php echo $YTID; ?>'`

**Comment by pupunzi** [comment]
Hi,
Do you have an URL where I can see the issue?

**Comment by effectivemedia** [comment]
http://aenaturals.com/

Also, it seems that it's stalling, so the actual video does not start until a while after the page is loaded. I do not know if this is on Google's end, a result of the plugin or related to other code on the site. See attached screenshot.

I do not expect you to troubleshoot my whole site of course. I would just like to know if this is related to the plugin.

Thanks very much.
![aenaturals_screenshot_youtube_network](https://user-images.githubusercontent.com/20324690/28431543-afd13da2-6d52-11e7-88a1-b0d7d7bb5454.jpg)

**Comment by pupunzi** [comment]
Hi,
1. The starting time is the time the Youtube API takes to buffer the first playable fragment.
2. The youtube logo appears because of the aspect ratio of your container; you could try changing the "anchor" option from "center, center" to "top, center":

`anchor: "top,center"`

This should anchor the video to the top leaving the YT logo under the visible area.


All the best,
Matteo

**Comment by effectivemedia** [comment]
So basically the delay is caused by Google/YouTube and not a result of the plugin, is this correct?

Also, changing the anchor settings didn't seem to work. See screenshot.
![aenaturals_screenshot_youtube_logo](https://user-images.githubusercontent.com/20324690/28433945-9fcab592-6d5b-11e7-9c60-68f2e9c7d625.jpg)
