### ISSUE TITLE
No Autoplay

### ISSUE THREAD

**Issue by DaveNewWorld** [pupunzi/jquery.mb.YTPlayer#276]
Hi

My video will not autoplay when using mobile devices, yet works fine through a windows browser.  The video is muted, which I understand is required to get past ios and android rules.  Is there anything else I need to be mindful of?

Thanks
Dave

**Comment by RatFou** [comment]
+1

**Comment by pupunzi** [comment]
@DaveNewWorld Do you have an URL where I can see the issue?
On mobile devices the video should start once the user touch the screen...
