### ISSUE TITLE
YTPLayer Full Screen Not working in IE/Edge

### ISSUE THREAD

**Issue by timawork** [pupunzi/jquery.mb.YTPlayer#277]
Hi! YTPlayer is amazing! But Full Screen not working on IE & Edge. Does anyone have a solution to fix this?

**Comment by pupunzi** [comment]
This issue should be fixed on the latest release

**Comment by wyoikawa** [comment]
Hey, 
i've got fullscreen working on Edge but it didn't work on IE 11. Is this fixed?
