### ISSUE TITLE
Multiple Videos.

### ISSUE THREAD

**Issue by BenjamintGibbs** [pupunzi/jquery.mb.YTPlayer#278]
Hi,

I want an array of videos that each fit a container. A container that I have given an 'id'. Cant get it to work though. This error comes up...

jquery.mb.YTPlayer.js:642 Uncaught TypeError: Cannot set property 'isPlayList' of undefined
    at r.fn.init.playlist [as YTPlaylist] (jquery.mb.YTPlayer.js:642)
    at main.js:660

Here's my code: 

var videos = [
            {videoURL:"https://www.youtube.com/watch?v=beyU9Sfi1j8",containment:'#leng',autoPlay:true, mute:false, startAt:0,opacity:1, loop:false, ratio:"4/3", addRaster:true},
            {videoURL: "https://www.youtube.com/watch?v=beyU9Sfi1j8",containment:'#mind',autoPlay:true, mute:true, startAt:0,opacity:1, loop:false, ratio:"4/3", addRaster:false},
        ];

 jQuery("bgndVideo").YTPlaylist(videos, false);

**Comment by pupunzi** [comment]
Hi,
the error is in the selector you are pointing to. jQuery uses the CSS syntax so the correct way is:

`jQuery("#bgndVideo").YTPlaylist(videos, false);`

All the best,
Matteo

**Comment by BenjamintGibbs** [comment]
The error is still comes up? 
var videos = [
            {videoURL:"https://www.youtube.com/watch?v=beyU9Sfi1j8",containment:'#leng',autoPlay:true, mute:false, startAt:0,opacity:1, loop:false, ratio:"4/3", addRaster:true},
            {videoURL: "https://www.youtube.com/watch?v=beyU9Sfi1j8",containment:'#mind',autoPlay:true, mute:true, startAt:0,opacity:1, loop:false, ratio:"4/3", addRaster:false},
        ];


 jQuery("#bgndVideo").YTPlaylist(videos, false);

Is that all the code I need?

**Comment by BenjamintGibbs** [comment]
I'm trying to have a video for each item in my 'work' section. This is my site live: http://benjaminthomasgibbs.co.uk/

**Comment by pupunzi** [comment]
Hi, 
in your page (http://benjaminthomasgibbs.co.uk/main.html) I can't see any element with the "bgndVideo" id. 
Using the playList method is not the correct way to add a background video the the different elements. Just set the video properties directly on each element you want the video as background as for example:

`<div class="work-slate-mind-video" id="mind" data-property="{videoURL:'beyU9Sfi1j8',containment:'#mind', showControls:false, autoPlay:true, loop:true, vol:50, mute:false, startAt:10,ratio:16/9, stopAt:150, opacity:1, addRaster:true, quality:'hd720', optimizeDisplay:true}>...</div>`

Hope this helps you,
All the best,
Matteo

**Comment by BenjamintGibbs** [comment]
Do I use this JS call?
      jQuery(function(){
      jQuery("#P1").YTPlayer();
    });

??

**Comment by BenjamintGibbs** [comment]
I've added the method you said above to my page, neither videos will load though :(. I must be doing something stupid, so sorry.
live: http://benjaminthomasgibbs.co.uk/main.html#
