### ISSUE TITLE
Video centered only by setting abundance to 0?

### ISSUE THREAD

**Issue by svencreations** [pupunzi/jquery.mb.YTPlayer#281]
I tried to set a youtube video as background of an element. the video is not centered.

When i replaced the following line

`win.height = el.outerHeight() + abundance;
`

with

`win.height = el.outerHeight();
`
The video is centered. Why is it abundance set to 180? What is it actually? Can somebody explain this please?

Thank you

Cheers,
Sven.

**Comment by pupunzi** [comment]
Hi,
the abundance variable is used to grow the video window to make the Youtube logo on the bottom right outside the visible area.
That should not cause the issue as it is calculated... do you have some additional CSS that could cause the issue?

**Comment by svencreations** [comment]
Hi,

Thanks for the response.

**Comment by pupunzi** [comment]
There's an option to define which is the anchor for the video:

`anchor: "center,center", // top,bottom,left,right combined in pair`

**Comment by AM-R** [comment]
anchor: 'center,center'
Is not working for me... And video is not property displayed, it's seems like video content is bigger then video player window... and at bottom of window is not enought place to show the video content.

**Comment by pupunzi** [comment]
The video is resized to cover all the containment area. If you need to show all the video and you don't need to optimize the size to cover the area then you can set the 'optimizeDisplay' property to 'false'; that way the video will have the default behavior but you'll have black stripes top/bottom or left/right depending to the different ratio between the containment and the video ratio.

**Comment by AM-R** [comment]
"optimizeDisplay: false," it's working for me! Big thanks for your work and answer!

**Comment by siberianbear** [comment]
Hello.
How to check of optimizeDisplay-trigger is actually works?
By some reason it does not work for me.
