### ISSUE TITLE
YTPlayer not working on Linux (ElementaryOS 0.4.1 Loki)

### ISSUE THREAD

**Issue by rSSi** [pupunzi/jquery.mb.YTPlayer#282]
On my Laptop with elementary OS 0.4.1 Loki (Built on "Ubuntu 16.04.2 LTS") using Firefox or Chromium your demo pages don't work.

`TypeError: /Android ([\.\_\d]+)/.exec(...) is null  jquery.mb.YTPlayer.js:2078:12`

`getOS https://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js:2078:12
<anonymous> https://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js:2078:209`

and:

`jQuery.Deferred exception: $.mbCookie is undefined @https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html:261:7

j@https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:29586

g/</k<@https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:29902
 undefined  jquery.min.js:2:31155`

Let me know if i can provide more information!

**Comment by pupunzi** [comment]
Hi,
do you have an URL where I can check the issue?

It seams the blocking error is on the OS detection method but the regular expression you have on the first error (TypeError: /Android ([\.\_\d]+)/.exec(...) is null)  doesn't exist on the jquery.mb.YTPlayer.js file...

**Comment by rSSi** [comment]
it's your demo page:
https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html

i started playing with your wonderfull player on my windows machine but found out whgen i wanted work on my linux laptop that wouldn't work.
my basic implementation does work:
http://geraldrossbacher.com/index_new.php
![youtube chromeless player - mb ytplayer - mozilla firefox_001](https://user-images.githubusercontent.com/858198/29486181-87384f02-84e0-11e7-90d3-adec5f5a68fa.png)

**Comment by pupunzi** [comment]
What version of the script are you using?
Did you try with the last version (3.0.20)?

**Comment by rSSi** [comment]
Sorry for the late reply!
Yes, it is and has been 3.0.20

**Comment by pupunzi** [comment]
I just made some test emulating the Linux User Agent (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1636.0 Safari/537.36) but it is still working fine for me... The regular expression in the error you post is not used by the script and I'm not able to reproduce the issue.

**Comment by rSSi** [comment]
Ok. Just checked to see what happens if i change the user agent and it works perfectly...
have to find out what is causing trouble. as i said, on my page it it working, it's on the demo page where it doesen't.
thank's for looking into it. will let you know what i can find out!

**Comment by pupunzi** [comment]
The online demo has not been updated to the latest script, that's why you have the error. :-)

**Comment by rSSi** [comment]
Thanks for lookin into this issue so quick! :)
