### ISSUE TITLE
Youtube control is visible on init

### ISSUE THREAD

**Issue by emilium** [pupunzi/jquery.mb.YTPlayer#284]
Hi all,

On init I got two controls on the background video - one from the lib and one from youtube. Any idea how to remove youtube control?

Here is the code:
` 
var dataProperty = "{videoURL:'" + that.get_videoID() + "', containment:'#" + $(that._element).attr('id') + "', autoPlay:false, mute:false, startAt: 0, opacity:1, showControls:true, loop:false}";
`

And here is the screenshot:
https://ibb.co/hUiYbk

Example:
https://codepen.io/emilium/pen/xLQvPr

**Comment by pupunzi** [comment]
Do you have an URL where I can check for your issue?

**Comment by emilium** [comment]
Here is a codepen example: https://codepen.io/emilium/pen/xLQvPr

**Comment by pupunzi** [comment]
Just tested your codepen test page and it's working fine for me.
What OS and what browser are you testing with?

**Comment by emilium** [comment]
On Windows 10, Chrome and Firefox. Sometimes if I change the startAt to 3 then the control is gone. Right now I'm testing on OSX, Chrome and the issue is still there. Here is a screenshot: https://ibb.co/d910NQ

**Comment by pupunzi** [comment]
If you set the containment to "self" the ply button will not be visible.
I'll check why that happens.
