### ISSUE TITLE
Remove Suggested Videos

### ISSUE THREAD

**Issue by willgeggy** [pupunzi/jquery.mb.YTPlayer#285]
How to you prevent YouTube from placing suggested videos after your video is done playing? I do not want anything to come up after my video is done playing. I would like the replay button to stay up or just a blank screen. anything but other peoples videos. Hopefully the picture helps explain what i am talking about.
![image](https://user-images.githubusercontent.com/31517142/29936130-b19ee8d6-8e46-11e7-99a7-3b154e792518.png)

**Comment by pupunzi** [comment]
Do you have an URL where I can see the issue?

**Comment by willgeggy** [comment]
![image](https://user-images.githubusercontent.com/31517142/30069771-353fc866-9227-11e7-87ad-792eb9b1b0d7.png)

here is the url to my site. obviously it is not finished at all but am publishing so you can see the issue.
geggmedia.com

click on portfolio and it will take you to the place i am talking about. the working youtube video is in the first box. the only image that isnt 600x410. it says STLCM. that video will play and then put up suggested or related videos. i would like these things not to come up after the youtube video has played. hopefully this makes sense. thanks for your help!

**Comment by pupunzi** [comment]
Hi,
you're using a really old version of the plug-in (2.6.0) and it has an error. 
You should update to the latest stable version 3.0.20 from here: https://github.com/pupunzi/jquery.mb.YTPlayer/archive/3.0.20.zip
