### ISSUE TITLE
Self-hosted videos

### ISSUE THREAD

**Issue by golyalpha** [pupunzi/jquery.mb.YTPlayer#286]
Hey, I'd like to use this player to play videos that I self-host, rather than videos up on YT. Is that a planned feature here, or is there a way I can structure my URL for example so the videos work with the plugin?

**Comment by pupunzi** [comment]
Hi,
this player works only with videos on the Youtube cloud service as it's using the Youtube javascript API to control it.

At the time I've not planned to make it for self hosted videos because I think that is better to use services as Youtube or Vimeo that have dedicated server to stream and optimize the band-with that any other self hosted solution can compete with.

All the best,
Matteo

**Comment by golyalpha** [comment]
What are you using the YT API for, if I may ask?

**Comment by pupunzi** [comment]
The YTPlayer plays video hosted on Youtube. Youtube expose its API to let it possible to include any public video inside a website page and control it (play, pause, seekto, etc.).

Without the API you couldn't have control of the video in your page using javascript.

**Comment by golyalpha** [comment]
That's actually natively in HTML5 video tag, JS video controls that is.

**Comment by pupunzi** [comment]
If you've a self hosted video you can use the native HTML5 javascript API but not if the video is streamed from Youtube

**Comment by golyalpha** [comment]
Yes, when I asked what you are using the YT API for, I meant, what are you using it for that can't be done without it, provided you use a self-hosted solution.

**Comment by pupunzi** [comment]
A self hosted video means you should have a dedicated stream server, a huge support for bandwidth, different videos for different browsers (mp4 and webm) and anyway you'll never be able to optimize the video for the different connections as Youtube or Vimeo can do.

If you embed a video from Youtube you need its API to control it and you can't use the same controls for the self hosted video.

**Comment by golyalpha** [comment]
Hey, I mean, getting AWS CloudFront is not *that* hard... Add Elastic Beanstalk to the mix and you have a server that will do the transcode and downscale.

My point is, from what you are saying, all that is required is a little compatibility layer between your player and the HTML5 JSAPI.

**Comment by pupunzi** [comment]
For most of the people is much more easyer to upload a video on Youtube or Vimeo then configure AWS CloudFront. Making a plug-in for a self hosted video would mean give a lot of support. 

Anyway It would be much easyer to start coding from scratch then to create a compatibility layer between the YTPlayer methods and the native HTML5 methods.

**Comment by golyalpha** [comment]
For most of the people, it is much easier to use the YT embed, rather than finding their own player and fiddling with the JS.

**Comment by pupunzi** [comment]
That if they don't need to play it as background

**Comment by golyalpha** [comment]
I am pretty sure I've been talking about using it as a player, not as a background. If someone uses your player to play a video in the bg of his website, I wouldn't say that writing a compat between your player and HTML5 JSAPI isn't out of their league either - not to imply that the player is hard to use, if it was, we wouldn't be having this conversation in the first place.
