### ISSUE TITLE
Video not working on github pages

### ISSUE THREAD

**Issue by madlyn** [pupunzi/jquery.mb.YTPlayer#287]
I integrated your code into my test website, it's working locally but not when I push it to github pages
https://madlyn.github.io/PhotoPhactory/videos.html

**Comment by pupunzi** [comment]
You're including various css and javascript over HTTP while github runs over HTTPS.
Change the URL using HTTPS and it should work.

**Comment by hoanghog** [comment]
Thanks mate, had same problem, changing http -> https works perfectly fine for me :)

**Comment by User2004** [comment]
https://webappcodes.com/play-video-from-url-in-swift

Above link is use for play video from url

**Comment by meedox9** [comment]
I have a video playing as a background for a section. Here is the css:
```
#example {
  background: url("../../videos/example.mp4");
  background-size: contain;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: left;
}
```
The video works locally but not on GitHub pages. Any suggestions??
