### ISSUE TITLE
Multiple Players

### ISSUE THREAD

**Issue by effectivemedia** [pupunzi/jquery.mb.YTPlayer#288]
Hi,

how would I manage IDs and the Jquery to have multiple players on the same page? 

If the JS call 
`jQuery(function(){
      jQuery("#[playerID]").YTPlayer();
    });`
Uses the ID do I need to call the JS multiple times? Is there a more efficient way?

Thanks

**Comment by pupunzi** [comment]
Hi,
you can add a classname to all the players you need to initialise and use that classname:

jQuery(
   function(){ 
      jQuery(".[playerClassname]").YTPlayer(); 
   }
);
