### ISSUE TITLE
it's a mistake or I'm stupid?

### ISSUE THREAD

**Issue by VeX78rus** [pupunzi/jquery.mb.YTPlayer#291]
js created "mbYTP_wrapper" class
css have "YTPWrapper" class
What it is?

**Comment by VeX78rus** [comment]
I would not have asked, because it works, but if I change class, it runs a bit smoothly

**Comment by VeX78rus** [comment]
ifs forum dead?

**Comment by pupunzi** [comment]
Hi,
It's a CSS mistake. change the CSS class from  YTPWrapper to mbYTP_wrapper. I'll fix it on the next update.

**Comment by VeX78rus** [comment]
оо Thank you! pros also make mistakes :)

**Comment by pupunzi** [comment]
:-D
