### ISSUE TITLE
Enable inline playback for background videos on iOS Safari

### ISSUE THREAD

**Issue by ThatGuySam** [pupunzi/jquery.mb.YTPlayer#292]
Youtube now allows inline playback on iOS 10 via url parameter

https://developers.google.com/youtube/player_parameters#playsinline

How can I get that parameter added to the embed url?

Example: https://www.youtube.com/embed/zt7NJeEO6Ig?playsinline=1

**Comment by pupunzi** [comment]
Hi @ThatGuySam,
I'm implementing that feature on the plug-in; if you download the master version it already plays on mobile devices: https://github.com/pupunzi/jquery.mb.YTPlayer/archive/master.zip

Soon available with the next public release.
