### ISSUE TITLE
Video poster appearing in low resolution, but video plays as high resolution

### ISSUE THREAD

**Issue by T-Fletcher** [pupunzi/jquery.mb.YTPlayer#293]
Hi 

I'm using a 1080p video background from Youtube, which plays fine.

However, the background poster image displayed while the video loads shows as 360p, making the video look shabby. 

I'm using these data-properties:

```
<div id="P1" class="player homepage-feature-video mb_YTPlayer" data-property="{
     videoURL:'http://youtu.be/foo',
     containment:'self',
     mute:false,
     autoPlay:false,
     loop:false,
     stopMovieOnBlur:false,
     realfullscreen:true
}"
```

When I tried adding any of the `quality` options (`‘default’ or ‘small’, ‘medium’, ‘large’, ‘hd720’, ‘hd1080’, ‘highres’`), JS throws an error complaining the chosen value is undefined. 

The `<iframe>` tag inserted by the script is only loading at 360p also. Not sure why this is when the video plays as a higher resolution. 

Any ideas how to get the background image to load at the same resolution as the video plays?

Thanks!

**Comment by pupunzi** [comment]
Hi,
that is a bug.
you can fix it by replacing "hqdefault.jpg" with "maxresdefault.jpg" at line 676.
Doing that you get the highest resolution thumbnail from Youtube.

All the best,
Matteo

**Comment by T-Fletcher** [comment]
Thanks @pupunzi, that did the trick!
