### ISSUE TITLE
The video seems choppy on firefox

### ISSUE THREAD

**Issue by beany-vu** [pupunzi/jquery.mb.YTPlayer#295]
I think the player is really good on chrome/safari. However, it seems to be laggy on firefox. It's likely the video is played with 5-10fps (the number is higher on Chrome). I couldn't find any suspected issues on the javascript side. I think the problem comes from the encoder system of Firefox.  Any ideas for this issue?

**Comment by pupunzi** [comment]
Hi,
What version of FF? on which OS?
I'm testing it on FF 56.0 (64 bit) on a mac OSX 10.12.6 and it works fine for me...

**Comment by beany-vu** [comment]
Hi, I found the firefox will be lagged if we keep playing video for a while (didn't see on chrome for now). Finally, I set the config to pause when losing focus. It seemed to be good. (y)
