### ISSUE TITLE
Error iniziating video in mobile mode chrome

### ISSUE THREAD

**Issue by dbagnai** [pupunzi/jquery.mb.YTPlayer#296]
Hi,
i'm debugging new relaease  3.1.1 on chrome settign visualiztion in mobile mode iphone,
but the video not start and try to start with playvideo it says

VM970 jquery.mb.YTPlayer.js:354 Uncaught TypeError: Cannot read property 'playVideo' of undefined
    at HTMLBodyElement.<anonymous> (VM970 jquery.mb.YTPlayer.js:354)
    at HTMLBodyElement.e (VM969 jquery.min.js:3)
    at HTMLBodyElement.dispatch (VM969 jquery.min.js:3)
    at HTMLBodyElement.r.handle (VM969 jquery.min.js:3)

Why?

**Comment by pupunzi** [comment]
Hi,
you have to test on a real mobile as the script check for the 'playsInline' property that the Chrome emulator return "false".

If you want to see it on the Chrome emulator then you need to change line 219 
from:

`YTPlayer.canPlayOnMobile = jQuery.mbBrowser.mobile && ( 'playsInline' in document.createElement( 'video' ) );
`
to:

`YTPlayer.canPlayOnMobile = true;
`
But remember to roll back after your test

**Comment by dbagnai** [comment]
What happens if i left
YTPlayer.canPlayOnMobile = true;

not doing rollback on precedent line?
ᐧ

2017-10-03 11:28 GMT+02:00 mb.jquery.components <notifications@github.com>:

**Comment by pupunzi** [comment]
Not all mobiles can play online videos. If you don't roll back it could happen that for someone who's using an old mobile the page will throw an error.
