### ISSUE TITLE
Problem with volume and play after stop

### ISSUE THREAD

**Issue by dbagnai** [pupunzi/jquery.mb.YTPlayer#298]
Hi,
there a problem with togglevolume, not working.

And at the end of video after it ends, if i press play again i can head only audio and video not is visible
( only if i change focus out of browser and after i click again on browser windwws the video become visible)!

SAMPLE
http://testsite29.weapps.eu/examples/demo_multiple_videosMod.html

**Comment by pupunzi** [comment]
That is due to the use of a wrong method for the play button:

Use:

`jQuery('#vidContainer').YTPPlay()`

Instead of:

`jQuery('#vidContainer').YTPGetPlayer().playVideo()`
