### ISSUE TITLE
Not working out-the-box with React

### ISSUE THREAD

**Issue by ralexandr** [pupunzi/jquery.mb.YTPlayer#299]
Is there any plans to make your plugin reactjs-friendly?
It will be amazing if you will help me to create react component based on your plugin, because It doesn't work out-the-box (no errors, video just not loading and player return 'undefined')
Also, could you please provide the ability to set custom controls (play/pause/mute/unmute icons or even the whole progress-bar).

**Comment by pupunzi** [comment]
Hi,
I never used reactjs library so I don't know how to implement my script with it...

For the controls the plug-in expose all the methods to let you build your own custom on the page; you can see the documentation here: https://github.com/pupunzi/jquery.mb.YTPlayer/wiki
