### ISSUE TITLE
Video position fixed in container

### ISSUE THREAD

**Issue by pseudonymus** [pupunzi/jquery.mb.YTPlayer#30]
Hey,

Awesome plugin.
I have a question: is it possible to make the video fixed inside a container, while scrolling the container? I'm using the plugin to generate YouTube video backgrounds for different page sections with content and want to make the videos fixed. When it comes to images, <code>background-attachment: fixed;</code> works great, but on this case, it looks like it`s a bit more complicated.

Regards!

**Comment by artie-groove** [comment]
So, is there a solution? How can I make the video fixed inside a HTML element area?
