### ISSUE TITLE
http://gdata.youtube.com/feeds/api/videos/

### ISSUE THREAD

**Issue by raiz0x** [pupunzi/jquery.mb.YTPlayer#300]
ERROR 1 FROM THIS `gdata` line 488 ytb.js jQuery.getJSON(
`No longer available`

ERROR 2
GET https://googleads.g.doubleclick.net/pagead/ads?sdkv=h.3.0.0&sdki=18803d85&video_product_type=5&correlator=4313141582704165&client=ca-pub-6219811747049371&url=https%3A%2F%2Fwww.youtube.com%2Fembed%2F-TiATtsyb08%3Fautoplay%3D0%26modestbranding%3D1%26controls%3D0%26showinfo%3D0%26rel%3D0%26enablejsapi%3D1%26version%3D3%26playerapiid%3DmbYTP_bgndVideo%26origin%3D*%26allowfullscreen%3Dtrue%26wmode%3Dtransparent%26iv_load_policy%3D3%26html5%3D1%26widgetid%3D1&adk=1830969481&num_ads=1&channel=Vertical_1408%2BVertical_211%2BVertical_3%2BVertical_35%2BVertical_36%2BVertical_588%2BVertical_613%2Bafv_overlay%2Bafv_ugc%2Bafv_user_id_65afEgL62PGFWXY7n6CUbA%2Bafv_user_officialtrapcity%2Binvideo_overlay_480x70_cat10%2Byt_bs2%2Byt_cid_319133%2Byt_mpvid_8y6GCn3s4knf0iZH%2Byt_no_ap%2Byt_no_cp%2Byt_no_wa%2Bytdevice_56%2Bytdevicever_20171018%2Bytel_embedded%2Bytps_default&output=xml_vast3&sz=1694x769&host=ca-host-pub-1800120140230655&ht_id=389658&hl=ro&cust_age=1001&cust_gender=1&pucrd=CggIABAAGAM4AQ&ea=0&image_size=450x50%2C468x60%2C480x70%2C728x90&ad_type=text_image&eid=168298150&u_tz=180&u_his=1&u_java=false&u_h=768&u_w=1366&u_ah=728&u_aw=1366&u_cd=24&u_nplug=4&u_nmime=5&dt=1508439576031&unviewed_position_start=1&videoad_start_delay=0&osd=2&frm=2&sdr=1&t_pyv=exclude&min_ad_duration=0&max_ad_duration=110000&ca_type=image&video_doc_id=yt_-TiATtsyb08&description_url=http%3A%2F%2Fwww.youtube.com%2Fvideo%2F-TiATtsyb08&lact=1049&loeid=9422596%2C9474595%2C9488991%2C23702700%2C23703154%2C23703286%2C23705778&lsv=false&yt_pt=APb3F2-uMUSIFbUyH3h4uq2jdEfsntlz3i8QoC5GzP7r7yjCk2yDvzGUl6wC9ARLyhhgo2lIlbQJqnvfmO9Ii-U19hXpqGYlalry3ll4kZzIZ_hOsDFSm-BqxcPDbRV2aXnfxCy2SVEg9LT51kTt2jsqXjrj-1uGNnuzalUE6FScGpuy-AaXMFfuWSANoLzoSCtPErBcXXYJvFR2i2nkE2f-EUk7wN6VVL7HDmMOXK3z-_XlsZsFVzsqLHQof3zXwVObr95oKBCEu-XvbZ7l575spAPPCsfJyjTn8ZiyW0mT59PgBYzAu7QVvJ1pMH402H0KmOPXmfU6DNrSqoeuYr0aiaSjTxzGG0uOSpiA9tkUWBWevNa_NZq1AmE8eKQGYsJ2Jn3wQ7-mgXFXXobE6_ngyA5cwWv2cj9WotwAm1YUirHT9zmSIVzk7OLS4tni-SDR_nkQOSwfzzI81zsHaHiKpArD9DBdqPPeY1D5hs6488leeBtx3bg_1OZWyTUlwUFIeRFSI5u_lJrQCs0bCo12umZoo5S0lQfr7o5dVJwTtY1I2CtltvmurYRImJBqHMag7Ag5VKqGVeQF8KI6CqcdWSBfJCFj9mUjBeOPR-MPhKTbGQlSc8NW0xX2Cnz-JFE9sTFfwZozrTeWhz0PBjEKbzeCngim17FpsqmOluqxismLXz82xIge7xWpq0qqIzzUAHrZEaDtWntyw4XDYpCoWV4vAR1tA2y4HsN420i_Yle_53qXD-X16YihzybjMCtvxF_hf03sfzjKXzVj&ytdevice=56&ytdevicever=20171018&yt_vis=0&dbp=ChZSSkV6Y3NkdVBxTG5KazYzc3ZfZjVnEAEgASgA&avo=AF-6KjKwSttODa_ZxULLWvR2snS_TK71xkf-lyUFIbsso7c6yFDJlFf-PVORByLfp-y2Wrsf9Ky6sIdHQRyX3mRAOYW7uLdWvw&v_p=DQ5zOD8lw1tbRA%3D%3D 400 ()

**Comment by pupunzi** [comment]
Hi,

http://gdata.youtube.com/feeds/api/videos/  is not called by the mb.YTPlayer plug-in
