### ISSUE TITLE
Problem with background image with autoplay false

### ISSUE THREAD

**Issue by dbagnai** [pupunzi/jquery.mb.YTPlayer#301]
I'm using YTPlayer 3.1.1 Master Ver

I have set video as background in  a div , like:

```
> <div id="myid" class="bckvideostyle"  mybind="Id" 
>      style="background: url('urlimage') no-repeat center center; background-size: cover"
>      data-property="{videoURL:'videolink',containment:'self', showControls: false, autoPlay:false, loop: false, mute: false, startAt:0, opacity:1,vol:50, addRaster:false, quality:'default'}"></div>
```

I set my background url image ( substituting urlimage before player initialize )
but when i initialize the player    var myPlayer = jQuery("#myid").YTPlayer(); my urlimage is replaced by  this:

background: url("https://i.ytimg.com/vi/ck3Kc48wZ40?rel=0/maxresdefault.jpg") center center / cover rgba(0, 0, 0, 0.5);

i can avoid this behaviour ?

**Comment by pupunzi** [comment]
Hi,
That happens because you're initialising the player in the same containment you defined the mb.YTPlayer element. To avoid the background image replacement you should separate the YTPlayer container from the div that describe it:

```
<div id="myid" class="bckvideostyle"  mybind="Id"  style="background: url('urlimage') no-repeat center center; background-size: cover"></div>

<div id="myYTPlayer" data-property="{videoURL:'videolink',containment:'#myid', showControls: false, autoPlay:false, loop: false, mute: false, startAt:0, opacity:1,vol:50, addRaster:false, quality:'default'}"></div>
```
and initialise the #myYTPlayer element: 

```
var myPlayer = jQuery("#myYTPlayer").YTPlayer();`
```
All the best,
Matteo
