### ISSUE TITLE
Mute not working!

### ISSUE THREAD

**Issue by AlbanBujupaj** [pupunzi/jquery.mb.YTPlayer#302]
Hi, I am trying to mute the video I don't know why is not working.

Im trying like this: ` <div id="bgndVideo" class="player" data-property="{videoURL:'http://youtu.be/4RUGmBxe65U',containment:'.container', autoPlay:true, mute:true, startAt:0, opacity:1, showControls: false}"></div>`

javascript :

`$("#bgndVideo").YTPlayer(); `

**Comment by pupunzi** [comment]
Do you have an URL where I can see your issue?

**Comment by AlbanBujupaj** [comment]
Yes: 
http://searangers.sprigslab.com

**Comment by pupunzi** [comment]
You're using the jquery.mb.YTPlayer.js 3.1.1 that has a bug. Just update to the 3.1.2 and it should work.
