### ISSUE TITLE
Android webview

### ISSUE THREAD

**Issue by westonnh** [pupunzi/jquery.mb.YTPlayer#303]
Ran into an issue where the latest mobile code is not working on mobile responsive sites.  In desktop view (Request desktop site) the feature works as expected.  In normal mobile responsive on Android-powered devises, however, the video fails to load.

**Comment by pupunzi** [comment]
Hi,
I tested the background video on both iPhone and Android (Samsung) mobile and it works on both as aspected. Which Android are you testing with? do you have an URL where I can test the issue?

**Comment by westonnh** [comment]
Hello,

works when I toggle 'request desktop site' on chrome but not the default mobile view. 

Nexus 6P phone
Nexus 7 tablet
Samsung S8 phone
Samsung Galaxy Tab2

https://lab.hawtcreative.com/vid.html

By the way thanks for such a wonderful tool.

**Comment by matueszwin** [comment]
I cannot make It works on mobiles as well, even on your demo pages It doesn't work. I was looking on this one https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html

**Comment by pupunzi** [comment]
@matueszwin : 
What device are you testing with?
Just made some tests with both iOs (iPhone 5s) and Android and it is working fine for me.
