### ISSUE TITLE
Showing current video infos in http 

### ISSUE THREAD

**Issue by antonyadam** [pupunzi/jquery.mb.YTPlayer#304]
Hello Matteo

I rage I love your plugin :-)  I wanted to complete the installation by adding the infos of the video but it does not work I am in http and I have this error

www-widgetapi.js:121 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://.........
I have looked here and there and seen some tricks but I am a beginner and I have trouble applying the methods views....

Its possible or not with http ?
Thanks 
Best regards

**Comment by pupunzi** [comment]
Hi,
the error you are getting is not blocking and should not compromise the correct behavior of the player. You can use both HTTP and HTTPS protocol and it should work.
Do you have an URL where I can test your issue?

**Comment by antonyadam** [comment]
Hello 
Thank you for the quick reply
[Here](http://antonyadam.1fr1.net/)
sometimes the error does not appear in the console must refresh the page..
Thank you

**Comment by pupunzi** [comment]
As previously told you that error doesn't compromise the correct behavior of the player; it is a known issue on Youtube side. 

If you want to retrive the video info from the API you should provide an API key as explained here:
https://github.com/pupunzi/jquery.mb.YTPlayer/wiki#ytpdata-event

As I can see from the source of your page you are initializing the YTPlayer several times:

- one time as jQuery(".movie").mb_YTPlayer()
-  two times as jQuery('#bgndVideo').YTPlayer(...)

That should not be done.

All the best,
Matteo

**Comment by antonyadam** [comment]
hello 
L'API key is on page...
  <script src=https://sd-1.archive-host.com/membres/up/37821634957680146/ytkey.js></script>
I will look to initialize the YT  player just one time ..

**Comment by pupunzi** [comment]
If you have the API key you're able to get the YTPData. you can do that in several ways:

1. Using the YTPGetVideoData method after the player has been initialized:

```
function logVideoData(){
    var videoData = jQuery("#bgVideo").YTPGetVideoData();
    console.debug(videoData.id);
    console.debug(videoData.channelTitle);
    console.debug(videoData.title);
    console.debug(videoData.description);
}
```
2. Using the YTPData event that is fired once the player receive the DATA from the API:

```
myPlayer.on("YTPData", function (e) {
            console.debug(e.type);
            console.debug(e.prop.title);
            console.debug(e.prop.description.replace(/\n/g, "<br/>"));
        });
```
3. Getting DATA from the player variable (if defined) after the player has been initialized:

```
var videoData = myPlayer.get(0).videoData
```
You can then printout the data you need on your HTML elements.

**Comment by antonyadam** [comment]
Ahhhhh :+1:   U save my day !

Thank u very much Matteo

thank you for the availability and responsiveness !
Best
