### ISSUE TITLE
Playlist method stopAt doesn't work

### ISSUE THREAD

**Issue by SandHoofd** [pupunzi/jquery.mb.YTPlayer#305]
Hello,

I am using the method jQuery.fn.YTPlaylist(videos, shuffle, callback), but when I give property stopAt to a video, the video won't stop. When I play a single video the video will stop at the StopAt parameter.

**Comment by pupunzi** [comment]
Hi,
Just tested the stopAt property with the YTPlaylist method and it's working fine for me.
It is working also in the demo_videoList_autoChange.html file in the example folder...

Do you have an URL where I can test your issue?
