### ISSUE TITLE
can i initialize more than one video in my page?

### ISSUE THREAD

**Issue by zearadoua** [pupunzi/jquery.mb.YTPlayer#306]
hi! i have a blog and i want to initialize more than one video on my blog card, but it doe's not work only the first one who work.
`$('.blog-card__video').each(function(i){
          var videoId = $(this).data('ytid');
          $(this).attr('id', videoId);

          $(this).data('property', {
            containment : "self",
            ration  : "auto",
            videoURL  :  videoId,
            autoPlay  : true,
            opacity : 1,
            loop  : true,
            showYTLogo : false,
            showControls  : false,
            showAnnotations : false,
            optimizeDisplay : true,
          });
          $(this).YTPlayer();
        });`
what's missing in this code?

**Comment by pupunzi** [comment]
Hi,
I should see the page where you have the player to check what's going on.
Do you have an URL?

**Comment by zearadoua** [comment]
Hi,
thank you for replying to my issue.
i found a solution, the probléme is: i got the same id generated by drupal and that what caused the problémes, after i make a random function to generate id's the video player is working .

**Comment by pupunzi** [comment]
:-)
