### ISSUE TITLE
YTPAlign[a].trim is not a function     at n.fn.init.jQuery.fn.optimizeDisplay

### ISSUE THREAD

**Issue by jerem555** [pupunzi/jquery.mb.YTPlayer#307]
Hello,

I try to use your plugin in a new magento 1.9.2.4 project but i have this issue on the search console : 

Uncaught TypeError: YTPAlign[a].trim is not a function
    at n.fn.init.jQuery.fn.optimizeDisplay (ytp-min.js:1831)
    at onReady (ytp-min.js:397)
    at K.f.I (www-widgetapi.js:66)
    at W.f.l (www-widgetapi.js:114)
    at W.f.J (www-widgetapi.js:127)
    at S.g (www-widgetapi.js:143)
    at www-widgetapi.js:9
    at g (www-widgetapi.js:95)

What can be the source of conflict in Magento ?

Thanks for your help

**Comment by pupunzi** [comment]
Hi,
what version of the YTPlayer.js are you using?

Do you have an URL where I can check the issue?

**Comment by jerem555** [comment]
Hi,

I am using this version : 

 _ jquery.mb.components                                                                                                                                                                                                                                                                        
 _ file: jquery.mb.YTPlayer.src.js                                                                                                                  _
 _ last modified: 05/01/16 17.43                                                                                                                    _
    
There is no url , i am working on the project in local with Xampp.  Can it be due to order loading of scripts?

**Comment by jerem555** [comment]
Your observation was correct. I  have used your last plugin and now video is launching but stops after 10 seconds.

i have another couples of errors on javascript console : 

www-widgetapi.js:121 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://127.0.0.1').

Uncaught ReferenceError: auto is not defined
    at eval (eval at jQuery.fn.optimizeDisplay (ytp-min.js:2031), <anonymous>:1:1)
    at jQuery.fn.init.jQuery.fn.optimizeDisplay (ytp-min.js:2031)
    at ytp-min.js:467
    at dispatch (jquery-2.2.4.min.js:3)
    at r.handle (jquery-2.2.4.min.js:3)

**Comment by pupunzi** [comment]
The first (postMessage) is not blocking and is fired from the Youtube API (it's a known bug).
The second one should not happens :-) ... Try setting the ratio to "16/9" or "4/3" instead of "auto".

**Comment by jerem555** [comment]
The second error now has disappeared from the console and the video is launching but stops after 12 seconds whereas the video lasts 1min 30 seconds. It is very strange. thanks for your support ;)

**Comment by pupunzi** [comment]
Did you set a "stopAt" value?
Otherwise I really don't know why it should stop after 12 sec.

**Comment by jerem555** [comment]
Here is the code i used to display video : 

<div id="P1" class="player" style="display:block;height:100%; background: rgba(0,0,0,0.5)" data-property="{videoURL:'https://youtu.be/6FTUpceqWnc',containment:'self',showControls:true,startAt:0,mute:true,autoPlay:true,loop:true,opacity:1,showYTLogo:false, optimizeDisplay:true}"></div>


Its working on html template but not on magento so i think problem comes from loading scripts on my install of magento

**Comment by jerem555** [comment]
#SOLVED my mistake... script was loaded 2 times... thats why video stopped. Thanks again for your help !!
