### ISSUE TITLE
Fullscreen button on iPhone

### ISSUE THREAD

**Issue by v-skiff** [pupunzi/jquery.mb.YTPlayer#308]
Hi!
It seems like the button for exit from fullscreen mode doesn't work on iPhone. What I could do to resolve this issue? Thanks in advance for any help!
Thanks for cool plugin!)

**Comment by pupunzi** [comment]
Hi,
The full screen button should not work at all on mobile... it is not allowed by the API...

**Comment by frafor1988** [comment]
Hi pupunzi, is there a way to allow the user to play the vid on mobile on his will? If someone is on WiFi, may want to view it, so it should be allowed.

**Comment by pupunzi** [comment]
The background video now works also on mobile devices.

**Comment by teacj** [comment]
Hello,
Which API are you referring too? Youtube's?

I've implemented YTPPlayer on a site and it's working fine. Except for fullscreen on iPhone. There's no problems on Android or in Safari, Chrome or Firefox(which I've just re-tested). And I'm trying to figure out if it's a general iPhone-problem or if there's something else wrong.
