### ISSUE TITLE
How to show a loading bar

### ISSUE THREAD

**Issue by diegoiglesias** [pupunzi/jquery.mb.YTPlayer#309]
Hi, I want to show a loading bar on the top of the page like Youtube does.
I've checked YTPBuffering out but I don't think it's the right event for this.

Can you help me?
Thanks

**Comment by pupunzi** [comment]
Hi,
I don't really understand what bar are you referring to;  anyway there's the 'YTPTime' event that is fired every second and returns the video played time (e.time):

```
myPlayer.on("YTPTime", function (e) {
     var currentTime = e.time;
     var totalTime = myPlayer.YTPGetTotalTime();
}
```
You can see an example in the demo.html file
