### ISSUE TITLE
background video positioning 

### ISSUE THREAD

**Issue by sillagokpora** [pupunzi/jquery.mb.YTPlayer#310]
Hi pupunzi,

I have a problem regarding the video background on the website I am editing. I am trying to use a premade website template using bootstrap, so I just insterted the video ID. The site and the video background are working fine besides this. 
The problem is that an important part of the video is not visible. In this case this is the bottom segment of the video because the performer on the recording had been cut halfway in one of the camera angles. 

1. I tried to change the anchor setting from (center,center)  to (bottom,center) but it didn't work. Nothing happened.
2. Changing the OptimizeDisplay property from true to false is not a solution for me because I still want the video to fill the entire background area and I don't want any black stripes or a small video on mobile devices.

My aim is to make the the bottom zone of the Yutube video visible without any black stripes. Is that possible?

Do you have any idea? 
Here is the site with the video in question:
http://antalzalai.com/testsite/index_finance.html

Thank you in advance.

**Comment by pupunzi** [comment]
Hi,
From what I can see on your page the video is anchored correctly on the bottom (resizing the window it stays correctly anchored).
You should consider that there's anyway a small portion of the video that is cropped to prevent the display of the Youtube logo on the bottom. 
If you want you can play with the "jQuery.fn.optimizeDisplay" method to adapt its behavior to your needs.

All the best,
Matteo

**Comment by sillagokpora** [comment]
Dear Matteo,
Thank you for your quick reply!
It seems to me that quite a big portion is invisible of the video at the bottom, on the contrary the top of the video is almost entirely visible.
I would like to try and play with the "jQuery.fn.optimizeDisplay" method.  I found this section in the code but to be honest I have no idea which parameters I should adjust or change at all. Could you give me just a quick guide? where to look at in that code.
Thank you ind advance!

Best regards,
Csilla

**Comment by pupunzi** [comment]
Hi Csilla,
At the time it adds 180px to the original iframe height to prevent the logo display... and that is probably too much :-)

here is a variation of the method where it adds the 10% of the original height and honestly it seems to be better:

```
	jQuery.fn.optimizeDisplay = function( anchor ) {
		var YTPlayer = this.get( 0 );
		var vid = {};

		YTPlayer.opt.anchor = anchor || YTPlayer.opt.anchor;
		YTPlayer.opt.anchor = typeof YTPlayer.opt.anchor != "undefined " ? YTPlayer.opt.anchor : "center,center";
		var YTPAlign = YTPlayer.opt.anchor.split( "," );

		if( YTPlayer.opt.optimizeDisplay ) {
			var el = YTPlayer.wrapper;
			var iframe = jQuery( YTPlayer.playerEl );
			var abundance = YTPlayer.isPlayer ? 0 : iframe.height() * 0.1;
			var win = {};
			win.width = el.outerWidth();
			win.height = el.outerHeight() + abundance;
			YTPlayer.opt.ratio = eval( YTPlayer.opt.ratio );
			vid.width = win.width;
			vid.height = Math.ceil( vid.width / YTPlayer.opt.ratio );
			vid.marginTop = Math.ceil( -( ( vid.height - win.height ) / 2 ) );
			vid.marginLeft = 0;
			var lowest = vid.height < win.height;

			if( lowest ) {
				vid.height = win.height;
				vid.width = Math.ceil( vid.height * YTPlayer.opt.ratio );
				vid.marginTop = 0;
				vid.marginLeft = Math.ceil( -( ( vid.width - win.width ) / 2 ) );
			}

			for( var a in YTPAlign ) {

				if( YTPAlign.hasOwnProperty( a ) ) {
					var al = YTPAlign[ a ].replace( / /g, "" );
					switch( al ) {
						case "top":
							vid.marginTop = lowest ? -( ( vid.height - win.height ) / 2 ) : 0;
							break;
						case "bottom":
							vid.marginTop = lowest ? 0 : -( vid.height - ( win.height ) );
							break;
						case "left":
							vid.marginLeft = 0;
							break;
						case "right":
							vid.marginLeft = lowest ? -( vid.width - win.width ) : 0;
							break;
						default:
							if( vid.width > win.width )
								vid.marginLeft = -( ( vid.width - win.width ) / 2 );
							break;
					}
				}
			}

		} else {
			vid.width = "100%";
			vid.height = "100%";
			vid.marginTop = 0;
			vid.marginLeft = 0;
		}

		jQuery( YTPlayer.playerEl ).css( {
			width: vid.width,
			height: vid.height,
			marginTop: vid.marginTop,
			marginLeft: vid.marginLeft,
			maxWidth: "initial"
		} );
	}
```
Just replace the original method with this one where the "abundance" parameter is changed and let me know.
All the best,

**Comment by sillagokpora** [comment]
Dear Matteo,

I replaced the original method with the above one, and it works perfectly.  This is exactly what I wanted. Without your help it would have been much harder to find out what to do. :-)
Thank you for your help! 
And of course thanks for this player! 
Best regards,
Csilla

**Comment by pupunzi** [comment]
Great! ;-)
