### ISSUE TITLE
Suggested Videos and More Videos button

### ISSUE THREAD

**Issue by jdev1977** [pupunzi/jquery.mb.YTPlayer#311]
Having a mysterious problem for one user in Chrome, but not for other users.  
I don't see any obvious extension installed, figured I'd run this past you and check if you've seen this before. 

Sounded similar to this older issue, but we are using 3.1.2

https://github.com/pupunzi/jquery.mb.YTPlayer/issues/285

http://khovhomesregistration.com/NOTH1v2/

![morevideos2](https://user-images.githubusercontent.com/11538913/33398275-6abce130-d51c-11e7-9ae1-7223ac2dfb01.png)

![morevideos1](https://user-images.githubusercontent.com/11538913/33398274-6aabe52e-d51c-11e7-855b-7eb0b5783553.png)

**Comment by pupunzi** [comment]
Hi,
It is quite strange :-)
Couldn't that depends on any plug-in installed on that Chrome instance that add a suggested video layer on the Youtube videos?

I'm sure it is not related to the plug-in itself... It could be related to the Youtube video properties (but as it happens just to one user I don't believe so) or to some behavior of a plug-in installed on that Chrome.

All the best,
Matteo
