### ISSUE TITLE
Compatibility with latest jQuery

### ISSUE THREAD

**Issue by bubble33** [pupunzi/jquery.mb.YTPlayer#312]
Hi.
On adding the latest version of jQuery YTPlayer has stopped working - the console says:

"Uncaught TypeError: $(...).mb_YTPlayer is not a function"

It was working perfectly before this.

Any ideas?

Thanks

**Comment by pupunzi** [comment]
Hi,
The latest jQuery version is the 3.2.1 that is the same I'm using on the demo files:
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>`

Do you have a public page where I can see your issue?

**Comment by bubble33** [comment]
Hi. Yes sure it's: http://bit.ly/2kPavqh - you'll see a grey box under the our services section on the homepage. This is where the video was playing until a few days ago.
Thanks

**Comment by pupunzi** [comment]
If you look at the javascript console you've another error:
`WOW is not defined `

I think that this error is preventing the YTPlayer javascript to load.

**Comment by pupunzi** [comment]
I see you are pointing to the javascript on my server...
You should not do that but have it locally on your.

**Comment by bubble33** [comment]
Hi.

I removed the call to WOW and replaced the script with a local version. However it's still not fixed the problem. Any other ideas?

**Comment by pupunzi** [comment]
Hi
The source of the jquery.mb.YTPlayer.min.js doesn't contain the YTPlayer.js script...
(http://fuchsiagreen.com/wp-content/themes/fuchsiagreen/js/jquery.mb.YTPlayer.min.js)

**Comment by bubble33** [comment]
Ok cool. I've resolved the trouble - my code was calling the function: mb_YTPlayer - I notice you now call it YTPlayer (without the mb_)
Cheers for looking into this for me.
