### ISSUE TITLE
How to reload and resize player while screen change, and how to play on mobile

### ISSUE THREAD

**Issue by mrrtee** [pupunzi/jquery.mb.YTPlayer#313]
I have 2 questions;

1) How to reload and resize player while screen change?
>> when I use this script to play video on fullscreen in browser, and when I enlarge or reduce page size by press "Ctrl+" or "Ctrl-", the player does not adjust accordingly, I thought that script may have command to reload player, then I will apply to jQuery when page resize..
>> How can I do?

2) How to play on mobile?
>> Basically, I think that video playing on mobile is disable by default, however I apply code to some page and it works, but some page does not work, not sure what happen, and how to fix it?

**Comment by mrrtee** [comment]
knock knock

**Comment by pupunzi** [comment]
Hi,

1. If you resize the window by dragging the borders or the corners the video will resize to best fit the available area. If you're using the Ctrl+ or the Ctrl- the video will not change as it refers to the window and not to the content to set its size.

2. The YTPlayer should work also on mobile from version 3.1.3. If it does work on some pages and not on others the problem could be on your pages and not on the component. Check if you have any javascript error or something that could prevent it to work.

All the best,
Matteo
