### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ,

### ISSUE THREAD

**Issue by simran66** [pupunzi/jquery.mb.YTPlayer#314]
```
VM601:1 Uncaught SyntaxError: Unexpected token ,
    at HTMLAnchorElement.<anonymous> (jquery.mb.YTPlayer.js?ver=4.9.1:143)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.buildPlayer [as mb_YTPlayer] (jquery.mb.YTPlayer.js?ver=4.9.1:134)
    at setting.js?ver=4.9.1:3
    at setting.js?ver=4.9.1:4
```

I am using wordpress and theme memenz.  I only imported the demo and changed their video id with mine.

I keep getting the above error. how do I fix this?

You can check the error in console here: http://www.aonesalons.com/

**Comment by pupunzi** [comment]
Hi simran66,
I'm not able to reproduce your issue on your page... No errors in console...

**Comment by danny-englander** [comment]
Older issue but I ran into this too. The culprit was faulty markup in the HTML within `data-property=`
