### ISSUE TITLE
Can script check if script can play via YouTube or not

### ISSUE THREAD

**Issue by mrrtee** [pupunzi/jquery.mb.YTPlayer#315]
I have question;
how to check if script cannot play video from YouTube
in case of that video is not exist
or it has been blocked by user (maybe proxy or firewall)

and i would like script to play video from hosting instead (could be .mp4)

is it possible? and how can I do ?

**Comment by pupunzi** [comment]
Hi,

1. If the video you're trying to load is unavailable you'll have an error on screen and an error event is fired (onError).

2. No, you can't use a self hosted video using this plugin. Only videos from Youtube.
