### ISSUE TITLE
Quality setting not applied

### ISSUE THREAD

**Issue by frafor1988** [pupunzi/jquery.mb.YTPlayer#316]
Hi there, I am using YTPlayer to set up a video background, however the quality setting is not being applied as the video always loads as 360p with very poor quality.

This is the data-property settings in use:

data-property="{ 
videoURL:'$youtube',
mobileFallbackImage:'$fallback;',
containment:'.big-background',
autoPlay:true,
mute:false,
showControls: false,
quality: 'hd1080',
optimizeDisplay: true,
startAt:0,
opacity:1}"

**Comment by pupunzi** [comment]
Hi,
the "quality" setting does not guarantee that the playback quality will actually change. Youtube set the quality based on the available video size on its server and based on the available bandwidth when the video is playing.
