### ISSUE TITLE
jquery.mb.YTPlayer.min.js 3.1.7 requires jquery.mb.vimeo_player.src.js ?

### ISSUE THREAD

**Issue by ak545** [pupunzi/jquery.mb.YTPlayer#318]
Hi!
I'm found in the code of jquery.mb.YTPlayer.min.js

alert("This is the 'jquery.mb.vimeo_player.src.js' javascript file and can't be included. Use the one you find in the 'dist' folder!");

It is normal?

In the source code (jquery.mb.YTPlayer.js), this is not present.

![2018-01-18_14-59-29](https://user-images.githubusercontent.com/12557874/35097340-bb7a8c42-fc60-11e7-9a0b-75121d957c52.png)

**Comment by pupunzi** [comment]
Hi,
there was a grunt compile error. Just published an update (3.1.8) that solve this issue.
