### ISSUE TITLE
Sometimes Youtube API loads very slow (30 seconds)

### ISSUE THREAD

**Issue by OkanKaradag** [pupunzi/jquery.mb.YTPlayer#321]
Hi,
I would like to ask if there are any problems with youtube API loading content? Recently, youtube api response very slow (30 seconds per pageload!) This happens like 2 times in a week, otherwise it works good. See the image attached. What might cause to the problem? Any help for solution?Thanks in advance[Errors when loading the web site] https://i.hizliresim.com/9m20gQ.png

**Comment by pupunzi** [comment]
Hi,
I'm not experiencing this isse... couldn't depends on your connection?

**Comment by OkanKaradag** [comment]
The video on Youtube just works fine but the response on the web site is very slow at the same time.
My video link : http://youtu.be/abJM7m_8Mzo
My web site link : www.garantikonserve.com
This just happens sometimes, for now it seems good but might happen anytime.
Please help me!

**Comment by pupunzi** [comment]
Some times the Youtube API can slowdown on responding due to physiological situation such as traffic overload, maintenance, updates, etc. and there could also bee some issue concerning your connection... I really don't know how to help you, sorry; it is not depending on the plugin calls.

**Comment by OkanKaradag** [comment]
Thank you very much.
