### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by ivandotv** [pupunzi/jquery.mb.YTPlayer#322]
I'm using the player as a video background and it was working correctly, however now there is another
`div` that is wrapping the video player `class=inline-YTPlayer` and it is forcing  `position:relative` and it is completely messing up the layout.
I am using containment `self`
I see that it is completely new code added in last two commits. What is the purpose of that code?

**Comment by ivandotv** [comment]
It is also adding these styles to the html element that is holding the video ( where video is actually initialized
```
display: block;
position: relative;
padding-bottom: 56.25%;
overflow: hidden;
height: 0px;
```
That is also messing up the layout.
I have that div like this:
```
position: absolute;
top: 0;
left 0;
width: 100%;
height: 100%;
```
So it acts as a video background.

**Comment by pupunzi** [comment]
Using "self" as containment the component set the containment as "player" changing the layout to make the player responsive.
If you don't want this behavior you should not use the video placeholder as containment:

```
<!-- the video containment -->
<div id="v1" class="playerBox" style="background: #7698c6;"></div>

<!-- the video placeholder -->
<div id="p1" class="player" data-property="{videoURL:'qvuILbcXlg8',containment:'**#v1**', showControls:false, autoPlay:true, loop:2, mute:true, startAt:5, stopAt:10, opacity:1, addRaster:true, quality:'default'}"></div>
```

**Comment by scrobbleme** [comment]
I think this is still an issue as it makes it quite hard to use the lib, as this behaviour is not obvious and propably will break many sites using a video on "body".
