### ISSUE TITLE
Option to loop an x number of times not working

### ISSUE THREAD

**Issue by raysreclame** [pupunzi/jquery.mb.YTPlayer#323]
I'm trying to loop a movie once, so it's shown twice. But no matter what number i enter, it keeps looping forever (except for 0, then it doesn't loop). This is the code i use:

	     data-property="{
		    videoURL:			'https://youtu.be/xxx',
			containment:		'#hero',
			quality: 			'default',
			ratio:			'auto',
			startAt:			0,
			showControls:	false,
			mute:			true,
			autoPlay:		true,
			loop:			2,
			showYTLogo:		false,
			opacity:			1,
			stopMovieOnBlur:	false,
			anchor: 			'center,center',
		}"

 Am i using the right notation or is this a bug?

**Comment by pupunzi** [comment]
Hi,
this issue has been fixed with the 3.1.13 release.

**Comment by raysreclame** [comment]
Sorry, but that will be the next version then as you're now at 3.1.12?
