### ISSUE TITLE
3.1.9 and 3.1.12 what changer. My web cant add any more js 

### ISSUE THREAD

**Issue by dlmobiles** [pupunzi/jquery.mb.YTPlayer#324]
Ver 3.1.12 cant play and cant add to play list http://live.karadl.com/
Ver 3.1.9 this very good. http://karadl.com

Pls tell me how changer in new ver ?

**Comment by pupunzi** [comment]
Hi,
do you have errors on console?

**Comment by dlmobiles** [comment]
yes. it error cant jquery.validate

**Comment by pupunzi** [comment]
The plug-in works fine; probably there's a compatibility issue with some other script you have on your site and I can't see the error on console on your page as you are cleaning the logs... I'm sure it is not a direct problem of the YTPlayer plug-in as it works for everyone... methods are not changed from 3.1.9 to 3.1.12...
