### ISSUE TITLE
Video autoplay not working on Safari

### ISSUE THREAD

**Issue by WORX-Developer** [pupunzi/jquery.mb.YTPlayer#327]
I'm using the version "jquery.mb.YTPlayer 31-01-2018" and encountered difficulties with the plugin with Safari (v11.0.3) on Mac (v10.12.6 "Sierra"). To be specific, the autoplay setting (autoPlay:true) does not work.

If I set showControls:true and press the play button it works. But unfortunately this is not an option for me. 

Any idea or hint?

**Comment by ak545** [comment]
https://support.apple.com/guide/safari/stop-autoplay-videos-ibrw29c6ecf8/mac
"Never Auto-Play" is On?

**Comment by WORX-Developer** [comment]
You are right, autoplay for media with audio is disabled.
But I didn't set this myself. So I guess this is enabled by default.

I just checked what happens if I set autoPlay:true and mute:true.
Suddenly the autoplay on the video works. 

So it's not a problem with the plugin but with browser settings.
For me, I see this issue as solved.

Thank you.

**Comment by ak545** [comment]
;)
