### ISSUE TITLE
youtube api called many times

### ISSUE THREAD

**Issue by zearadoua** [pupunzi/jquery.mb.YTPlayer#329]
Hello mr @pupunzi 
i have a little probléme with performance.
my case is that i use a slider and inside each slide items i got a video in background 
everything is working fine
but when i test performance in gtmetrix i got a many calls for the youtube api as shown in the image
![image](https://user-images.githubusercontent.com/9933686/36322009-beceb482-1343-11e8-861f-7b3a067963c9.png)
![image](https://user-images.githubusercontent.com/9933686/36322070-ebf11342-1343-11e8-872e-8c50b1c538ce.png)
thank you for the plugin.

**Comment by pupunzi** [comment]
Hi,
That depends on how the slider is working...

**Comment by zearadoua** [comment]
Hi @pupunzi 
sorry for the late in respond 
I found that for every video was initialized there's a call for the youtube api 
even if I use youtube API directly
I found a work arround for this problem is that I only initialize the video if it's in the view (lazy load) 
thank you.

**Comment by iadmemoriam** [comment]
@zearadoua i know it's been a while, but would be awesome if you explain how you lazy loaded it 🙏!
