### ISSUE TITLE
How to remove Youtube's Ads ?

### ISSUE THREAD

**Issue by Le-future** [pupunzi/jquery.mb.YTPlayer#33]
Hi, 

firstly great plugin very useful for my projects, but is it possible to remove the Youtube's Ads on the video ?

Greetz

**Comment by nexxoz** [comment]
Install AD blocker + add a small popup on ur site for users to get ad blocker if ad blocker is not detected. Not the best way but it works.

**Comment by Quotatic** [comment]
1.add a code into browser’s developer console can slove this problem before.
document.cookie="VISITOR_INFO1_LIVE=oKckVSqvaGw; path=/; domain=.youtube.com";window.location.reload();
2. Some adblocker like Adblock, Ghostery are also useful. 
Donwload YouTube videos is also a good way to block off any ad:http://www.videoconverterfactory.com/tips/remove-youtube-ads.html
