### ISSUE TITLE
When i change the url  its not working

### ISSUE THREAD

**Issue by RashidRcp** [pupunzi/jquery.mb.YTPlayer#331]
data-property="{videoURL:'qvuILbcXlg8',containment:'#myPlayer', showControls:true, autoPlay:true, loop:false, mute:true, startAt:0, opacity:1, addRaster:true, quality:'default'}". 
**I changed to** 

data-property="{videoURL:'ubtAAbaq5yo',containment:'#myPlayer', showControls:true, autoPlay:true, loop:false, mute:true, startAt:0, opacity:1, addRaster:true, quality:'default'}". 

I cant figure out the error , please help.
Thanks

**Comment by RashidRcp** [comment]
Well, I got a solution , its works fine in my web server.
but not in my local host, thats not a big issue.

**Comment by pupunzi** [comment]
Hi,
if you check the console you can see that that video doesn't have permissions to be embedded into external site:

video ID:: ubtAAbaq5yo: The owner of the requested video does not allow it to be played in embedded players.
