### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by soxepo** [pupunzi/jquery.mb.YTPlayer#332]
How can I use it several times(like a bg video) on one page?

I use this options for the first div
`<div id="video_bg" class="player video_option"
         data-property="{
                    videoURL:'<?php the_field('video_for_background'); ?>',
                    containment:'.video_bg',
                    autoPlay:true,
                    mute:true,
                    startAt:0,
                    opacity:1,
                    showControls:false,
                    quality:'hd720',
                    stopMovieOnBlur: true
                    }">
    </div>`
and for the second
`<div id="video_bg" class="player video_option"
                 data-property="{
                    videoURL:'<?php the_field('xyz_video_for_background'); ?>',
                    containment:'.xyz_video_bg',
                    autoPlay:true,
                    mute:true,
                    startAt:0,
                    opacity:1,
                    showControls:false,
                    quality:'hd720',
                    stopMovieOnBlur: true
                    }">
            </div>`

init
`$(".video_option").YTPlayer();`

and have error
"TypeError: e.target.getPlaybackQuality is not a function at onPlaybackQualityChange "

**Comment by pupunzi** [comment]
Hi,
The first error I can see on this code is that you are using the same ID for both the DIV. The ID should be unique; but I can't help you without an URL to the page where this issue happens...

**Comment by soxepo** [comment]
Crap!
Thanks, man! This was a problem ((
