### ISSUE TITLE
Mobile fallback not working for me

### ISSUE THREAD

**Issue by welshchris** [pupunzi/jquery.mb.YTPlayer#333]
I'm trying to disable the video completely on mobile, and have set a fallback image, but the video continues to play underneath the image. Can you tell me how to disable the video completely on browsers with a small viewport?

Test page is - http://www.festrail.co.uk/video_bg_test6.htm

Thanks in advance.
Chris

**Comment by welshchris** [comment]
I should be clearer.... I have specified fallback images in my own css for tablet and mobile, but what I specifically need to do is disable the video on tablets and mobiles because of terrible mobile signal in our area. i preferred the script when it didn't work on mobile! :-)

Are you there Pupunzi?

**Comment by pupunzi** [comment]
Hi Chris,
on the latest 3.1.13 version there's a new "useOnMobile" option that let you choose if it should or not work on mobile. Setting it to false the previous behavior should be used.

 Download the 3.1.13 and let me know if it works for you.

All the best,
Matteo

**Comment by welshchris** [comment]
Thanks Matteo - Is 3.1.13 dated 13.2.18? - I don't see the version number in the code comment. My version is dated 16.1.18 and seems to include "useOnMobile" as well?

I'd also like help with how to implement this option - i.e. a code example if possible. It's not included in the doc.

Thanks in advance
Chris

**Comment by welshchris** [comment]
Thanks for that Matteo - Works perfectly now!

**Comment by pupunzi** [comment]
Great! ;-)
