### ISSUE TITLE
Video stops on first frame in Safari

### ISSUE THREAD

**Issue by r007** [pupunzi/jquery.mb.YTPlayer#334]
Hi pupunzi,

We use the latest YTPlayer (13-02-2018), the video background works fine in Chrome/Firefox, but stops on first frame in Safari.

Data properties:
```
fitToBackground: true,
realfullscreen: true,
stopMovieOnBlur: false,
addRaster: true,
showControls: false,
startAt: 0,
opacity: 1,
gaTrack: false,
containment: #hero,
videoURL: https://www.youtube.com/watch?v=Ht39XLCQ43o,
mute: false,
autoPlay: true,
loop: true
```

JS Script for video background https://pastebin.com/raw/AwzYmgg8

Here's the link to website:
http://innocence.squeakywheelcreative.com/

Do you have an idea why it may not work?

**Comment by ak545** [comment]
https://github.com/pupunzi/jquery.mb.YTPlayer/issues/327

**Comment by r007** [comment]
Yep, that worked! Thanks.

**Comment by tleifj** [comment]
This doesn't appear to be fixed. I'm having the same issue and the fix ak545 linked to is not working. I also checked the link of the OP and it is also not working in Safari. Interestingly, If I resize the window or go to a new tab and back, it will work. 

Safari Version 12.0 (13606.2.11)
macOS 10.13.6 (High Sierra)
