### ISSUE TITLE
After window resize, the max-width doesn't update

### ISSUE THREAD

**Issue by snade** [pupunzi/jquery.mb.YTPlayer#335]
Hi,
I've noticed that on a mobile device when I turn to landscape, the video stays the same as before, doesn't grow to fill the whole screen.
On viewport change, the max-width inline property set to the video container, doesn't update. 

I've overwritten it with "max-width: 100%!important" and for now it behaves properly on screen resizing.

**Comment by arkid** [comment]
Also having this problem when I use the player on the background of a div.    The div is set to 100% screen width and when the TYPlayer initialises it seems to write a max-width inline tag onto its outer wrapping element.  As that inline property isn't updated, any resizing of the browser space that increases its size goes over that original width limit and so the player doesn't increase in size leaving an empty space down the side of my page.

**Comment by pupunzi** [comment]
@arkid 
Hi, do you have an URL where I can see your issue?
The default behavior is responsive and should resize with the DIV (https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_domElement.html)

**Comment by joseangeljimenez** [comment]
Same issue confirmed here on Firefox. It rarely happens but can be reproduced by quickly resizing the browser window. Sometimes the player doesnt stretches to the maximum allowed width. Adding this to my custom.css fixes the issue,
```
.inline-YTPlayer {
  max-width: 100% !important;
}
```
