### ISSUE TITLE
Styling Mobile Fallback Image

### ISSUE THREAD

**Issue by welshchris** [pupunzi/jquery.mb.YTPlayer#337]
Matteo - I have the fallback image working, but I'd like to apply some style to it, i.e. 'background-size:contain;' so that the image fits into the container properly. The fallback image works correctly on both mobile and tablet, but of course without styling it doesn't display the whole image (stretch/shrink to fit etc.). I tried using inline styling but couldn't get it to work. Could you explain how to achieve this?

url is http://www.festrail.co.uk/video_bg_test6.htm

**Comment by pupunzi** [comment]
You can fix it via CSS...

add this code to your css file:

div#wrapper_video {
    background-position: top !important;
    background-size: 100% !important;
}
