### ISSUE TITLE
cc_load_policy won't show subtitles

### ISSUE THREAD

**Issue by runegronkjaer** [pupunzi/jquery.mb.YTPlayer#338]
Hi,

I have been trying hard to autoshow subtitle/captions on my videos. I can do it with the vanilla YT.Player, but not with your otherwise brilliant YTPlayer.
On the vanilla player I can do it like this:
...
player = new YT.Player('player', {
        height: '390',
        width: '640',
        videoId: 'aBYGrlkxDiU',
        playerVars: { 'cc_load_policy': 1 },
        events: {
          'onReady': onPlayerReady,
          'onStateChange': onPlayerStateChange
        }
      });
...
Adding the cc_load_policy to the playerVars in this plugin doesn't do anything no matter what I do, and I'm puzzled.

Is it possible, or have I run into some kind of a bug?

/Rune

**Comment by pupunzi** [comment]
Hi,
on the next release there will be a new "cc_load_policy" option to activate the subtitle/captions capability. By default is set to false as the YTPlayer used as background video is cropped to fit the display area. 

If you download the Master code the option is already there.

**Comment by runegronkjaer** [comment]
I can see that you have been busy and added the feature to the dist. I'm not sure if I'm doing something wrong, but I cannot get it to work.
I have tried doing it with the very basic example, and my video that have subtitles: I'm using the non minified script and the standard jquery.mb.YTPlayer.min.css.
`<div id="bgndVideo" class="player" data-property="{videoURL:'http://youtu.be/aBYGrlkxDiU',containment:'self',cc_load_policy:true,autoPlay:true, mute:true, startAt:0, opacity:1}">My video</div>`

I can see that the YT.Player get a '1' in the cc_load_policy, when i inspect the javascript, but no subtitle is showing up. Also that was one of the things I tried to force, last friday, when debugging.
I'm using Chrome on a windows 10 machine.

**Comment by pupunzi** [comment]
Hi,
if you are using the YTPlayer as background video either for thew BODY or for any other element of your page the display has an abundance margin for the display that is cutting out the subtitle from the bottom. this abundance is needed to prevent the display of the Youtube logo at the bottom of the video.

You can remove this abundance via options and set the anchor point of the video to the bottom adding the following:

`cc_load_policy:true, abundance: 0, anchor: 'bottom,center'`

this way the bottom will be always available and the subtitle visible.

All the best,
Matteo

**Comment by runegronkjaer** [comment]
Yes. That was exactly what was wrong.
Setting abundance to 0 did not make the player any higher (larger). So I'm not entirely sure as to how this actually works.

But thanks a billion for your quick help. 

/Rune
