### ISSUE TITLE
youtube-nocookie.com support

### ISSUE THREAD

**Issue by petrhasalik** [pupunzi/jquery.mb.YTPlayer#339]
Hello,

I would like to ask how to modify the plugin so that it will work with youtube-nocookie.com? I have tried to change it manually in the code, but it does not work.

This will be a big deal now with GDPR knocking on our doors and I need to solve it. If that is not possible I will have to leave this plugin.

Thank you.

**Comment by pupunzi** [comment]
Hi,
The youtube-nocookie embed doesn't support the Youtube API events so it is not possible to use it.
Sorry
