### ISSUE TITLE
issue mute / unmute video

### ISSUE THREAD

**Issue by jeromebart** [pupunzi/jquery.mb.YTPlayer#340]
Hi, 

First, thank you for this very useful plugin !

I'm using your plugin for a background video, and I've created a button to unmute / mute  sound (like on your demo).
It's working well on desktop, but on mobile iOS and firefox mobile, the button doesn't seems to work (except for chrome mobile). I've tried different things and when the video isn't set on mute, the button is working, but you have to touch de screen to play the video.

On your demo, the first video has the same problem, but when you use  "change video 1-2-3" button, it's working well. 

Do you have a fix for this problem ?

Many Thanks !

**Comment by pupunzi** [comment]
Hi, 
the audio volume on iOs devices (and I presume on the others too) can't be managed vi API as it needs a real interaction with the device volume control.

All the best,
Matteo

**Comment by jeromebart** [comment]
You're right, I've find a way to do it with 
player.YTPUnmute(); / player.YTPMute();

Thank you again, 

Jerome
