### ISSUE TITLE
Load Video URL from external text file

### ISSUE THREAD

**Issue by bcontento** [pupunzi/jquery.mb.YTPlayer#341]
I want to store the video URL in an external file, then read that file into the webpage and have it used in the player. I've got the external file (simple one line txt file) and can read it into the page, store it as a variable, but can't figure out the best way to have it used in the div data-property videoURL value.

I've tried using jquery to build and insert the entire player DIV and it works including the URL from the external file, however, the player doesn't build correctly. The end part that the JS builds onto the div (starting with id="YTP_1522466697166"...) never gets created. I assume it's because the function I wrote to add the player DIV happens too late (maybe the playerJS executes too soon and can't add the properties because it can't find the div?

Has to be an easier way to do this. any help would be appreciated!

**Comment by pupunzi** [comment]
On the data-property you can set a variable as videoURL as you can see in the "demo_random.html" example.  The variable should be already defined once you initialize the player so you should initialize it with a callback fired when the file containing the videoURL is loaded in the page. If you are using an Ajax call to load the variable you then should initialize the player on the success callback.
