### ISSUE TITLE
jQuery Initialization not working

### ISSUE THREAD

**Issue by RohitSethia** [pupunzi/jquery.mb.YTPlayer#342]
Hello,

The jQuery Initialization is not working after the Latest Update. Not identifying the selectors. Can you please check. Here is the code:

**HTML:**
<pre>&lt;div class=&quot;youtube-bg-player&quot; style=&quot;height: 600px;&quot;&gt;
&#x9;..
&lt;/div&gt;</pre>

**jQuery:**
<pre>jQuery(&quot;.youtube-bg-player&quot;).YTPlayer({
&#x9;videoURL: &apos;http://youtu.be/A3PDXmYoF5U&apos;,
&#x9;startAt: 20,
&#x9;stopAt: 40,
&#x9;quality: &apos;hd1080&apos;,
&#x9;containment: &apos;self&apos;
});</pre>

Thanks.

**Comment by pupunzi** [comment]
Hi,
do you have a public URL where I can see your issue?
The code seems correct... but without your page example I can't help you...
