### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by bgiorgi** [pupunzi/jquery.mb.YTPlayer#343]
Hello, 
quality parameter isn't working in my case. 
It's set to "highres", (quality:'highres'), but, loading low quality videos at low speed internets.

**Comment by pupunzi** [comment]
Hi,
The quality parameter is a suggestion for the YouTube API; if your bandwidth is low then YouTube will serve the video optimizing quality based on the real possibility for the stream without considering your settings.
