### ISSUE TITLE
Nested containment

### ISSUE THREAD

**Issue by HjalmarCarlson** [pupunzi/jquery.mb.YTPlayer#344]
I'm using the library for the hero section of the site here: http://cw.hjalmarcarlson.com

The containment can't be applied to 'body' and the added inline-YTPlayer wrapper that is created when applying 'self' containment breaks the layout. Is there a way to target a parent>child selector inside the containment? Is it possible to create nested containment?

**Comment by pupunzi** [comment]
Just set the CSS selector of the element where you need the video to play.
