### ISSUE TITLE
Pause video when container is not visible 

### ISSUE THREAD

**Issue by fnagel** [pupunzi/jquery.mb.YTPlayer#346]
Is it possible to add something that stops the video when the container is not visible. Something similar to `stopMovieOnBlur`?

**Comment by pupunzi** [comment]
Hi,
if you download the master there's the "playOnlyIfVisible" option that play the video only if it is visible on screen.

**Comment by pupunzi** [comment]
Do you mean when the container is out of screen?

**Comment by fnagel** [comment]
Works like a charm. Thanks a lot for your fast response!
