### ISSUE TITLE
How to make it so the video doesn't go fullscreen and just plays within the element alone

### ISSUE THREAD

**Issue by capples3** [pupunzi/jquery.mb.YTPlayer#347]
Hi,
I have a dev site up and ready to go [www.clhdesigns.com/18](url) on the home page I have the cover photo load and then the video plays, then it automatically takes over the whole screen. I'm looking for it to just play within that banner and not take over the whole page. How can I accomplish this? 

Thx

**Comment by pupunzi** [comment]
Hi,
You should first use the latest release of the YTPlayer script: https://github.com/pupunzi/jquery.mb.YTPlayer/archive/3.2.1.zip

Replace all the files including the CSS.

I'm not able to find where you are initializing the player on your javascript files. Anyway I think you should set as containment  the ".home" section and not the "BODY" as I presume you actually do.

All the best,
Matteo
