### ISSUE TITLE
Issue with Samsung Internet browser

### ISSUE THREAD

**Issue by fnagel** [pupunzi/jquery.mb.YTPlayer#348]
The video stays blank on the Samsung Internet browser (v 6.4.10.5) on a Galaxy Tab S2 running on Android 7.0. Reproducible on project demo page.

Testing on Chrome on this tablet works fine. Any idea why?

**Comment by pupunzi** [comment]
Hi,
googling on the web for your issue I found that others had the same problem with youtube videos using the Samsung web browser... I presume it depends on how thy are implementing their player in the browser but I've no solution for that; it seams a bug of that browser...

**Comment by fnagel** [comment]
Thanks for the fast feedback! Ohh, that's sound we're not able to do something. 

Do you have a link for me? I wan't able to come up with something useful.

**Comment by pupunzi** [comment]
Unfortunately I've not found any post with solutions for this issue.
On this one there's a comment at the bottom of the article where someone falls back to Chrome just for the same problem:
https://www.androidcentral.com/google-chrome-vs-samsung-internet-browser-which-do-you-prefer
