### ISSUE TITLE
Unable to unmute inline video

### ISSUE THREAD

**Issue by teacj** [pupunzi/jquery.mb.YTPlayer#351]
Hello,

We have some inline videos on our site. They're default muted, and the users need to active the sound of their own.

This works on all devices except **iPhone 7 with iOS 11.3**. Absolutely nothing happens when we try to click on the mute/unmute icon. 

If the videos are displayed "outline" (as in: the user need to press play for the video to start), there's no problem with mute/unmute. 

We have been able to recreate the issue on your own demo with autoplay: https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html 

Have you experienced this bug before?

Regards, 
Camilla

**Comment by pupunzi** [comment]
Hi,
I've to check why... if you perform a "changeVideo" action then the mute/unmute works...
it'a a bug :-)

**Comment by teacj** [comment]
Hi,
Thank you for the fast reply. We'll await a fix then :)

**Comment by teacj** [comment]
Hey, 
I was wondering if you know when we can expect a bugfix for this issue? :)

**Comment by teacj** [comment]
Hi,
Is there any news on this?

**Comment by pupunzi** [comment]
Hi Camilla,
with the latest 3.2.2 release, this issue should be closed.
https://github.com/pupunzi/jquery.mb.YTPlayer/releases/tag/3.2.2

All the best,
Matteo
