### ISSUE TITLE
Video not centered on element

### ISSUE THREAD

**Issue by premitheme** [pupunzi/jquery.mb.YTPlayer#353]
Hi there,

I was using v3.0.20 and have an element with YT background applied on it, and this was the result as expected...
![screen_shot_2018-04-22_at_11_12_21_pm](https://user-images.githubusercontent.com/3824596/39100067-5a7a34ce-4684-11e8-8e1a-dbf3ac2ac0b1.png)

Then when I updated to v3.2.1 the video is not centered vertically...
![screen_shot_2018-04-22_at_11_11_42_pm](https://user-images.githubusercontent.com/3824596/39100146-9f67edaa-4685-11e8-924f-a7d4c6cf1404.png)

As you can see it's shown correctly in the first screenshot, but its covered in the second one (notice the word "Copenhagen" which is centered vertically in the video).

I only swapped the minified js file, nothing else touched.
Not sure what I'm doing wrong, any advice will be appreciated.

**Comment by premitheme** [comment]
Thanks for your response,

Here is the link to [demonstration of the issue](http://premitheme.com/tests/demo-test/).

I was not using the CSS file before with the old version, but to make sure I tested the CSS file with new version and it doesn't make any difference.

I was skeptical about FitVids plugin being the issue, but removing it makes no difference as well.

Another thing I have found, when I initially load the page at certain window width, 1000px for example, then I resize the window to smaller width, say 500px, and I resize it back to bigger width like 1200px, the video background will not go bigger than the initial width (1000px) and will leave me at the final width (1200px) with 200px of black area. Here is a screenshot of the final result.

![screen shot 2018-04-25 at 7 05 43 pm](https://user-images.githubusercontent.com/3824596/39261565-2b721daa-48bd-11e8-8fcf-e2adb06af048.png)

Looks like something preventing the plugin from resizing the centering correctly, but it's strange because this happen when I only update the plugin, nothing else is changed.

**Comment by pupunzi** [comment]
Hi,
You should not set the containment as "self" other then if you want to render a chrome-less player.
Just create a DIV element with all the YTPlayer properties and the DIV element where the player should play and set the containment as follow:

```html
<div class="class="pt-bg-mask pt-intro-bg"></div>

<div id="ytp-properties" data-property="{videoURL:'https://www.youtube.com/watch?v=gKDDUbPLnqM', containment:'.pt-bg-mask pt-intro-bg', ratio:'auto', autoPlay:true, mute:true, showControls:false, showYTLogo:false, stopMovieOnBlur:false, startAt:0, opacity:1}"></div>
```

In your javascript initialize the YTPlayer on the DIV element that contains the properties:

```javascript
    jQuery(function () {
          jQuery("#ytp-properties").YTPlayer();
   });
```

This will fix your problem.

**Comment by premitheme** [comment]
Thanks a lot, this fixed my issue.
