### ISSUE TITLE
Video not playing on Chrome for OSX

### ISSUE THREAD

**Issue by welshchris** [pupunzi/jquery.mb.YTPlayer#356]
I can't make the video play on Chrome on the Mac.

Chrome version 66.0.3359.170 (Official Build)
OSX High Sierra 10.13.4

I get the first frame but then nothing. Chrome is also a little flaky on Windows 10.

Page is here: www.festrail.co.uk

Could you figure out what's going wrong?

TIA

**Comment by pupunzi** [comment]
Hi,
you have javascript errors in console that probably are blocking the YTPlayer plugin:

![schermata 2018-05-14 alle 18 39 33](https://user-images.githubusercontent.com/56659/40010839-45bf4d70-57a6-11e8-8fc7-97b73282791e.png)

**Comment by welshchris** [comment]
Thanks for getting back to me!

I have cleared the errors, but still no playable video. Any idea what else it could be?

**Comment by pupunzi** [comment]
Did you try disabling the other plug-ins to see if there's a conflict with them?

**Comment by welshchris** [comment]
I've tried stripping the page back to the bare code removing as many scripts as I can - Still no luck

**Comment by Le-future** [comment]
Same here, safe install, was working a few days ago, I don't understand what's wrong

**Comment by pupunzi** [comment]
Maybe this answer can help you: https://github.com/pupunzi/jquery.mb.YTPlayer/issues/357
