### ISSUE TITLE
Player mutes the video by default ignoring 'mute:false' parameter

### ISSUE THREAD

**Issue by 0x6FA3D0** [pupunzi/jquery.mb.YTPlayer#359]
The problem was described in the title. It started to happen after some of the recent updates.
Calling jQuery("#bgv").YTPUnmute(); after loading the player is fixing the problem, but thats not the proper solution because this is working only after page reload.

**Comment by 0x6FA3D0** [comment]
As i can see, this is related to the new Chrome autoplay policy. Any possible bypass?

**Comment by pupunzi** [comment]
Hi,
It is not a bug. With the latest Youtube policy the video can auto play only if muted. At the time this is applied only by Webkit browsers but soon by all. 

You can restore the previous behavior commenting from line 353:

        /**
         * If autoPlay is set to true the mute must be true 
         * as required by the latest Youtube policy
         */
        if(YTPlayer.opt.autoPlay)
          YTPlayer.opt.mute = true;
  
All the best,
Matteo

**Comment by 0x6FA3D0** [comment]
Thanks, already decided to force users to press on the button before loading other page content.
