### ISSUE TITLE
Option to use youtube-nocookie.com due to GDPR regelations

### ISSUE THREAD

**Issue by fnagel** [pupunzi/jquery.mb.YTPlayer#360]
Is there a way to change the created URL from `https://www.youtube-nocookie.com/embed/` to `https://www.youtube-nocookie.com/embed/`? This is needed to match the new GDPR guidelines as forced by the EU.

**Comment by pupunzi** [comment]
Hi,
No way to do that. youtube-nocookie.com doesn't expose the Youtube javascript API.
Just add to your cookie declaration the Google Youtube use of cookies.

**Comment by fnagel** [comment]
Thanks for the fast response! 

Did some more research myself and it seems more people having this issue, see https://github.com/CookPete/react-player/issues/272#issuecomment-343912996

**Comment by Alexander-van-aken** [comment]
To add usability, is there a way to get a preview image loaded over another domain by google? since now, when blocked and added to the advertizing/targeting cookie category, users see a black canvas. Maybe add a custom video img bg via css?
