### ISSUE TITLE
Issue loading normal .mp4 file from external file

### ISSUE THREAD

**Issue by calstu99** [pupunzi/jquery.mb.YTPlayer#362]
I am having issues loading .mp4 file using jquery.mb.YTplayer plugin 
Is there currently a property for load this (vs using youtube URL). An example would also be helpful.

**Comment by pupunzi** [comment]
Hi,
No, this plugin works only with video hosted on Youtube.

All the best,
Matteo

**Comment by LukeDouglas2** [comment]
Matteo,

Put it on your 'to-do' list at some time in the future.  The ability to use locally stored videos would really reduce a lot of performance hits.  It is a great add-on.
