### ISSUE TITLE
Video playing not from start and looping not till final frame

### ISSUE THREAD

**Issue by siberianbear** [pupunzi/jquery.mb.YTPlayer#363]
Hello,

First of all - thank you very much for such useful plugin!

I'm using latest version - jquery.mb.YTPlayer 29-05-2018

Video is placed on youtube and  8 sec long.
I've tried to use "startAt:0"-prop but with no luck. Video is playing in loop from ~4 sec to ~6 sec. So not from start and not to final frame.

Is it possible to fix it somehow please?

**Comment by pupunzi** [comment]
Hi,
the video should start 1 second after the real start and end 1 second before the real end due to technical problems
