### ISSUE TITLE
Possibility to add nocookie-Version

### ISSUE THREAD

**Issue by maniax-at-work** [pupunzi/jquery.mb.YTPlayer#364]
Hey there,

i am in germany and as you know we all drive Crazy about the new EU-DSGVO.
So i wanna know if it is possible to change make it more private to get a YT-Video as background.
With youtube-nocookie or so?
i checked the network already and there are many connections to youtube and partners.
Is it possible to protect the privacy of our visitors or should i disable YT?

**Comment by pupunzi** [comment]
Hi,
The youtube-nocookie doesn't expose the Youtube javascript API and can't be used as a source for the video. 

Maybe you can try using this script to prevent Youtube to set cookies:
https://github.com/nicholasruggeri/cookies-enabler

**Comment by maniax-at-work** [comment]
Thanks I'll give it a try

**Comment by fnagel** [comment]
Duplicate of #360
