### ISSUE TITLE
YTPlayer is not a function

### ISSUE THREAD

**Issue by roietik** [pupunzi/jquery.mb.YTPlayer#368]
Hi, I have a this issue message from browser: YTPlayer is not a function

`jQuery.Deferred exception: $(...).YTPlayer is not a function @http://localhost:3002/:283:9
mightThrow@http://localhost:3002/js/jquery-3.3.1.js:3534:21
resolve/</process<@http://localhost:3002/js/jquery-3.3.1.js:3602:12
 undefined`

`TypeError: $(...).YTPlayer is not a function[Więcej informacji]
localhost:3002:283:9
<anonimowa>
http://localhost:3002/:283:9
mightThrow
http://localhost:3002/js/jquery-3.3.1.js:3534:21
resolve/</process<`

Can you help me?

full code of index.html inside: http://www.wklejto.pl/566589

**Comment by pupunzi** [comment]
You should give me a working URL to check what's going on.

Is the path to the javascript and the css file correct?
