### ISSUE TITLE
Redirect site when video is finished

### ISSUE THREAD

**Issue by edulaerti** [pupunzi/jquery.mb.YTPlayer#371]
Hello,

How can i manage to redirect the site after the video is finished? 

i have a six seconds video and i want to tell the script that when the video is finished redirect the site to another page as im using it as a splash screen for the mobile app.

Regards

**Comment by pupunzi** [comment]
Hi,
There's the "YTPEnd" event fired once the video ends you can use for the redirect:
https://github.com/pupunzi/jquery.mb.YTPlayer/wiki#events
