### ISSUE TITLE
YTPlayer conflicts with Owl Carousel 2

### ISSUE THREAD

**Issue by hauph** [pupunzi/jquery.mb.YTPlayer#372]
Hello everyone,
I have a site: https://devildaves.com/
where I use YTPlayer for youtube videos.
On this site, I also use Owl Carousel 2 for 3 sliders.
However, I realize that somehow YTPlayer blocks Owl Carousel's swipe (touch) event on mobile, making it impossible to swipe to change the slider. Owl Carousel's next and prev buttons still work, but it cannot be swiped to change slides on mobile.
It works fine on desktop screen and when I remove YTPlayer, the Owl Carousel works fine again on mobile, meaning I can swipe to change slides.
I am stuck at this conflict, so I am truly grateful if anyone can suggest me any idea on how to resolve this problem.

**Comment by pupunzi** [comment]
Hi,
If on mobile the plugin adds an "ontouchstart"  event to the body that is probably the cause of your issue.
You can try commenting from line 555 to line 562:

```javascript
        /**
         If is on device start playing on first touch
         */
        if (jQuery.mbBrowser.mobile && YTPlayer.opt.autoPlay && YTPlayer.opt.useOnMobile)
          jQuery("body").one("touchstart", function () {
            YTPlayer.player.playVideo();
          });

```

**Comment by hauph** [comment]
@pupunzi thank you for your response. I tried it but somehow it seemed to be not working.
But please dont worry, because I think I've found a way to fix this.
I followed this: https://stackoverflow.com/questions/46789482/element-changedtouches0-error-undefined-chrome-bug
and it works now :)
So I think this issue can be closed now.
Thank you once again.
