### ISSUE TITLE
property Mute dont work

### ISSUE THREAD

**Issue by Golden-Puma** [pupunzi/jquery.mb.YTPlayer#377]
Downloaded last version your's script.
And sound gone off.
I need start with sound, but 'mute:false' or 'mute:true' not effect. Sound off.
https://www.dellemoscow.ru/
```
<!-- YOUTUBE VIDEO-->
			<div id="bgndVideo" class="video-player" data-property="{videoURL:'<?php echo $aVideo;?>', containment:'.module-video',  startAt:0, autoPlay:true, loop:true, opacity:1, showControls:false,   mute:false, showYTLogo:false, ratio: 16/9}">

			</div>
			<!-- /YOUTUBE VIDEO-->
		<a href="#" value="Звук" id="mute-toggle" onclick="jQuery('#bgndVideo').YTPToggleVolume();toggleClass(this, 'volume-off', 'volume-up')" class="volume-up"></a>
```

**Comment by pupunzi** [comment]
Hi,
The latest browser policy is to prevent video to start automatically if the audio is on.
At the time Webkit browsers are applying this policy. 
If you download the Master (https://github.com/pupunzi/jquery.mb.YTPlayer/archive/master.zip) the behavior is now different. The audio is on again but on Webkit browsers, if they block the video, it will start after a first click on the page with the audio.

**Comment by Golden-Puma** [comment]
This is weird. why is this related to browsers?! after all, until yesterday I had an old version of your script and audio included immediately with autoplay videos

**Comment by pupunzi** [comment]
Are you sure?

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/
https://bitmovin.com/play-not-play-new-autoplay-policies-safari-11-chrome-64/
http://adage.com/article/digital/apple-blocks-autoplay-video-safari-web-browser-update/309266/

... and more and more...

**Comment by Golden-Puma** [comment]
yes. look, return last version script.
https://www.dellemoscow.ru
video autoplay and audio on
