### ISSUE TITLE
privacy-Enhanced mode.

### ISSUE THREAD

**Issue by Vakarian96** [pupunzi/jquery.mb.YTPlayer#378]
Is it possible to use the privacy-enhanced mode?

**Comment by pupunzi** [comment]
Hi,
It is not possible to activate the privacy-Enhanced mode using the javascript API.
Enabling privacy-enhanced mode means taht videos are served from youtube-nocookie.com but 
youtube-nocookie.com doesn't allow javascript API to interact with the video and this break the YTPlayer plug-in.

**Comment by fnagel** [comment]
Duplicate of #360
