### ISSUE TITLE
Player starts then stops very quickly as if buffering a little with play button ignored if pressed during the first seconds of initialisation

### ISSUE THREAD

**Issue by arkid** [pupunzi/jquery.mb.YTPlayer#379]
I have custom control buttons in place on a video that starts on the background of a div.  In general all the functionality works fine. 

The videos are set to not start automatically.   If you try to start the video quicky after the page has loaded the play button action is ignored and the play button goes to a pause then back to a play.  

It seems like some kind of buffering is going on and that the play request is basically ignored during this process.

The video can be seen here below the first full width image filling the page: https://www.anderson-sheppard.co.uk/haberdashery/style/trousers/

You may need to scroll down to this, then once there Ctrl F5 refresh the browser to reload the page at the required page scroll position in order to press the button and see this occurring.

**Comment by pupunzi** [comment]
Hi,
The "play" action can be performed after the "YTPReady" event has been fired; if you try to start the player before the YTPlayer is ready (it is ready after that the Youtube API has been loaded and the video has been buffered enough to start) then the play action is not considered.

What I suggest is to display the custom button bar on the "YTPReady" event:


``` javascript
jQuery('#homepage100_1').on("YTPReady",function(e){
      // your code to display the buttonbar
});
```


All the best,
Matteo

**Comment by arkid** [comment]
Thanks so much Matteo that did the trick!
