### ISSUE TITLE
startAt option not working

### ISSUE THREAD

**Issue by AlohafromHell** [pupunzi/jquery.mb.YTPlayer#380]
Suddenly startAt option not working. (demo.html)
if set option startAt :40,  starts 40 seconds later

Thank you for awesome plugin.
Thank you in advance.

**Comment by rugor** [comment]
Same issue, `jquery.mb.YTPlayer 08-06-2018`

**Comment by pupunzi** [comment]
With the last 3.2.5 release this issue has been fixed

**Comment by AlohafromHell** [comment]
Thanks, pupunzi That's perfect! Much appreciated.

**Comment by rugor** [comment]
Thanks for the fix @pupunzi ... npm is still @ v. 3.2.2 :)
