### ISSUE TITLE
How to disable video's end cards

### ISSUE THREAD

**Issue by ExillustX** [pupunzi/jquery.mb.YTPlayer#383]
Is it even possible to disable the end cards?

![image 1078](https://user-images.githubusercontent.com/6927114/44467770-9fcadc80-a61b-11e8-84e3-eb8de636284b.png)

**Comment by pupunzi** [comment]
Hi,
this screenshot is not the mb.YTPlayer layout; it is the default Youtube player.
With the mb.YTPlayer you should not have the suggested video at the end

**Comment by ExillustX** [comment]
No i'm just showing an example. Even with mb.YTPlayer the cards still show up, they are not suggested videos nor annotations.

You can read more about it:
https://support.google.com/youtube/answer/6388789

**Comment by ExillustX** [comment]
Thanks!
