### ISSUE TITLE
Have to touch the screen before play

### ISSUE THREAD

**Issue by MrDaGree** [pupunzi/jquery.mb.YTPlayer#387]
I have to touch the screen before it plays, tried on iPhone 7, iPhone 4s, iPod 5, iPad 2

**Comment by pupunzi** [comment]
Hi,
On mobile devices, the media autoplay behavior is limited by the vendors to prevent unwanted bandwidth usage. In case the autoplay is not available (usually because the audio is turned on) the plugin let you start the video on the first physical touch.

It is not a bug but a feature :-).
