### ISSUE TITLE
Remove youtube play button from mobile browser

### ISSUE THREAD

**Issue by compostbrain** [pupunzi/jquery.mb.YTPlayer#388]
I am having an issue with version 2.7 showing the play button in chrome mobile browser.  Is it possible to remove it?  I have set both showControls and showYTLogo to false in the data-properties like so:
`					<a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=0Fpj3eWmODA', containment:'.video_slide', showControls:false, autoPlay:true, loop:true, vol:0, mute:true, showControls: false, showYTLogo: false, startAt:10, opacity:1, addRaster:false, quality:'default'}"></a>`
but that has no effect.  You can view the problem if you open this [link](http://theblockchainagency.biz/devsite-beta-4/) in a mobile browser.

**Comment by pupunzi** [comment]
Hi,
We are now at version 3.2.5.
You should use the latest release.
The 2.7 was not working on mobile devices.

All the best,
Matteo
