### ISSUE TITLE
how to init player on button click

### ISSUE THREAD

**Issue by hardikpoojara** [pupunzi/jquery.mb.YTPlayer#389]
`$(document).ready(function(){
	window.addEventListener('CookiebotOnAccept', function (e) {
    if (!($("html").hasClass("mobile"))){
    	$(".player").playerDestroy(); // This is not working
        $(".player").mb_YTPlayer();
    }
    }, false);
});`

**Comment by pupunzi** [comment]
Hi,

` $(".player").playerDestroy()` is not an YTPlayer method.
the correct one is:
` $(".player").YTPPlayerDestroy();`

here is an example to initialize the player via a button click:

```html
<div id="wrapper">
  <div style="text-align: center">
    <button id="playVid"  style="font-size: 40px; margin: 20px" >PLAY VIDEO</button>
  </div>
  <div id="p1" class="player" data-property="{videoURL:'qRSPVj1ldVQ',containment:'body', showControls:true, autoPlay:true, loop:2, mute:true, startAt:9, stopAt:100, opacity:1, addRaster:true, quality:'default', playOnlyIfVisible: false}"></div>
</div>
```
```javascript
<script>
  function play(){  jQuery(".player").YTPlayer();  }
  $(function(){
    $("#playVid").on("click", play);
  })
</script>
```
