### ISSUE TITLE
How i can add link to play

### ISSUE THREAD

**Issue by dlmobiles** [pupunzi/jquery.mb.YTPlayer#390]
i have link https://www.fshare.vn/file/L818QSHPUTE6 
How i can add link to play ? 
Thanks

**Comment by pupunzi** [comment]
Hi,
what do you mean by adding a link to play?

**Comment by dlmobiles** [comment]
Yes

**Comment by dlmobiles** [comment]
Hi

**Comment by dlmobiles** [comment]
pls help
