### ISSUE TITLE
Hide player only on mobiles and not on tablets

### ISSUE THREAD

**Issue by nkki** [pupunzi/jquery.mb.YTPlayer#392]
Hello, is it possible to only hide the player on mobiles and not on tablets using the useOnMobile function? thank you

**Comment by pupunzi** [comment]
Hi,
the "useOnMobile" option doesn't distinguish between Tablets and smartphones. If you want that distinction you can make your own function that returns it is a tablet or not to set the useOnMobile option:

``` javascript
function isTablet() { 

        // The jQuery.browser.js in bundle with the mb.YTPlayer.js 
        // set the jQuery.isTablet variable based on the mobile verification
        // and on the screen size.

        // Use your own verification if more relayable.

        return jQuery.isTablet;
}

jQuery("#bgndVideo").YTPlayer({ useOnMobile: isTablet() });
```

**Comment by nkki** [comment]
Thank you for noticing. But I can't seem to understand what I'm supposed to put in the function. Can you explain it in a more detailed way? Please and thank you.

**Comment by nkki** [comment]
It works! Thank you so much. I'm inlove with this plugin. Hope you create more like this, in the future. God Bless!

**Comment by pupunzi** [comment]
Great! :-)
