### ISSUE TITLE
YTPlaylist does not have smooth transition

### ISSUE THREAD

**Issue by nkki** [pupunzi/jquery.mb.YTPlayer#393]
Hello again. I'm using the YTPlaylist and added 4 videos in an array. It seems that everytime the video ended, it loads again before the next video which by the way, creates a delay. Is it supposed to be doing that? Thank you

**Comment by pupunzi** [comment]
Hi,
yes, I notice that the YTPlaylist method has some problems; probably something broken with the latest code changes.
I'll check to fix it.

**Comment by nkki** [comment]
Yes please and thank you

**Comment by pupunzi** [comment]
This issue should now be fixed with the 3.2.7 release:  https://github.com/pupunzi/jquery.mb.YTPlayer/archive/3.2.7.zip
