### ISSUE TITLE
Cut the bottom of video

### ISSUE THREAD

**Issue by dardos** [pupunzi/jquery.mb.YTPlayer#395]
Hi,

First of all, thanks for your job!

My video is cutting the bottom and I don't know why. I checked your demo and the same is happen.

https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_domElement.html

The original movie has more height.

Do you have any idea?

Tks

**Comment by pupunzi** [comment]
Hi,
The viewport of the video depends on the aspect ratio of the containment element. The video size is calculated to cover all the containment area cutting the extra areas to prevent the display of the black strips top/bottom or left/right.
You can manage the anchor point of the video via the "anchor" option that let you decide which part should be masked (center, top, bottom, left, right combined in pair).

If you need to display the video entirely you should set the "**optimizeDisplay**" option to false when you initialize the video.

All the best,
Matteo
