### ISSUE TITLE
Video stops on first frame and has loader in Safari

### ISSUE THREAD

**Issue by tleifj** [pupunzi/jquery.mb.YTPlayer#396]
This is similar to issue #334 which had a fix but it doesn't seem to be working for me. The video hangs in Safari on the first frame. It sits there with the YT loading circle. Interestingly, If I resize the window or go to a new tab and back, it will work.

Safari Version 12.0 (13606.2.11)
macOS 10.13.6 (High Sierra)

**Comment by pupunzi** [comment]
Hi,
this is why the video stops to autoplay:

https://faq.dailymotion.com/hc/en-us/articles/360000102908-Browser-rules-that-determine-autoplay

Working to make it start playing again. Hope to publish a fix soon.

**Comment by pupunzi** [comment]
@tleifj can you try downloading and testing the master?
Now on Safari if is set the autoplay option the audio mute is forced before playing and additionally, the video would start after the first mouse down interaction.  
It is working for me; if the browser settings have the "automatic reproduction" set to "never" the video would anyway start after the first user mousedown.

Let me know if those changes fix your issue.

**Comment by tleifj** [comment]
Hello,

This looks like it worked! Thanks for the quick response and fix!
