### ISSUE TITLE
HD quality on start

### ISSUE THREAD

**Issue by pomyslografia** [pupunzi/jquery.mb.YTPlayer#398]
Hi Pupunzi,

Thanks for a great plugin. I'm using it on this page: http://lidar3d.pomyslografia.pl
Sometimes video starts in hd sometimes not. If not, after few seconds video changes quality to hd.
Is there a possibility to start video always in hd quality? Thank you in advance for your answer.

**Comment by pupunzi** [comment]
Hi,
The video quality is managed by Youtube and depends on the bandwidth available. Setting the quality parameter to "auto" will make Youtube optimize the quality based on the visitor bandwidth capability.

All the best,
Matteo

**Comment by pomyslografia** [comment]
ok, thank you
