### ISSUE TITLE
how to hide info on top

### ISSUE THREAD

**Issue by pomyslografia** [pupunzi/jquery.mb.YTPlayer#402]
Hi, I have problem with info shown on top of placed in background YT video (author and share button). I know it disappears after a few seconds, but I would like it to not appear at all. Thank you in advance for your answear.

http://redvet.pomyslografia.pl/pl/

**Comment by ierpe** [comment]
+1 same problem, but I do not think it's coming from the plugin, I think it's youtube related...

**Comment by pupunzi** [comment]
Unfortunately, Youtube recently removes the possibility to hide the share and the watch later actions from the embed videos: https://stackoverflow.com/questions/52886853/youtube-embed-showinfo-has-been-deprecated

At the time if you stop the video those elements will come out at the top of it.

Hope something will change on their API to let we hide those two buttons.

**Comment by prestamod** [comment]
IIt is possible:
player.on('YTPPause',function(){
                    $(this).find('iframe').hide();
                });
                player.on('YTPPlay',function(){
                    $(this).find('iframe').show();
                });
