### ISSUE TITLE
muted after update

### ISSUE THREAD

**Issue by gioiafueter** [pupunzi/jquery.mb.YTPlayer#403]
Hi, I just updated the script, and now the video is muted, although mute is set to false:

<a id="bgndVideo" class="player" data-property="{
        videoURL:'http://youtu.be/<?php echo get_the_title("196")?>',
        autoPlay:false,
        quality: 'hd720',
        optimizeDisplay:true,
        containment:'body',
        mute:false,
        startAt:0,
        opacity:1,
        loop:false,
        addraser:true,
        printurl:false,
        showcontrols:true,
        realfullscreen:true,
        showYTLogo:false
        }"></a>

Any idea what may be the issue?
Thanks in advance!

Gioia

**Comment by pupunzi** [comment]
Hi,
do you have an url where I can see the issue?

**Comment by gioiafueter** [comment]
Hi,

Yes, here it is: http://www.actorsoneagency.com/
Thanks in advance!

**Comment by gioiafueter** [comment]
So, I think I may have an idea of what may be the issue, just not sure what is the best way to fix it.
Together with the script, I was using the wordpress plugin plus to remove watermarks and so. I dont remember exactly how it was set, though.

Then the customer wanted a duplicate of the site on another domain, and I think by duplicating the site, the single site licence made it not work on the original site.

While trying to fix the watermark issue, I tried updating the script, then no sound. I deleted the wordpress plugin, upload it and activate it again, now sound is back, but still watermark. The "plus" is disabled and I dont see where to put a license number anywhere in the settings...

**Comment by gioiafueter** [comment]
So please how can I enter the licence for the original site?

**Comment by pupunzi** [comment]
Hi,
here is the link to download the mb.YTPlayer plus plugin for Wordpress:
https://pupunzi.com/wpPlus/wp-plugins/YTPL/wp-ytplayer-plus-3.3.9.zip

Install it and on the settings page you'll find the field for the license key.
If the license is associated to another domain a link to change the domain will be displayed after validating the license.

Let me know,
Matteo

**Comment by gioiafueter** [comment]
Hi, I downloaded the plugin and installed it. Had to get a new license, as the one I had was for a previous version, no problem. But I still see the video title and a button that says "Watch later"... And I dont see any option about that in the plugins settings.... How can I get rid of that?

Thank you in advance!
Gioia

**Comment by pupunzi** [comment]
Hi Gioia,
Youtube has changed it's API and removed the property to hide those elements from the player interface.
The only way is to increase the "abundance" parameter that will zoom in the video viewport till those elements go off screen.

All the best,
Matteo
