### ISSUE TITLE
YouTube Quick links visible

### ISSUE THREAD

**Issue by tleifj** [pupunzi/jquery.mb.YTPlayer#405]
It appears that Google recently updated the embed to add quick links at the top of the video: https://www.tubefilter.com/2018/10/19/youtube-revamps-look-video-embeds/. These are visible with background videos. Do you know if there's something in the API that can remove this?

An example can be found here: https://www.ef.org/

**Comment by shahbazkhan054** [comment]
Hi I am also facing the same issue. No options found yet.

**Comment by pupunzi** [comment]
Hi,
There's no option to hide the related and the share button at the top as Youtube APi showInfo attribute has been removed.

The only available solution is via the "abundance" YTPLayer option.

You can try this option effects here:
https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo-abundance-anchor.html

**Comment by tleifj** [comment]
Hello,

Thanks for the solution. I tried this which sort of worked, but depending on the aspect ratio of the window, you can still sometimes see the info at the top. I ended up setting the top of the video wrapper to -75px and the bottom to 0 which pushed the info up of the screen.
