### ISSUE TITLE
Safari browser would not run the youtube video in background iframe.

### ISSUE THREAD

**Issue by hasanzahidi** [pupunzi/jquery.mb.YTPlayer#409]
Safari browser would not load the video and would throw the following error in the console:

**Unsafe JavaScript attempt to access frame with URL "_https://mysiteurl.com_" from frame with url "_https://youtube.com/embed/?_........". Domains, protocols and ports must match.**

The issue is not present in Chrome, Edge, IE and Firefox

**Comment by pupunzi** [comment]
The plugin uses to work fine on Safari.
This advice is not blocking and the video should anyway display.

do you have an URL where I can check what is going on?

**Comment by hasanzahidi** [comment]
the issue is no more. Thank you
