### ISSUE TITLE
Video not working in mobile Safari

### ISSUE THREAD

**Issue by mars9999** [pupunzi/jquery.mb.YTPlayer#411]
Hello, the video does not show on iOS/Safari for my mobile device - iPhone 6s.  However, the Pupunzi sample page does play a video on my iPhone.  Mobile Chrome works just fine.  Am I doing something wrong?  I'm new. thanks, marzz

https://www.humanities.uci.edu/SOH/new/educat/

**Comment by mars9999** [comment]
Not sure what changed, but this does work now.

**Comment by pupunzi** [comment]
With the latest vendor policies, the video will not autoplay if the audio is turned on. To make the video autoplay the audio should be turned off; if you set the audio on then the video will start after the first screen touch on mobile.

All the best,
Matteo
