### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by early-reflexions** [pupunzi/jquery.mb.YTPlayer#415]
Hello there !

Love your tool !

I'm on a npm based development, and I would like to know if you could update the package 3.2.2 to the current 3.2.8 ?
https://www.npmjs.com/package/jquery.mb.ytplayer

Thanks again a lot !
Cheers !

**Comment by pupunzi** [comment]
Hi,
just updated the package to version 3.2.8 on npm.
https://www.npmjs.com/package/jquery.mb.ytplayer
