### ISSUE TITLE
Play video from youtube

### ISSUE THREAD

**Issue by RussaX0** [pupunzi/jquery.mb.YTPlayer#416]
Is there any way to embed video from youtube instead of using downloaded video. I have difficulty using large video files on hosting so it would be much easyer if it was possible to embed videos from youtube source.

**Comment by pupunzi** [comment]
HI,
I can't understand the question...
You can include videos from youtube using their API or the embed code provided or using this plugin...
You can't embed Youtube videos as VIDEO source.

**Comment by thursby** [comment]
Hi @RussaX0 ,
It is not necessary (or even possible) to host video using this plugin. All the video data streams directly from YouTube, making it a very hosting-friendly way of serving video.
