### ISSUE TITLE
No issue, just one question: Integration in Joomla

### ISSUE THREAD

**Issue by HassanMullah** [pupunzi/jquery.mb.YTPlayer#417]
Has anyone ever integrated the jquery.mb.YTPlayer into Joomla? A step by step tutorial would be great. Thank you and a happy new year

**Comment by pupunzi** [comment]
Hi,
I find this website where one of their components is a background video realized with the mb.YTPlayer component:

http://demo.joomlead.com/particles/index.php/gantry5-atom/video-background
