### ISSUE TITLE
Ready not firing at all

### ISSUE THREAD

**Issue by nandoblanco** [pupunzi/jquery.mb.YTPlayer#418]
I'm testing inlining deferred scripts/libraries and I cannot get the video to show up!

The script runs, you can see it in the console log say that the video is muted... 

https://codepen.io/nando99/pen/zyRRKe

Can you look into this please?

thanks in advance!

**Comment by nandoblanco** [comment]
I updated the original post for clarity...

**Comment by pupunzi** [comment]
Hi,
The video is ready to run but it is not initialized...
If you run the `$(".player").YTPlayer()` in console the video start correctly:

<img width="1852" alt="schermata 2019-01-16 alle 16 13 14" src="https://user-images.githubusercontent.com/56659/51258272-e265ca80-19a9-11e9-987a-3ca8ff67c87f.png">

So I presume you have some timing issue...

**Comment by pupunzi** [comment]
Ok, the issue is that you are initializing the YTPlayer on the wrong element:

NOT: `$("#videoBGPlayer").YTPlayer();`
BUT: ` $(".player").YTPlayer();`
