### ISSUE TITLE
Autoplay not working

### ISSUE THREAD

**Issue by groupewibi** [pupunzi/jquery.mb.YTPlayer#420]
Here the Autoplay is set to One. 
`<div id="ytplayer" class="player" 
     data-property="{videoURL:'iVMI8s5EXG4',addRaster:true,playOnlyIfVisible:true,containment:'#header-home',showControls:false,startAt:30, mute:false,autoPlay:1,loop:true,opacity:1}">
</div>`

here the Iframe generated : 
`<iframe .... src="https://www.youtube.com/embed/?modestbranding=1&amp;autoplay=0&amp;controls=0&amp;showinfo=0&amp;rel=0 .....`

I tried to force by using a bit of JS : 
` $("#iframe_ytplayer").attr("src", $("#iframe_ytplayer").attr("src").replace("autoplay=0", "autoplay=1"));`

got an error : jQuery.Deferred exception: undefined is not an object (evaluating '$("#iframe_ytplayer").attr("src").replace') (2)

and still not autoplay to 1 : 
Any suggestion ?

**Comment by pupunzi** [comment]
Hi,
The new vendor policy about the autoplay are very restrictive and allow the autoplay only if the audio is turned off.

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

The YTPlayer plugin has a workaround that if the autoplay is set to true and the audio is not mute the video start once the user has the first click/touch interaction with the page.

You should not try to replace the iframe src as it is not present at the time you are trying to do that and it would not work anyway.

All the best,
Matteo
