### ISSUE TITLE
YouTube Suggestions appears after a while

### ISSUE THREAD

**Issue by arizeqnx** [pupunzi/jquery.mb.YTPlayer#421]
Hello together,

after a while the Player stops to loop the video and shows some suggestions instead.
Is there a fix for that?

Best regards
![tempsnip](https://user-images.githubusercontent.com/47140684/51900134-d0762580-23b4-11e9-80d2-e9b071332e4f.png)

**Comment by pupunzi** [comment]
It should not happens...
Do you have javascript errors in console?
Do you have an URL where I can check thew issue?

**Comment by arizeqnx** [comment]
No there are no errors on the console and the URL is unfortunatly not public.
I am using Version 3.2.9.

This is how it looks like on HTML:
`<section class="content-section video-section" style="position: relative;">
   <span id="controlBar_bgndVideo" class="mb_YTPBar inlinePlayer compact" style="white-space: nowrap; position: absolute; z-index: 1000; display: inline-block;">
      <div class="buttonBar">
         <span class="mb_YTPPlayPause ytpicon">p</span><span class="mb_YTPMuteUnmute ytpicon">A</span>
         <div class="mb_YTPVolumeBar simpleSlider muted" style="display: inline-block; cursor: auto;">
            <div class="level horizontal"></div>
         </div>
         <span class="mb_YTPTime">02 : 41 / 02 : 41</span><span class="mb_YTPUrl ytpicon" title="view on YouTube">Y</span><span class="mb_OnlyYT ytpicon">O</span>
      </div>
      <div class="mb_YTPProgress" style="position: absolute;">
         <div class="mb_YTPLoaded" style="position: absolute; left: 0px; width: 100%;"></div>
         <div class="mb_YTPseekbar" style="position: absolute; left: 0px; width: 0px;"></div>
      </div>
   </span>
   <div id="wrapper_bgndVideo" style="position: absolute; z-index: 0; min-width: 100%; min-height: 100%; left: 0px; top: 0px; overflow: hidden; opacity: 1; background-image: none; transition-property: opacity; transition-duration: 1500ms;" class="mbYTP_wrapper">
      <iframe id="iframe_bgndVideo" class="playerBox" style="position: absolute; z-index: 0; width: 2045.5px; height: 1151px; top: 0px; left: 0px; overflow: hidden; opacity: 1; -moz-user-select: none; margin-top: -338px; margin-left: -71.25px; max-width: initial;" allowfullscreen="1" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" title="YouTube video player" src="https://www.youtube.com/embed/?modestbranding=1&amp;autoplay=0&amp;controls=0&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1&amp;version=3&amp;playerapiid=iframe_bgndVideo&amp;origin=https%3A%2F%2Fdevhanau.service-now.com&amp;allowfullscreen=true&amp;wmode=transparent&amp;iv_load_policy=3&amp;cc_load_policy=0&amp;playsinline=0&amp;html5=1&amp;widgetid=1" unselectable="on" width="640" height="360" frameborder="0"></iframe>
      <div style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;" class="YTPOverlay"></div>
   </div>
   <div class="pattern-overlay" style="position: relative;"> 
      <a id="bgndVideo" class="player mb_YTPlayer isMuted" data-property="{videoURL:'https://www.youtube.com/watch?v=mt1jN5nRqXI',containment:'.video-section', quality:'large', autoPlay:true, loop:true, mute:true, opacity:1}" style="display: block;">bg</a> 
   </div>
</section>`

**Comment by pupunzi** [comment]
From the HTML is impossible to understand what is going wrong.
What browser are you testing with?

**Comment by arizeqnx** [comment]
Here I build a new page which you could access:
https://dev40833.service-now.com/ytplayer

How to reproduce (using firefox):
1. Open as a new tab
2. Keep working on other tabs for a while (10 minutes)
3. Go back to the Page

**Comment by arizeqnx** [comment]
That worked.
Thank you!
