### ISSUE TITLE
Video starts because of stopMovieOnBlur when focus returns to window, when video has been paused before focus loss

### ISSUE THREAD

**Issue by marcostastny** [pupunzi/jquery.mb.YTPlayer#422]
If you use the plugin like in the documentation and add the parameter stopMovieOnBlur it will start the video, even if the video has been paused before window focus loss.

I am currently using the plugin with the following settings:
```
{
    videoURL: 'https://www.youtube.com/watch?v=Bey4XXJAqS8',
    mute: false,
    showControls: true,
    ratio: 'auto',
    quality: 'highres',
    containment: '#youtube-header',
    optimizeDisplay: false,
    loop: false,
    autoPlay: false,
    showYTLogo: false,
    stopMovieOnBlur: false,
}
```

**Comment by pupunzi** [comment]
Hi,
just made some tests and all of them worked as expected.
If the video is paused once you focus the window again it is paused; if it is playing once focused it start playing again.

https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html

Do you have an URL where I can see the issue?
