### ISSUE TITLE
Video is last element loading on my page

### ISSUE THREAD

**Issue by arizeqnx** [pupunzi/jquery.mb.YTPlayer#424]
Hi pupunzi,

for some reason the youtube player is the last element on my webpage which appears.
It takes about 1 second to appear.

Is there any setting which controls that?

**Comment by pupunzi** [comment]
Hi,
This plugin needs about 1 second to setup and be ready to play as it has to call Youtube via the API and wait till the first part of the video is buffered enough to start.
