### ISSUE TITLE
Playlist callback only called once

### ISSUE THREAD

**Issue by simoneldevig** [pupunzi/jquery.mb.YTPlayer#425]
Hi,

I'm using the playlist to loop trough a list of autoplaying videos, but there seem to be a problem with the callback.

When initializing the playlist I hit the callback just fine and get the video info from the YT API, but when the video change the callback is not being called again.

Example code:
```
var videos = [{ videoURL:'koxqaR1YtJE', containment:'.js-video-player-container', showControls:false, startAt: 0, autoPlay:true, loop:false , mute:true, opacity:1}, { videoURL:'EzKImzjwGyM', containment:'.js-video-player-container', showControls:false, startAt: 0, autoPlay:true, loop:false , mute:true, opacity:1 }]

jQuery(dom.$videoContainer).YTPlaylist(videos, false, function(video){
  console.log('Video changed', video.videoData);
});
```

I'm running on the newest release (3.2.9)

**Comment by pupunzi** [comment]
Hi,
There's a little bug at line **1148**:

Change this:

```javascript
jQuery(YTPlayer).one("YTPChanged", function () {
          callback(YTPlayer);
        });

```
with this:

```javascript
jQuery(YTPlayer).on("YTPChanged", function () {
          callback(YTPlayer);
        });
```

This fix will be available with the next release.

**Comment by simoneldevig** [comment]
Thx
