### ISSUE TITLE
Feature request: pick video from shortlist

### ISSUE THREAD

**Issue by fraternl** [pupunzi/jquery.mb.YTPlayer#430]
The webmaster on our site bought a license of your plugin and we love it.
On the front page we're using it to display a youtube flick of clouds on the background.
https://hmvc.eu

I noticed there are more of these video's and I thought it would be nice if YTPlayer could randomly pick one video from a shortlist upon startup to make the front page more dynamic.

**Comment by pupunzi** [comment]
Hi,
If you are using the Wordpress plugin (https://pupunzi.com/wpPlus/go-plus.php?plugin_prefix=YTPL)
you can set a comma-separated list of Youtube video URL on the back-end to play them randomly each time you reach the page.

<img width="948" alt="Schermata 2019-03-20 alle 22 11 51" src="https://user-images.githubusercontent.com/56659/54719442-2ff2e500-4b5d-11e9-896b-dd3aeab89625.png">

If it has been implemented manually you can look at the "demo-random.html" file available downloading the main jQuery plugin (https://github.com/pupunzi/jquery.mb.YTPlayer/archive/3.2.9.zip)

All the best,
Matteo

**Comment by fraternl** [comment]
Done @ https://hmvc.eu
:-)
