### ISSUE TITLE
Mask Console Errors

### ISSUE THREAD

**Issue by mizzinc** [pupunzi/jquery.mb.YTPlayer#432]
https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo-masked.html

Failed to load resource: the server responded with a status of 404 (Not Found)
css/jquery.mb.YTPlayer.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.mb.YTPlayer.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
apikey.js:9 Uncaught TypeError: Cannot set property 'apiKey' of undefined
    at apikey.js:9
jquery.min.js:2 jQuery.Deferred exception: jQuery(...).YTPlayer is not a function TypeError: jQuery(...).YTPlayer is not a function
    at HTMLDocument.<anonymous> (https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo-masked.html:241:45)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999)
    at k (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: jQuery(...).YTPlayer is not a function
    at HTMLDocument.<anonymous> (demo-masked.html:241)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
jquery.mb.YTPlayer.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Managed to get this working on localhost in /dist/. Does not work in /examples/. 
I am able to apply mask using a button onclick. Have not been able to apply a single mask when the video initiates. e.g: 

//Single mask
var myPlayer = jQuery("#[playerID]").YTPlayer({mask:'assets/mask-1.png'});

Checked file paths too.

**Comment by pupunzi** [comment]
Hi,
with the latest 3.2.10 release this issue should be fixed
