### ISSUE TITLE
Usage of jQuery.slim fails silently

### ISSUE THREAD

**Issue by krnlde** [pupunzi/jquery.mb.YTPlayer#435]
I recently had trouble with this library, where the video wouldn't want to initialize properly, parts worked (like the needed DOM Containers where created correctly) but most of it didn't (like adding the actual iframe and starting the video). Unfortunately there where no errors in the console whatsoever - nothing was happening in the network tab of the inspector either.

So if anyone arrives here from google, the **TL;DR answer** is: use jquery not jquery.slim

**Comment by krnlde** [comment]
Maybe it's worth that @pupunzi gets notion of this issue?

**Comment by pupunzi** [comment]
Hi,
Thank you for the advice.
The jquery.slim.js library removes many core methods used by the YTPlayer plugin and is almost impossible to make it work without. I'll add this information in the documentation.
All the best,
Matteo
