### ISSUE TITLE
All my videos disappeared from my site

### ISSUE THREAD

**Issue by fraternl** [pupunzi/jquery.mb.YTPlayer#437]
I have been using your plugin on my site @ https://hmvc.eu/videos/ and afaik nothing changed to the site and currently all videos are gone.
What I think is strange is that the file YTPL.lic gets constantly written to and gets changed.

**Comment by pupunzi** [comment]
Hi,
I presume that the plugin you are using to compress the source code is removing all the YTPlayer scripts; I can't see any reference to the YTPlayer on the source code...

**Comment by fraternl** [comment]
I have done a restore of the site to that of 3 days ago...
I can't reproduce it anymore.
BTW... there was a theme update done by someone else, but that has been applied as well now.

Why is YTPL.lic constantly updating?

**Comment by pupunzi** [comment]
Hi,
The YTPL.lic file is updated any time the plugin needs to verify the license key on the server. That happens randomly when you open the admin back-end or if the plugin is not able to decrypt the YTPL.lic file. In all these cases the YTPL.lic file is updated.

All the best,
Matteo

**Comment by fraternl** [comment]
Thanks...
During troubleshooting it caught my eye and considered suspicious behaviour (in the context of a non-working site). I didn't see any other activity than my own in the logs, so I just thought it was peculiar...

Too bad I never was able to determine the culprit.

**Comment by fraternl** [comment]
FYI

The site runs on a server that's managed with Plesk.
Plesk has a WordPress Toolkit with which you can easily patch the code to have enhanced security.
It seems that one of the many security features clashed with the theme and I now have it disabled.

It's the hotlink protection.

This issue can stay closed.


![image](https://user-images.githubusercontent.com/8692856/106353273-a3cdaf00-62e9-11eb-9928-6e47d5d580aa.png)
