### ISSUE TITLE
Video does not start immediately

### ISSUE THREAD

**Issue by engel4u** [pupunzi/jquery.mb.YTPlayer#446]
When I open the page, it takes several seconds for the video to start. How do I do it That the video starts immediately?

http://www.square-concept.de/cct/index.php?article_id=9

**Comment by NPCtom** [comment]
Bumping this

**Comment by NPCtom** [comment]
@pupunzi Could you help us out please?

**Comment by pupunzi** [comment]
Hi,
the video needs the Youtube APi to load before starting and it should be around 1 or 2 seconds.

**Comment by NPCtom** [comment]
Is there a CDN we could use to speed up delivery of the js files?

**Comment by pupunzi** [comment]
The YTPlayer js file is loaded in 7 milliseconds; the Youtube API can only be called directly from Youtube

**Comment by pupunzi** [comment]
if you want to embed the YTPlayer from a CDN:
https://cdnjs.com/libraries/jquery.mb.YTPlayer
