### ISSUE TITLE
On Webkit browsers you can not autoplay the video if the audio is on.

### ISSUE THREAD

**Issue by prasadraja07** [pupunzi/jquery.mb.YTPlayer#449]
Cant able to play the video, even if we click pay also its not playing... got the following message in console.... How can we avoid this

On Webkit browsers you can not autoplay the video if the audio is on.

**Comment by pupunzi** [comment]
Browsers don't allow any playable media to automatically start with the audio turned on.
Anyway the video should start if you press the play button... do you have an URL where I can see the problem?

**Comment by prasadraja07** [comment]
After clicking the play button also video is not yet started playing..
We have faced the issue on the local internal..
