### ISSUE TITLE
Problem with abundance and pause

### ISSUE THREAD

**Issue by bilo1967** [pupunzi/jquery.mb.YTPlayer#450]
Hi,

if `abundance` is set other than the default 0.2 value, when the player is paused the video seems wrongly resized.

**Comment by pupunzi** [comment]
I will check,
thank you

**Comment by lyjen** [comment]
Hi, 
I got the same problem. Any solutions? Thanks

**Comment by pupunzi** [comment]
That is not a bug but a feature :-D

Youtube automatically displays on a paused video the related videos bar. To prevent that display or just to limit its terrible impact, the YTPlayer plugin resizes the video area once paused.  If that is for you a bug I can think to add an option to manage it.

**Comment by lyjen** [comment]
Hi Pupunzi,

Yes please, thanks in advance :)
