### ISSUE TITLE
Video display in mobile not centered

### ISSUE THREAD

**Issue by lyjen** [pupunzi/jquery.mb.YTPlayer#452]
![video mobile](https://user-images.githubusercontent.com/3081235/73280310-48299b00-4229-11ea-91f3-3fd25eb82e27.png)

I was trying to display the center of the video but failed to do it. It's displaying the left part of the video instead of the middle. I also set an anchor: 'center,center' and I don't think it has something to do with the display in mobile.  Anyone who can help? Please. Thanks!

**Comment by pupunzi** [comment]
Hi,
the "anchor" parameter should work also for mobile background video. 
Are you sure that the video containment has the same size as the mobile view?
Did you try changing the "abundance" parameter to see if that is influencing the background-position?

If you have a public URL where I can check your problem that could be helpful.
All the best,
Matteo

**Comment by lyjen** [comment]
Hi Matteo,

I'm glad with your reply. Here's the link http://178.128.54.120/watson-uat/nutrabliss.html
Abundance is working but I wonder if there's separate setup for mobile? I need to display the center of the video not the left one 🙏 

Many thanks,
- Jen

**Comment by pupunzi** [comment]
Hi,
you've another video plugin that actually is resetting the CSS properties calculated by the YTPlayer plugin:
`../assets/css/bgvid.css`

All the best,
Matteo

**Comment by lyjen** [comment]
Thanks Matteo, 
I will look on that.
