### ISSUE TITLE
large display results in blurry video

### ISSUE THREAD

**Issue by salcott** [pupunzi/jquery.mb.YTPlayer#457]
I have tested the different `quality` options:  (‘default’ or ‘small’, ‘medium’, ‘large’, ‘hd720’, ‘hd1080’, ‘highres’), but the video seems to be blurry no matter what.  It doesn't appear to load in high definition despite the video showing crisp on YouTube directly.

I see that this tool uses negative margin to focus in on the iframe, but without forcing HD video load I believe the blowing up of the video from 640x360 size just doesn't produce great results.

Please let me know what else to try, thanks for your hard work on this.

**Comment by salcott** [comment]
After more fiddling and hard refreshes, I was able to get the high res option to work with `hd1080`. I suppose your internet connection may have something to do with this, too.

**Comment by pupunzi** [comment]
@salcott The quality parameter you set is intended as a suggestion for the Youtube API. Youtube will try to serve the video with the set quality but it will fall back to a lower quality if there isn't enough bandwidth.
