### ISSUE TITLE
The stopAt function does not work

### ISSUE THREAD

**Issue by neo191987** [pupunzi/jquery.mb.YTPlayer#460]
Hi, first I want to thank you for the great plugin. I have a problem with the stopAt function, it no longer works. I also tested in your demo and it doesn't work there.

**Comment by pupunzi** [comment]
Hi,
I just tested the stopAt parameter and it is working fine for me.
do you have a webpage where I can see your issue?
The stopAt must be expressed in seconds and should not be higher than the video duration.
Let me know,
M

**Comment by neo191987** [comment]
Hi, I was able to fix the problem. For startAt I put 05 instead of 5, if it should start in 5 seconds and is already working properly.
