### ISSUE TITLE
YouTube Videos Appear Zoomed In or Size is too large

### ISSUE THREAD

**Issue by ConwayStern1969** [pupunzi/jquery.mb.YTPlayer#462]
I love the plugin. It came as part of a bootstrap template with a Hero video background. But the YouTube always appears zoomed in by about 20-30% it's as if the video is a lot larger than the container it's being played in.

Is there a setting in the JS or CSS that can control this?

**Comment by stevegrant1983** [comment]
> I love the plugin. It came as part of a bootstrap template with a Hero video background. But the YouTube always appears zoomed in by about 20-30% it's as if the video is a lot larger than the container it's being played in.
> 
> Is there a setting in the JS or CSS that can control this?

I found setting the optimizeDisplay option to false made it fit the container I was trying to use, but that was as an embedded video player of a live stream where I didn't want the actual YouTube stream to be easily obtainable.

The optimizeDisplay setting seems to basically set the underlying video player to be the size of the entire viewport, so if your hero block isn't full width, it'll appear zoomed.

**Comment by alansaviolobo** [comment]
+1 for optimizeDisplay = FALSE

**Comment by pupunzi** [comment]
@alansaviolobo The optimizeDisplay is an option that you can configure initializing the player. If you don't want it to be active just set it to false:
     data-property="{videoURL:'http://youtu.be/l_tHTmd5pgk',containment:'body',..., **optimizeDisplay:false**}">
