### ISSUE TITLE
Jquery 3 Upgrade  jQuery.browser

### ISSUE THREAD

**Issue by Pyronerd62** [pupunzi/jquery.mb.YTPlayer#466]
Migrating one of my sites to Jquery 3.x

Looking at Jquery Migrate  it's giving the warning jQuery.browser is deprecated.

**Comment by guyinpv** [comment]
I second this.
With WordPress 5.5+, the jQuery Migrate Helper plugin complains about this.

I suppose when 5.6+ comes, it's going to break.

Hopefully this can be fixed up to be more compatible soon, because every WP theme that uses it is going to be in trouble!

**Comment by tleifj** [comment]
Any updates on this issue? We've reached the point where it is breaking things now!

**Comment by pupunzi** [comment]
@tleifj Although this issue would not break anything as the jQuery.browser component in this plugin is not the jQuery default and deprecated one, I just published a new release (3.3.9) where this function has been renamed into jQuery.mbBrowser to prevent the WordPress alert.
