### ISSUE TITLE
issue with mac OS Big Sur

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [pupunzi/jquery.mb.YTPlayer#468]
hey there.
I'm using the beta version of mac os big sur
![mac](https://user-images.githubusercontent.com/1507948/96412332-dfd77b00-11f6-11eb-8dc6-df2bb3d68f86.jpg)

and since I upgraded, I'm getting this error
![errors](https://user-images.githubusercontent.com/1507948/96412732-6b510c00-11f7-11eb-8f5f-4aed62ed7d08.jpg)

![error 1](https://user-images.githubusercontent.com/1507948/96412813-8f145200-11f7-11eb-9686-f1a1b753a464.jpg)

![error2](https://user-images.githubusercontent.com/1507948/96412891-a81d0300-11f7-11eb-8abf-33fd2c0fa498.jpg)

**Comment by HCMF** [comment]
I'm having the same issue with Big Sur as well.

**Comment by groundnation** [comment]
I 'fixed' by removing the '0' from the OS reference i.e. 

test(nAgt)&&(e.version=/Mac OS X (1[\.\_\d]+)

Big Sur is OS 11, so causing an issue in this case.

**Comment by hablodoug** [comment]
same issue

**Comment by pupunzi** [comment]
With the latest commit, this issue should be fixed. You can test it by downloading the Master.  Soon available a new version.

**Comment by Mohsen-Khakbiz** [comment]
thank you!
