### ISSUE TITLE
How can I hide the pause overlays that appear suggesting other videos?

### ISSUE THREAD

**Issue by arkid** [pupunzi/jquery.mb.YTPlayer#472]
For a while it seems that certain videos we are showing in your player appear with a rectangular widget when the video is paused.  This is part of the code within the iframe of the youtube player it seems.   It has an outer class of ytp-pause-overlay.

I've tried various CSS selectors to hide the element but they don't seem to have any effect.

I've seen people talking about adding [certain url parameters](https://stackoverflow.com/questions/44027851/how-to-remove-pause-menu-video-suggestions-related-videos-class-ytp-pause-ov) to the youtube url as well but I'm not sure how to apply these when the video is used via this particular player ?

**Comment by arturmamedov** [comment]
https://github.com/pupunzi/jquery.mb.YTPlayer/issues/401

**Comment by arkid** [comment]
I now see this abundance setting.  It doesn't really work as a solution for me but thanks anyhow, i will close this.
