### ISSUE TITLE
Change Iframe default title value

### ISSUE THREAD

**Issue by tourtools** [pupunzi/jquery.mb.YTPlayer#479]
To be compliant with WCAG guidelines we need a way to modify the YT iframe title which is by default 
`title="YouTube video player"`
when having two or more background video on the same page, the title duplication is noticed as an accessibility issue,
is there a solution?

**Comment by pupunzi** [comment]
@tourtools Hi, the iframe is injected by the YouTube API and it is not under the plugin control. What I can try to do is to change it after the player has been initialized. At the time you can not modify it other than via javascript after the YTPlayer fires the onReady event:

` onReady            : function (player) {
            $(player.playerEl).attr("title", "YTPlayer_"+ (new Date().getTime()))
			  }`

**Comment by tourtools** [comment]
thank you @pupunzi 
it is a good workaround, 
now I have to verify if siteimprove.com (the accessibility tools we are using) checks the DOM before or after .js are triggered,

**Comment by pupunzi** [comment]
If it gets the iframe then it means that it checks the DOM after the javascript runs because the iframe is injected by the javascript API

**Comment by tourtools** [comment]
√ it works
