### ISSUE TITLE
autoPlay: true stopped working

### ISSUE THREAD

**Issue by icd2k3** [pupunzi/jquery.mb.YTPlayer#49]
It was working for a while, but I noticed it randomly stopped working for me this morning and now the user needs to click the play button (or use .playYTP()) to start the video.

It looks like in YTPlayer.checkForStartAt interval line 356:

if (YTPlayer.player.getCurrentTime() >= startAt && YTPlayer.player.getDuration() > 0) {

YTPlayer.player.getCurrentTime() is 0 and startAt is 1 so it never plays, but in my settings I have startAt: 0

Edit:
switching YTPlayer.opt.startAt ? YTPlayer.opt.startAt : 1;
to YTPlayer.opt.startAt ? YTPlayer.opt.startAt : 0;
fixes the issue, but seems like it could be some bigger problem

Version 2.7.0

**Comment by eirenaios** [comment]
@pupunzi Thank you! it worked!
