### ISSUE TITLE
WP YTPlayer & Divi Theme

### ISSUE THREAD

**Issue by giobrapisa** [pupunzi/jquery.mb.YTPlayer#496]
Hi Matteo,

i've just bought you plugin. Thanks for the amazing job.
I'm experiencing some problem using the short code.

Since the is no way to create shortcode on Divi constructor i created one shortcode using the default editor:
![image](https://user-images.githubusercontent.com/132462012/235920313-c7d043c8-78f8-4a39-9419-981812ab1821.png)
Here's the shortcode:
[mbYTPlayer url="https://www.youtube.com/watch?v=erG6jfJpqm8" custom_id="YTPlayer_579169530" elementselector="abcd" autoplay="true" mute="true" ratio="auto" isinline="false" gofullscreenonplay="false" showcontrols="false" realfullscreen="true" printurl="true" loop="false" optimize_display="true" anchor="center,center" addraster="false" stopmovieonblur="false" remember_last_time="false" gaTrack="false" ]

I opened a new page with divi builder and copied the Shortcode into a new text element.
![image](https://user-images.githubusercontent.com/132462012/235920896-9e50fde4-9cf0-4557-90b4-ca319f4f888e.png)

Then, with the builder, i edited the section.
I tried to put the attribute "abcd" in this 2 places but nothing happens:
![image](https://user-images.githubusercontent.com/132462012/235921142-a2d6da19-a568-4568-ac57-7ee2038b6074.png)

Could you please help me? THANKS A LOT! :)

Giovanni

**Comment by pupunzi** [comment]
Hi Giovanni,
I think the problem is that you should refer to the page element adding the "#" to specify it is an ID:

**elementselector="#abcd"** and add it as ID to the DIVI element you want to use.

Hope this can help.
All the best,
Matteo

**Comment by giobrapisa** [comment]
Hi Matteo,
thanks for the quick reply.

PERFECT, putting the "#" just in **elementselector="#abcd"** in the shortcode.
On Divi side:
![image](https://user-images.githubusercontent.com/132462012/235941211-8fe1f5c0-0eea-4a70-9a92-29b265fc702f.png)
