### ISSUE TITLE
Large resolution video not fully visible

### ISSUE THREAD

**Issue by uvassal** [pupunzi/jquery.mb.YTPlayer#497]
With example below video, not all parts of video are visible. The overflow parts is hidden.
https://www.youtube.com/watch?v=0smM0-ktvf4

**Comment by pupunzi** [comment]
Hi @uvassal,
The plugin default behaviour is similar to the CSS  "cover" for background images.
That means it adapt and crop the view to best cover all the containment area.
If you want to display all the video you can set the "optimizeDisplay" option to false.

**Comment by uvassal** [comment]
thanks, I didn't understand that.
