### ISSUE TITLE
playlists

### ISSUE THREAD

**Issue by riisjensen** [pupunzi/jquery.mb.YTPlayer#52]
Hi, the YTplayer is being used in a Joomla template, Cashemir, that I have purchased.
I am trying to figure out if YTplayer can play YouTube playlists.
I have tried inserting one (PLTKV7BkhP7i0rWOaChXnqckJV_7-IKgdt) but it doesn't seem to be working.
Can the YTplayer handle a YouTube playlist (instead of manually inserting a number of videos in the script)?

Carsten.

**Comment by Akhileshvk** [comment]
$(function(){
			var videos = [
            {videoURL:"https://www.youtube.com/watch?t=11&v=REAm6sxDZ2Q",containment:'.home-section',autoPlay:true, mute:false, startAt:0,opacity:1, loop:false, opacity:1, showControls:false, showYTLogo:false, vol:25},
            {videoURL: "https://www.youtube.com/watch?t=13&v=pwePIO3TMxU",containment:'.home-section',autoPlay:true, mute:true, startAt:0,opacity:1, loop:false, opacity:1, showControls:false, showYTLogo:false, vol:25},
            {videoURL: "https://www.youtube.com/watch?v=Rm-vBq-1T1k",containment:'.home-section',autoPlay:true, mute:false, startAt:0,opacity:1, loop:false, opacity:1, showControls:false, showYTLogo:false, vol:25}
        ];
		var player = $(".video-player").mb_YTPlayer();
		player.YTPlaylist(videos, true);
		});

**Comment by pupunzi** [comment]
You should not use the mb_YTPlayer() method but just the YTPlaylist():

var player =  $(".video-player").YTPlaylist(videos, true);

**Comment by jeremybphillips** [comment]
Hi, when using YTPlaylist(), I see that there are 'next' and 'prev' methods, but is there a way play a specific video in the list?

For example, I have the playlist also represented in a grid next to the player, when the user clicks on a random row, I want to play that video from the playlist.

Thanks
