### ISSUE TITLE
Video getting cropped as background video and not optimizing display

### ISSUE THREAD

**Issue by aaronjpitts** [pupunzi/jquery.mb.YTPlayer#59]
Hey, great plugin. My only issue is that my background video is getting cropped, I have set the optimizeDisplay to true but it is having no affect. I had this working fine with a previous version of the plugin. I am now using the latest version. You can see my issue here: http://dev.aaronpitts.ch/hg/

Many thanks

**Comment by Mithgol** [comment]
Some setting for YTPlayer to behave like `background-size: contain` (instead of like `background-size: cover`) is necessary.

I am not sure if `optimizeDisplay` is intended to do that (after all, `optimizeDisplay` is explained as “will fit the video size into the window size optimizing the view” and thus it might be some different feature). But some setting for mimicking `background-size: contain` is necessary.

**Comment by mrjlynch** [comment]
I am having trouble acheiving this. As a temporary hack I am playing around with the height of the iframe: 

```
.playerBox {
  min-height: 1080px !important;
}
```

Any better ideas?

**Comment by pupunzi** [comment]
@mrjlynch
What is exactly the problem you're having?
from the hack you're suggesting seams the player doesn't fit the height of the page... if you can send me the URL where you're having problems I can take a look.

Bye,
Matteo

**Comment by atif-kht** [comment]
Hi Pupunzi !

I am also facing the same issue. I have assigned the video to div element but video seems to be cropped. I have tried setting ratio as well to 'auto', 4/3 and 16/9. But it still shows like video is cropped.

Thanks.

**Comment by pupunzi** [comment]
@atif-kht: If the Div you assigned the video has not the same aspect ratio of the video itself then the video will be cropped. If set the "optimizeDisplay" option to false then the video will never crop adding black bars on the top or on the bottom to compensate for the difference in height or width.

**Comment by simplecreatif** [comment]
Has there ever been a solution to switch the the YTPlayer from 'cover' to 'contain'?

**Comment by pupunzi** [comment]
@simplecreatif : If you want the video never been cropped you should set the "optimizeDisplay" option to false; that way it will behave as "contain".
