### ISSUE TITLE
Image preview before loading video

### ISSUE THREAD

**Issue by purgeru** [pupunzi/jquery.mb.YTPlayer#60]
Is that possible to make if it isn't yet?That tere would be no white(empty) div background.

**Comment by wuzzy12** [comment]
Not possible when your using a playlist. Dealing with this now.

**Comment by gdnwebmedia** [comment]
Thank you guys. I understand the limitations of looping a video in the middle of a playlist... It would be great to have a playlist and enable a way to loop the last video of the list or have the playlist run once and then trigger a function to play a single video which can then triggered to loop or not.
Hope that makes sense. Thanks again!

**Comment by karlosdpm** [comment]
It think the best way to load a picture as background until the video starts in mb YTPlayer is by applying a css snippet. Please see this article.

http://www.kmbytes.com/how-to-load-a-picture-as-background-until-the-video-starts-in-mb-ytplayer/

It works beautifully for me every time. I hope this helps!
