### ISSUE TITLE
Events are all fired on page load

### ISSUE THREAD

**Issue by ghost** [pupunzi/jquery.mb.YTPlayer#67]
I worked with a previous version of the plugin, but that one is now full of errors (chrome extensions, youtube errors) probably caused by the YouTube API. In the latest version, it looks like all events are executed after the page has loaded, while they're indicating that they only should do something whenever the function is triggered.

$('#bgndVideo').on("YTPEnd",function(){
   // For example this function is triggered and fired after loading the page
});

The result is a glitching page that loads all these events one time. (YTPStart, YTPPause, YTPEnd)
These functions / events used to work before.

**Comment by hj84** [comment]
Enfortunately I'm (still) experiencing the same behaviour as ghost commented. See http://www.filedropper.com/videotest for an example of what I mean. You'll find comments in the videotest.js file.
