### ISSUE TITLE
event: when video has finished buffering

### ISSUE THREAD

**Issue by hedii** [pupunzi/jquery.mb.YTPlayer#68]
Hi,
Is there an event fired when the video has finished buffering ?
It would be useful to display a play button only when the video is entirely buffered and can start playing (when the youtube background image for one video is yet shown).
On your doc, we have: 
YTPBuffering: when video is buffering

but no event for buffering end.
Maybe I missed something...

Thank you in advance

**Comment by durancristhian** [comment]
@hedii any piece of news about that? I want to do the same

**Comment by pupunzi** [comment]
Hi,
there's no "buffering end" or "video can play" event fired by the YT API. Sorry

**Comment by durancristhian** [comment]
@pupunzi: thanks for answering! I supose that but I wanted to be sure (:

I'm trying to find a way to hide the player during a few seconds before show it as background and, in the meantime, show an image as "poster". Anyway, thanks!

**Comment by hedii** [comment]
@durancristhian no, I gave up what I wanted to do. You can hide the player some few seconds on page load, but it will not be synced with youtube buffering :(
I close the issue, thx @pupunzi
