### ISSUE TITLE
Video not work in Safari browser of apple mobile device

### ISSUE THREAD

**Issue by tienloc1** [pupunzi/jquery.mb.YTPlayer#73]
I have iPhone 4 (iOS 7.x) and use safari to test website: http://ideologyproductions.com/. Every thing seems work fine in my laptop (use Windows 7). But in the iPhone 4 video section not work.

I was tried research info to figure out and solve it but not thing info helpful.

Please help me to solve my issue. Thank so much for reply!

**Comment by pbouda** [comment]
Can I somehow find out programmatically if background video is supported? I want to do sth on the `YTPStart` event (removing a preloader), but this is never fired on mobile. What's the best option to still run the code if starting the video does not work?

**Comment by pupunzi** [comment]
As the background video doesn't work on mobile the YTPStart event is never fired. 
If you have javasript that depends on that event you can manually trigger the event in the case of mobile:

Ex:
```javascript
if (jQuery.browser.mobile)
  jQuery("#myVideoSelector").trigger("YTPStart");
```
Or you can just write something like:

```javascript
if (jQuery.browser.mobile) {
   // run some code
} else {
   $("#myVideoSelector").on("YTPStart", function(){
       // run some code
   }
}
```
Bye,
Matteo

**Comment by pbouda** [comment]
Thanks, I used the second solution, works fine!

**Comment by droslean** [comment]
Hi pupunzi 
Awesome work ,well done. Only thing is that its not working for safari browsers.Do you have any solution ?

**Comment by jphellemons** [comment]
@droslean have you found a solution?
