### ISSUE TITLE
Some IDs from youtube not works

### ISSUE THREAD

**Issue by hamdan-mahran** [pupunzi/jquery.mb.YTPlayer#81]
Hi,
Thanks for this awesome plugin, but i have issue with it, i dont know why some ID not works for me :( 
Thanks very much

**Comment by pupunzi** [comment]
Hi,
You must check that the video is public and can be embedded outside Youtube, otherwise it can't be shown.

**Comment by hamdan-mahran** [comment]
Thanks very much pupuni :)
you all right, the video is public now and its works very good
Best Regards
