### ISSUE TITLE
playYTP Bug

### ISSUE THREAD

**Issue by Bluxart** [pupunzi/jquery.mb.YTPlayer#83]
Hi, your plugin is fantastic, but I find a bug ( also in your demo ).

I create a button to play the video, when I click immediately after the page is loaded the video start but stopped after 1 second and I need re-click to the button for start completely the video.

But if I wait some seconds after the page is loaded ( 3 seconds max ) the play events work perfectly.

You can see the bug on your demo page, I tested it with Chrome.

URL: http://pupunzi.com/mb.components/mb.YTPlayer/demo/demo_as_player.html

**Comment by pupunzi** [comment]
Hi,
That depends on the fact that the video is not ready yet and need to buffer fiew seconds befor starting.
Within the next commit the button bar will show only if the video has enough buffer to start.

Bye,
Matteo

**Comment by Bluxart** [comment]
Thanks for the explanation.
Another small request, it would be nice to decide when you have autoplay enabled the transition duration. ( opacity effect by default is 2000ms )

**Comment by pupunzi** [comment]
I'll see to add this option on the next release.
