### ISSUE TITLE
Bandwidth Usage Optimization?

### ISSUE THREAD

**Issue by bhamodi** [pupunzi/jquery.mb.YTPlayer#84]
Hello there @pupunzi,

I have been analyzing the bandwidth consumption of this tool when loading up my website and it seems to me that a lot of bandwidth is downloaded in the initial moments of downloading the video. The video I've been using is about `20MB` with `default` settings from YouTube and due to the large initial download, there seems to be a a noticeable delay loading up the page and video.

Is there anyway we can optimize this by breaking the download up into smaller chunks and intervals?

Also, depending on the user's internet speeds, I think it would be a good idea to serve them a different video quality. For example, the `240p` version of the above mentioned video is only `7MB`. This is a huge difference when it comes to download time. I think it would be a really cool feature if this tool can determine the user's internet speed and chose the appropriate video quality to have a good user experience.

**Comment by pupunzi** [comment]
Hi,
Youtube itself does the bandwidth optimization according to the user connection speed; also the video quality is controlled by Youtube; you can just suggest which quality you want but your choice is not mandatory.

Bye,
Matteo
