### ISSUE TITLE
Usage on non-empty divs

### ISSUE THREAD

**Issue by djalexa** [pupunzi/jquery.mb.YTPlayer#86]
Thank you for this plugin and frequent updates!!!
 
As of v2.7.8 (I used v2.7.5 before it), I've found that it can not be assigned to non-empty div due to line:
var isPlayer = YTPlayer.opt.containment.is(jQuery(this)) && jQuery(this).children().length == 0;

Is this check necessary 
jQuery(this).children().length == 0 
as I'm using bg video on some Bootstrap rows for example?

**Comment by pupunzi** [comment]
Hi,
That condition has been set becouse I assumed that if the player is instanced as "self" contained it is used as "player" and should not contains any other elements. 
But as you are pointing uot this is not correct as at the time the player get hidden if it contains elements.

I'll fix this for the next release; you can comment the second condition to prevent this issue:
 var isPlayer = YTPlayer.opt.containment.is(jQuery(this)) /*&& jQuery(this).children().length == 0*/;

Bye,
Matteo
