### ISSUE TITLE
Quality Settings Not Being Applied

### ISSUE THREAD

**Issue by bhamodi** [pupunzi/jquery.mb.YTPlayer#90]
Hello @pupunzi 

So I've been trying to serve the medium/small quality version of a YouTube video (480p/360p), but it appears that adding the quality parameter isn't working. It continues to be under the default setting and therefore giving me the HD version (720p) since my internet speed is fast enough.

I've noticed the only way to get the video quality to be 480p or 360p was to throttle my internet speed.

Here is the HTML code that I'm using to display the video player:
```html
<a id="background-video" class="player" data-property="{videoURL:'kn-1D5z3-Cs',mute:true,quality:'small',showControls:false,showYTLogo:false,realfullscreen:false,gaTrack:false}"></a>
```

**Comment by bhamodi** [comment]
@pupunzi

**Comment by pupunzi** [comment]
I'll check this behavior.

**Comment by cotwitch** [comment]
For me, quality setting specified in HTML constructor works fine in Firefox(Linux), Safari(Mac), but failing in Chrome(Linux). Other browsers behavior is unknown.

**Comment by bhamodi** [comment]
@cotwitch - thanks for the input! I noticed this issue in Chrome(Windows) as well.
