### ISSUE TITLE
Chrome, Failed to load resource: the server https://www.youtube.com/get_video?noflv=1&video_id=######  responded with a status of 404 (OK)

### ISSUE THREAD

**Issue by julianromera** [pupunzi/jquery.mb.YTPlayer#91]
I am getting a 404 error when playing a Youtube Loop video on Chrome, though the video is playing fine. (I have tested Chrome, Safari, Opera and FF)

My issue with this is the error 404 may make the page load slower. (And not sure, impact on Pagespeed, and thus, in SEO). 
 
I have done some research on this and it seems to be an unresolved Google issue that has been ongoing for a long time 
https://code.google.com/p/gdata-issues/issues/detail?id=6267

There seems to be a possible solution (I have not tried this).
https://stackoverflow.com/questions/24177831/youtube-player-api-throws-404

Is there any way that you could fix this error?

The detailed error is: 

Failed to load resource: the server https://www.youtube.com/get_video?noflv=1&video_id=tmDQzWusJZ0&cpn=N4JsA6WMXxy3qWN7&el=embedded&referrer&eurl=http%3A%2F%2Fdev.eaz.ie%2F&fmt=244&ptk=youtube_none&splay=1&start=1000  responded with a status of 404 (OK)

**Comment by Markillion** [comment]
I started seeing this issue randomly after a few loops.

**Comment by emaia** [comment]
Same here

**Comment by valeriu** [comment]
+1

**Comment by Independente** [comment]
same
