### ISSUE TITLE
Volume force-setting globally

### ISSUE THREAD

**Issue by df-5** [pupunzi/jquery.mb.YTPlayer#94]
If I set mute on my embed, it globally sets volume down to 0 - if I open any YT link elsewhere - in new tab, etc, it is completely mute by default. Not sure how this can be fixed..

**Comment by pupunzi** [comment]
What browser and what OS are you using?
It doesn't happen to me...

**Comment by daveachuk** [comment]
This is happening to me too.

Steps to reproduce:

1) Go to Youtube.com, watch a video, make sure volume is up.
2) Go to a mb_YTPlayer page where mute:true is set and let the video play
3) Go back to Youtube.com, watch a video. Video is now muted by default.

**Comment by pupunzi** [comment]
It probably depends by the Youtube API... I'll see if it is mentioned somewhere on the web.

**Comment by ArkQA** [comment]
Guess: Try using a browser or video that uses the flash player instead of the html5 player.

**Comment by niek33** [comment]
Facing the same issue, all of a sudden the mute: true option gets overridden. I expect this to be some kind of change in the YouTube API. 

Is there another way to force the video to be played muted?

**Comment by ArkQA** [comment]
My best guess is that this is based on whether the player used is forced to flash or html5/the new player.

In `%appdata%\Macromedia\Flash Player\#SharedObjects\[uniqueid]\s.ytimg.com\soundData.sol` it appears to persist volume data on flash, shared across instances..

**Comment by pupunzi** [comment]
There's no way on my side to prevent this issue... I'm sorry.
