### ISSUE TITLE
Change body background before and after video has started

### ISSUE THREAD

**Issue by mizukimadness** [pupunzi/jquery.mb.YTPlayer#95]
Hello!

I have a fallback background image on body. When the video hasn't started yet, the background image is visible for a short time, then the video fades in from black. To avoid this, I have changed the background image to "none" with jQuery. See below: 

    $(function(){
		if (!jQuery.browser.mobile) 		
		$("body").css("background-image", "none");
		$("body").css("background-color", "black")
		$(".player").YTPlayer();			
    });

However - to make sure the fallback background image on body always works - I want to change this back with jQuery when the video has started playing. I think using YTPUnstarted in some way would work, which I have tried and failed with, as I'm not really used to working with jQuery/JS.

Is there a way to achieve this?

Thanks in advance!

**Comment by pupunzi** [comment]
The YTUnstarted event is triggered when the player is loaded, but the video has not been started; this is a very rare case.
You should use the YTPStart instead.

Bye,
M
