### ISSUE TITLE
Video on loop not starting from begining.

### ISSUE THREAD

**Issue by FastWP** [pupunzi/jquery.mb.YTPlayer#97]
He have a customer using one of our themes, 
http://www.valentinaciarapica.com/
if you check on home section the video is in loop mode, but when it starts it skips 1 sec, and it ends about 3 second before video end. 
here is the video 
https://www.youtube.com/watch?v=xJrOiN9JSKA
I am not sure if this is a issue or not.. 
Thanks.

**Comment by pupunzi** [comment]
HI,
it's not an issue but the correct behavior; the 3 sec at the end are needed to prevent the display of the "play" youtube button and the first second is loosed by the fade in. If you are the owner of the video you should publish it considering that and adding some blank at the beginning and at the end.

Bye,
Matteo
