### ISSUE TITLE
Android 5.0.1

### ISSUE THREAD

**Issue by stefanbinder** [pupunzi/jquery.mb.YTPlayer#98]
Hi, 

I'v tried your demo on my smartphone (Nexus 5 with Android 5.0.1) but no single one works on the device. I can't start the video. Sometimes I get a preview image but thats it :(

Did you test the player on mobile devices - should it work?

I really like your player and it works really good! It would be great if your player works on the newest Android version :)

Thank you for your reply

kind regards
Stefan

**Comment by pupunzi** [comment]
Hi,
This component can't work on mobile devices due to the vendor policies regarding the media manipulation via javascript. You should provide a fall-back behavior for mobile devices.

Bye,
Matteo
